'use client';
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {authClient,downloadBlob} from '@/lib/ops/client';
import {extractCandidates,sourceLink,type Candidate,type MeetingDetail,type MeetingsIndex,reviewSchema} from '@/lib/ops/meetings/model';
import {OPS_RELEASE} from '@/lib/ops/contracts';
import {mayNavigate,useEntryGuard} from '../navigation';

class MeetingError extends Error {constructor(message:string,public code:string){super(message);}}
async function request<T>(path='',data?:unknown):Promise<T>{
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);
 try{const r=await fetch('/api/ops/meetings'+path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined,credentials:'same-origin',cache:'no-store',signal:controller.signal});const j=await r.json();if(!r.ok)throw new MeetingError(j.error?.message||'The meeting request could not be confirmed.',j.error?.code||'unavailable');return j;}catch(e){if(e instanceof MeetingError)throw e;throw new MeetingError('The connection was interrupted. Your open entry is retained.','unavailable');}finally{clearTimeout(timer);}
}
const day=(date:string)=>new Date(date+'T12:00:00+10:00').toLocaleDateString('en-AU',{day:'numeric',month:'short',year:'numeric',timeZone:'Australia/Brisbane'});
const FOCUSABLE_IN_DRAWER='a[href], area[href], button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [contenteditable="true"], [tabindex]:not([tabindex="-1"])';
function drawerFocusables(drawer:HTMLElement){return Array.from(drawer.querySelectorAll<HTMLElement>(FOCUSABLE_IN_DRAWER)).filter(element=>{const style=window.getComputedStyle(element);return !element.closest('[inert]')&&element.getAttribute('aria-hidden')!=='true'&&style.display!=='none'&&style.visibility!=='hidden';});}

function ReviewForm({candidate,userId,onSaved,onClose,onDenied}:{candidate:Candidate;userId:string;onSaved:()=>Promise<void>;onClose:()=>void;onDenied:()=>void}){
 const [title,setTitle]=useState(candidate.title),[owner,setOwner]=useState(candidate.owner_text),[due,setDue]=useState(candidate.due_on||''),[state,setState]=useState(candidate.state),[note,setNote]=useState(candidate.review_note),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const retry=useRef<{intent:string;id:string}|null>(null);useEntryGuard(true,busy);
 return <form className="mt-review" aria-label="Review meeting action" onSubmit={async e=>{e.preventDefault();if(busy)return;setError('');setBusy(true);try{const payload={candidateId:candidate.id,expectedActorId:userId,expectedVersion:candidate.version,title,owner,dueOn:due,state,note};const intent=JSON.stringify(payload);if(retry.current?.intent!==intent)retry.current={intent,id:crypto.randomUUID()};const parsed=reviewSchema.safeParse({...payload,requestId:retry.current.id});if(!parsed.success)throw new Error(parsed.error.issues[0].message);await request('/review',parsed.data);await onSaved();}catch(e){if(e instanceof MeetingError&&['unauthenticated','forbidden'].includes(e.code)){onDenied();return;}setError((e as Error).message);}finally{setBusy(false);}}}>
  <div className="mt-section-heading"><h3>Review action {candidate.ordinal}</h3><button type="button" disabled={busy} onClick={()=>{if(mayNavigate())onClose();}}>Close</button></div>
  <label>Action<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={1000} required/></label>
  <div className="mt-form-grid"><label>Accountable owner<input value={owner} onChange={e=>setOwner(e.target.value)} maxLength={100}/></label><label>Confirmed due date<input type="date" min="2000-01-01" max="2100-01-01" value={due} onChange={e=>setDue(e.target.value)}/></label></div>
  <label>Review status<select value={state} onChange={e=>setState(e.target.value as Candidate['state'])}><option value="proposed">Needs review</option><option value="reviewed">Reviewed</option><option value="dismissed">Dismissed</option></select></label>
  <label>Review note<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={2000} rows={3} placeholder="Clarify the name, date, dependency or dismissal reason."/></label>
  <p className="mt-muted">Review confirms the interpretation of the notes. It does not approve expenditure, certify compliance or mark work completed.</p>
  {error&&<p role="alert" className="mt-error">{error}</p>}<button className="ops-primary" disabled={busy}>{busy?'Saving review…':'Save review'}</button>
 </form>;
}
function ImportForm({index,onSaved,onClose,onDenied}:{index:MeetingsIndex;onSaved:(id:string)=>Promise<void>;onClose:()=>void;onDenied:()=>void}){
 const [title,setTitle]=useState(''),[date,setDate]=useState(''),[notes,setNotes]=useState(''),[sourceUrl,setSourceUrl]=useState(''),[workspace,setWorkspace]=useState(index.workspaces.find(w=>w.role!=='viewer')?.id||''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const identity=useRef({request:crypto.randomUUID(),source:'manual:'+crypto.randomUUID()}),retry=useRef('');useEntryGuard(!!(title||date||notes||sourceUrl),busy);
 const count=extractCandidates(notes).length;
 const submit=async(e:FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{const payload={workspaceId:workspace,title,heldOn:date,sourceText:notes,sourceKey:identity.current.source,sourceKind:'manual',sourceUrl};const intent=JSON.stringify(payload);if(retry.current&&retry.current!==intent)identity.current.request=crypto.randomUUID();retry.current=intent;const r=await request<{id:string}>('',{...payload,requestId:identity.current.request});await onSaved(r.id);}catch(e){if(e instanceof MeetingError&&['unauthenticated','forbidden'].includes(e.code)){onDenied();return;}setError((e as Error).message);}finally{setBusy(false);}};
 return <form className="mt-import ops-card" aria-label="Import meeting notes" onSubmit={submit}>
  <div className="mt-section-heading"><h2>Add meeting notes</h2><button type="button" disabled={busy} onClick={()=>{if(mayNavigate())onClose();}}>Close</button></div>
  <div className="mt-form-grid"><label>JV workspace<select value={workspace} onChange={e=>setWorkspace(e.target.value)}>{index.workspaces.filter(w=>w.role!=='viewer').map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label>Meeting date<input type="date" min="2000-01-01" max="2100-01-01" value={date} onChange={e=>setDate(e.target.value)} required/></label></div>
  <label>Meeting title<input value={title} onChange={e=>setTitle(e.target.value)} minLength={3} maxLength={240} required/></label>
  <label>Gmail source link (optional)<input type="url" inputMode="url" autoComplete="url" value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} maxLength={600} placeholder="https://mail.google.com/mail/..."/></label>
  <label>Original notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={200000} minLength={20} rows={10} required placeholder="Paste the Zoom meeting summary, including its Next steps section."/></label>
  <p className="mt-muted">{count} action candidates detected. Owners and dates remain subject to review. Reuse the same Gmail link for a corrected copy so it becomes a source revision.</p>
  {error&&<p className="mt-error" role="alert">{error}</p>}<button className="ops-primary" disabled={busy||!workspace}>{busy?'Saving notes…':'Save meeting'}</button>
 </form>;
}

export default function MeetingsWorkspace(){
 const [index,setIndex]=useState<MeetingsIndex|null>(null),[detail,setDetail]=useState<MeetingDetail|null>(null),[loading,setLoading]=useState(true),[opening,setOpening]=useState(false),[error,setError]=useState(''),[locked,setLocked]=useState(false),[menu,setMenu]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[tab,setTab]=useState<'actions'|'notes'>('actions'),[editing,setEditing]=useState<Candidate|null>(null),[adding,setAdding]=useState(false),[email,setEmail]=useState(''),[authBusy,setAuthBusy]=useState(false),[authMessage,setAuthMessage]=useState('');
 const loadSeq=useRef(0),detailSeq=useRef(0),identity=useRef(''),autoIndex=useRef<MeetingsIndex|null>(null),visibleDetail=useRef<MeetingDetail|null>(null),menuButton=useRef<HTMLButtonElement>(null),closeButton=useRef<HTMLButtonElement>(null),drawer=useRef<HTMLElement>(null),header=useRef<HTMLElement>(null),main=useRef<HTMLElement>(null),menuWasOpen=useRef(false);visibleDetail.current=detail;
 const invalidate=useCallback(()=>{loadSeq.current++;detailSeq.current++;},[]);
 const clear=useCallback(()=>{loadSeq.current++;detailSeq.current++;identity.current='';setIndex(null);setDetail(null);setEditing(null);setAdding(false);setLocked(true);setOpening(false);},[]);
 const fail=useCallback((e:unknown)=>{if(e instanceof MeetingError&&['unauthenticated','forbidden'].includes(e.code)){clear();}setError((e as Error).message);},[clear]);
 const load=useCallback(async()=>{const seq=++loadSeq.current;setLoading(true);setError('');try{const data=await request<MeetingsIndex>();if(seq!==loadSeq.current)return;if(identity.current&&identity.current!==data.userId){detailSeq.current++;setDetail(null);setEditing(null);setAdding(false);}if(visibleDetail.current&&!data.workspaces.some(w=>w.id===visibleDetail.current?.meeting.workspace_id)){detailSeq.current++;setDetail(null);setEditing(null);setAdding(false);}identity.current=data.userId;setIndex(data);setLocked(false);}catch(e){if(seq===loadSeq.current)fail(e);}finally{if(seq===loadSeq.current||!identity.current)setLoading(false);}},[fail]);
 const open=useCallback(async(id:string,revision?:number)=>{const seq=++detailSeq.current,actor=identity.current;setOpening(true);setError('');setDetail(null);setEditing(null);try{const data=await request<MeetingDetail>('/'+id+(revision?'?revision='+revision:''));if(seq===detailSeq.current&&actor===identity.current){setDetail(data);setTab(revision?'notes':'actions');const u=new URL(location.href);u.searchParams.set('meeting',id);history.replaceState(null,'',u.pathname+u.search);}}catch(e){if(seq===detailSeq.current)fail(e);}finally{if(seq===detailSeq.current)setOpening(false);}},[fail]);
 useEffect(()=>{void load();let unsubscribe=()=>{};try{const {data}=authClient().auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'){clear();setLoading(false);}else if(session?.user.id&&identity.current&&session.user.id!==identity.current){clear();setTimeout(()=>void load(),0);}});unsubscribe=()=>data.subscription.unsubscribe();}catch{}return()=>{invalidate();unsubscribe();};},[load,clear,invalidate]);
 useEffect(()=>{if(!index||detail||opening||autoIndex.current===index)return;autoIndex.current=index;const chosen=new URL(location.href).searchParams.get('meeting');const row=index.meetings.find(m=>m.id===chosen)||index.meetings[0];if(row)void open(row.id);},[index,detail,opening,open]);
 useEffect(()=>{let last=0;const resume=()=>{if(document.visibilityState!=='visible'||Date.now()-last<15000)return;last=Date.now();void load();};window.addEventListener('focus',resume);window.addEventListener('pageshow',resume);document.addEventListener('visibilitychange',resume);return()=>{window.removeEventListener('focus',resume);window.removeEventListener('pageshow',resume);document.removeEventListener('visibilitychange',resume);};},[load]);
 useEffect(()=>{if(!menu){if(!menuWasOpen.current)return;menuWasOpen.current=false;const frame=requestAnimationFrame(()=>menuButton.current?.focus());return()=>cancelAnimationFrame(frame);}menuWasOpen.current=true;const background=[header.current,main.current,...Array.from(document.querySelectorAll<HTMLElement>('.skip-link'))].filter((element):element is HTMLElement=>Boolean(element)),previous=background.map(element=>({inert:element.hasAttribute('inert'),ariaHidden:element.getAttribute('aria-hidden')}));background.forEach(element=>{element.setAttribute('inert','');element.setAttribute('aria-hidden','true');});return()=>background.forEach((element,index)=>{const original=previous[index];if(original.inert)element.setAttribute('inert','');else element.removeAttribute('inert');if(original.ariaHidden===null)element.removeAttribute('aria-hidden');else element.setAttribute('aria-hidden',original.ariaHidden);});},[menu]);
 useEffect(()=>{if(!menu)return;const dialog=drawer.current;if(!dialog)return;const focusInitialControl=()=>{const initial=closeButton.current||drawerFocusables(dialog)[0]||dialog;initial.focus({preventScroll:true});};const trapFocus=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();setMenu(false);return;}if(event.key!=='Tab')return;const focusable=drawerFocusables(dialog);if(!focusable.length){event.preventDefault();dialog.focus({preventScroll:true});return;}const first=focusable[0],last=focusable[focusable.length-1],active=document.activeElement;if(event.shiftKey&&(active===first||!dialog.contains(active))){event.preventDefault();last.focus({preventScroll:true});}else if(!event.shiftKey&&(active===last||!dialog.contains(active))){event.preventDefault();first.focus({preventScroll:true});}};const frame=requestAnimationFrame(focusInitialControl);document.addEventListener('keydown',trapFocus);return()=>{cancelAnimationFrame(frame);document.removeEventListener('keydown',trapFocus);};},[menu]);
 const meetings=index?.meetings.filter(m=>(m.title+' '+m.workspace_name).toLowerCase().includes(query.toLowerCase()))||[];
 const candidates=detail?.candidates.filter(c=>filter==='all'||c.state===filter)||[];
 return <div className="ops-shell mt-shell"><header className="ops-topbar" ref={header}><a href="/ops/meetings" className="ops-brand">MINERAL<span>X</span><small>OPERATIONS</small></a><button ref={menuButton} className="ops-mobile-menu" onClick={()=>setMenu(!menu)} aria-controls="meetings-navigation" aria-expanded={menu}>Menu</button><span className="mt-private">Private JV workspace</span><div className="mt-account">{index?<><span>{index.email}</span><button onClick={async()=>{if(!mayNavigate())return;try{const {error}=await authClient().auth.signOut();if(error)throw new Error('Sign-out could not be confirmed. Retry before leaving this device.');clear();}catch(e){fail(e);}}}>Sign out</button></>:<a href="/ops/login?next=/ops/meetings">Staff sign in</a>}</div></header>
 {menu&&<div className="ops-nav-backdrop" aria-hidden="true" onClick={()=>setMenu(false)}/>}<aside ref={drawer} className={'ops-sidebar '+(menu?'is-open':'')} id="meetings-navigation" role={menu?'dialog':undefined} aria-modal={menu||undefined} aria-label={menu?'Meetings navigation':undefined} tabIndex={menu?-1:undefined}><nav aria-label="Meetings navigation"><div className="ops-nav-mobile-heading"><span>Navigation</span><button ref={closeButton} type="button" onClick={()=>setMenu(false)}>Close</button></div><section className="ops-nav-group"><span className="ops-nav-caption">PRIVATE WORKSPACE</span><a href="/ops/meetings" aria-label="Meetings" aria-current="page" onClick={()=>setMenu(false)}>Meetings<small aria-hidden="true">Notes & reviewed actions</small></a></section><section className="ops-nav-group ops-nav-utility"><span className="ops-nav-caption">OTHER WORKSPACES</span><a href="/ops?mode=development" aria-label="Device workspace" onClick={()=>setMenu(false)}>Device workspace<small aria-hidden="true">Local pits, exploration & planning</small></a><a href="/ops/login" aria-label="Shared Operations" onClick={()=>setMenu(false)}>Shared Operations<small aria-hidden="true">Staff sign-in required</small></a></section></nav><footer><span>Release {OPS_RELEASE}</span><span>Private notes · verified access</span></footer></aside>
 <main className="ops-content mt-main" id="main-content" ref={main}><div className="mt-page-heading"><div><p className="ops-eyebrow">MINERALX / JOINT VENTURES</p><h1>Meetings</h1><p>Decisions, next steps and the notes behind them.</p></div>{index?.workspaces.some(w=>w.role!=='viewer')&&<button className="ops-primary" onClick={()=>{if(mayNavigate()){setEditing(null);setAdding(true);}}}>Add meeting notes</button>}</div>
 {loading&&!index&&!locked&&<p role="status">Checking your private meeting access…</p>}
 {locked&&<section className="mt-access ops-card"><div className="mt-lock-icon" aria-hidden="true">◇</div><p className="ops-eyebrow">YOUR JV RECORDS</p><h2>Sign in to view your meetings</h2><p>Meeting summaries and action lists are private. Verify your assigned email to open them across your devices.</p><form onSubmit={async e=>{e.preventDefault();if(authBusy)return;setAuthBusy(true);setAuthMessage('');setError('');try{const r=await request<{message:string}>('/signin',{email:email.trim()});setAuthMessage(r.message);}catch(e){setError((e as Error).message);}finally{setAuthBusy(false);}}}><label>Work email<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} maxLength={254} required/></label><button className="ops-primary" disabled={authBusy}>{authBusy?'Requesting sign-in link…':'Email me a secure sign-in link'}</button></form><p className="mt-muted">Open the link in this browser. You can also <a href="/ops/login?next=/ops/meetings">sign in with an existing password</a>.</p>{authMessage&&<p role="status" className="mt-success">{authMessage}</p>}</section>}
 {error&&<div role="alert" className="mt-error">{error}{!locked&&<button disabled={loading} onClick={()=>{if(mayNavigate())void load();}}>Retry loading</button>}</div>}
 {index&&<><section className="mt-intake"><span className="mt-dot"/><div><strong>Private archive</strong><p>{index.intake.message}</p></div><button disabled={loading} onClick={()=>{if(mayNavigate()){setDetail(null);void load();}}}>{loading?'Refreshing…':'Refresh meetings'}</button></section>
 <div className="mt-metrics"><div><span>Meetings</span><strong>{index.meetings.length}{index.more?'+':''}</strong></div><div><span>Action candidates</span><strong>{index.meetings.reduce((n,m)=>n+m.actions,0)}</strong></div><div><span>Needs review</span><strong>{index.meetings.reduce((n,m)=>n+m.pending,0)}</strong></div><div><span>Reviewed</span><strong>{index.meetings.reduce((n,m)=>n+m.reviewed,0)}</strong></div></div>
 {!index.workspaces.length&&<section className="ops-card"><h2>No JV workspace assigned to this account</h2><p>Your account is signed in, but it has no active membership for meeting notes. Use the email assigned to your JV access.</p></section>}
 {adding?<ImportForm index={index} onDenied={clear} onClose={()=>setAdding(false)} onSaved={async id=>{setAdding(false);await load();await open(id);}}/>:<div className="mt-workspace"><aside className="mt-list"><label>Find a meeting<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search title or JV…"/></label>{meetings.map(m=><button key={m.id} className={'mt-meeting-row '+(detail?.meeting.id===m.id?'selected':'')} aria-pressed={detail?.meeting.id===m.id} onClick={()=>{if(mayNavigate())void open(m.id);}}><small>{day(m.held_on)} · {m.workspace_name}</small><strong>{m.title}</strong><span>{m.actions} actions <em>{m.pending} need review</em></span></button>)}{!meetings.length&&<p className="mt-muted">{query?'No matching meetings.':'No meeting notes have been imported into your assigned workspace yet.'}</p>}{index.more&&<p className="mt-muted">Showing the 200 most recent meetings.</p>}</aside>
 <section className="mt-detail" aria-label="Meeting details">{opening&&<p role="status">Opening meeting notes…</p>}{detail&&<><div className="mt-detail-head"><p className="ops-eyebrow">{detail.meeting.workspace_name} · {day(detail.meeting.held_on)}</p><h2>{detail.meeting.title}</h2><div className="mt-detail-meta"><span>Source revision {detail.revision}</span><span>{detail.candidates.length} action candidates</span>{detail.source.source_url&&<a href={sourceLink(detail.source.source_url)} target="_blank" rel="noopener noreferrer">Open source email ↗</a>}</div></div>
 <div className="mt-tabs" aria-label="Meeting views"><button aria-pressed={tab==='actions'} onClick={()=>{if(mayNavigate()){setEditing(null);setTab('actions');}}}>Actions & review</button><button aria-pressed={tab==='notes'} onClick={()=>{if(mayNavigate()){setEditing(null);setTab('notes');}}}>Original notes</button></div>
 {tab==='actions'?<><div className="mt-action-toolbar"><label>Show actions<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All actions</option><option value="proposed">Needs review</option><option value="reviewed">Reviewed</option><option value="dismissed">Dismissed</option></select></label><p>Review records interpretation; completion and approvals stay in operational work.</p></div>{candidates.map(c=><article className="mt-action" key={c.id}><div className="mt-action-top"><span className="mt-ordinal">{String(c.ordinal).padStart(2,'0')}</span><div><span className={'mt-state '+c.state}>{c.state==='proposed'?'Needs review':c.state==='reviewed'?'Reviewed':'Dismissed'}</span><h3>{c.title}</h3><p className="mt-action-owner">{c.owner_text||'Owner unconfirmed'} <span>· {c.due_on?day(c.due_on):'Due date unconfirmed'}</span></p></div>{detail.canReview&&<button onClick={()=>{if(mayNavigate())setEditing(c);}}>Review</button>}</div>{!!c.flags.length&&<div className="mt-flags">{c.flags.map(f=><span key={f}>{f}</span>)}</div>}{c.review_note&&<p className="mt-review-note">Review note: {c.review_note}</p>}<details><summary>Source wording</summary><blockquote>{c.source_quote}</blockquote></details>{editing?.id===c.id&&<ReviewForm key={c.id+':'+c.version} candidate={c} userId={index.userId} onDenied={clear} onClose={()=>setEditing(null)} onSaved={async()=>{setEditing(null);await load();await open(detail.meeting.id);}}/>}</article>)}{!candidates.length&&<p className="mt-muted">No actions in this view. The original notes remain available.</p>}</>:<div className="mt-notes"><div className="mt-section-heading"><label>Source revision<select value={detail.revision} onChange={e=>{if(mayNavigate())void open(detail.meeting.id,Number(e.target.value));}}>{detail.versions.map(v=><option key={v.revision} value={v.revision}>Revision {v.revision} · {new Date(v.imported_at).toLocaleDateString('en-AU')}</option>)}</select></label><button onClick={async()=>{const actor=identity.current,seq=detailSeq.current;try{const fresh=await request<MeetingDetail>('/'+detail.meeting.id+'?revision='+detail.revision);if(actor===identity.current&&seq===detailSeq.current)downloadBlob('MineralX-meeting-'+fresh.meeting.held_on+'.txt',fresh.source.source_text,'text/plain');}catch(e){if(actor===identity.current&&seq===detailSeq.current)fail(e);}}}>Download notes</button></div><p className="mt-muted">Original imported text. Automated meeting notes can contain errors. Corrections remain separate from this source.</p><pre>{detail.source.source_text}</pre><details><summary>Source integrity</summary><code>SHA-256 {detail.source.source_hash}</code></details></div>}
 </>}{!opening&&!detail&&index.meetings.length===0&&<div className="mt-empty"><h2>Your meeting archive</h2><p>Imported notes and their action lists will appear here.</p></div>}</section></div>}</>}
 </main></div>;
}
