'use client';
import { useState } from 'react';
import { effectiveOn, isLayerOn, layerOpacityOf, projectLayerDescriptors, WMS_LAYERS_BY_THEME } from './layer-registry.js';
import { THEME_ORDER, THEME_LABELS } from './layer-data.js';
import { elementInfo } from './project-store.js';
import { boundaryData, spatialStats } from './spatial-import.js';
import './spatial-layers.css';

export default function MapLayersPanel({ store, layerIndex, layerOn, toggleLayerOn, layerOpacity, setLayerOpacity, isExpanded, setExpanded, wmsErrors, basemap, setBasemap, activeElement, setActiveElement, availableElements, flowState, onRerunFlow, onManage, onClose, api, preferencesSaved, spatialError, locked, removePublicLayer }) {
  const [query, setQuery] = useState(''), [catalogue, setCatalogue] = useState(false), [message, setMessage] = useState('');
  const project = store.projects.find(p => p.id === store.activeProjectId) || store.projects[0];
  const matches = value => !query || String(value).toLowerCase().includes(query.toLowerCase());
  const action = async fn => { try { await fn(); setMessage('Saved on this device.'); } catch (error) { setMessage(`Not saved: ${error.message}`); } };
  const expansion = row => ({ expanded: isExpanded(row.id, false), onExpanded: expanded => setExpanded(prev => prev[row.id] === expanded ? prev : { ...prev, [row.id]: expanded }) });
  const opacity = (id, value) => setLayerOpacity(current => ({ ...current, [id]: value }));
  const projectRows = p => {
    const counts = { chips: p.samples.filter(s => !s.archivedAt && !s.holeId && !['blank', 'standard', 'crm'].includes(s.qaqcType)).length + (p.observations || []).length, holes: p.collars.filter(c => !c.archivedAt).length, targets: (p.targets || []).length, bnd: p.boundary ? spatialStats(boundaryData(p.boundary)).polygons : 0 };
    return projectLayerDescriptors(p).filter(row => counts[row.id.split(':')[0]] > 0 && matches(row.id.startsWith('chips:') ? 'Samples observations' : row.id.startsWith('bnd:') ? 'Tenement boundary' : row.label)).map(row => <LayerRow key={row.id} {...expansion(row)} row={{ ...row, label: row.id.startsWith('chips:') ? 'Samples & observations' : row.id.startsWith('bnd:') ? 'Tenement boundary' : row.label }} count={counts[row.id.split(':')[0]]} layerOn={layerOn} layerIndex={layerIndex} onToggle={() => toggleLayerOn(row.id)} onZoom={() => api.fitProjectLayer(p.id, row.id)}>
      {row.manage && <button type="button" onClick={() => onManage({ type: row.manage, projectId: p.id })}>Manage records</button>}
      {row.id.startsWith('bnd:') && <><button type="button" onClick={() => api.exportBoundary(p.id)}>Export boundary KML</button><button type="button" disabled={locked} onClick={() => api.openSpatialImport(p.id, [], 'boundary')}>Add / replace tenements</button><p>{p.boundary.name} · all exterior and interior rings retained</p></>}
    </LayerRow>);
  };
  const imported = p => (p.spatialLayers || []).filter(l => !l.archivedAt && matches(`${l.name} ${l.source?.name}`)).map(l => {
    const row = layerIndex.get(`spatial:${p.id}:${l.recordId}`);
    return <LayerRow key={l.recordId} {...expansion(row)} row={row} count={l.data.features.length} layerOn={layerOn} layerIndex={layerIndex} onToggle={() => toggleLayerOn(row.id)} onZoom={() => api.fitSpatial(l.data)} opacity={layerOpacityOf(layerOpacity, layerIndex, row.id)} onOpacity={v => opacity(row.id, v)}>
      <p>{l.source.format.toUpperCase()} · {l.stats.points} points · {l.stats.lines} lines · {l.stats.polygons} polygons</p>
      <p>Source: {l.source.name} · imported {l.importedAt.slice(0, 10)} · WGS84</p>
      {(p.boundary?.sourceLayerIds || []).includes(l.recordId) && <p>Used in the separate tenement boundary outline above. Hiding this reference layer does not remove that boundary.</p>}
      <label>Layer name<input defaultValue={l.name} disabled={locked} onBlur={e => { const name = e.target.value.trim(); if (name && name !== l.name) action(() => api.updateSpatial(p.id, l.recordId, { name })); }} /></label>
      <button type="button" onClick={() => api.exportSpatial(p.id, l.recordId, 'original')}>Export original {l.source.format.toUpperCase()}</button><button type="button" onClick={() => api.exportSpatial(p.id, l.recordId, 'geojson')}>Export GeoJSON</button><button type="button" onClick={() => api.exportSpatial(p.id, l.recordId, 'kml')}>Export vector KML</button>
      <button type="button" disabled={locked || (p.boundary?.sourceLayerIds || []).includes(l.recordId)} onClick={() => { if (window.confirm(`Archive ${l.name}? Source and features stay in backups and can be restored.`)) action(() => api.updateSpatial(p.id, l.recordId, { archivedAt: new Date().toISOString() })); }}>Archive layer</button>
      <details><summary>Inspect features and attributes</summary><div className="mx-spatial-features">{l.data.features.map((f, i) => <details key={i}><summary>{String(f.properties?.name || f.id || `Feature ${i + 1}`)} · {f.geometry.type}</summary><pre>{JSON.stringify(f.properties, null, 2)}</pre></details>)}</div></details>
    </LayerRow>;
  });
  const publicRows = Array.from(layerIndex.values()).filter(row => row.group === 'pub' && row.engine);
  const selectedPublic = publicRows.filter(row => Object.hasOwn(layerOn, row.id) || isLayerOn(layerOn, layerIndex, row.id));
  const referenceRow = row => <LayerRow key={row.id} {...expansion(row)} row={row} layerOn={layerOn} layerIndex={layerIndex} onToggle={() => toggleLayerOn(row.id)} opacity={row.supportsOpacity ? layerOpacityOf(layerOpacity, layerIndex, row.id) : undefined} onOpacity={row.supportsOpacity ? v => opacity(row.id, v) : undefined} error={wmsErrors[row.id]}><p>{row.wms?.attribution || 'Published reference data from the last target-analysis run.'}</p>{Object.hasOwn(layerOn,row.id) && <button type="button" onClick={()=>removePublicLayer(row.id)}>Remove from working layers</button>}{wmsErrors[row.id] && <p>Turn the layer off and on to retry. Availability depends on the external provider.</p>}</LayerRow>;
  return <section className="mx-glass-panel mx-layers-clean mx-anim-rise" aria-label="Map layers">
    <header className="mx-panel-header"><div><h2>Map layers</h2><p>{project?.name || 'Choose a project'}</p></div><button type="button" className="mx-close-btn" aria-label="Close map layers" onClick={onClose}>×</button></header>
    <div className="mx-layers-tools"><button type="button" className="mx-btn-primary" disabled={!project || locked} onClick={() => api.openSpatialImport(project.id)}>Import map files</button><label>Find a layer<input type="search" placeholder="Search project layers or public catalogue" value={query} onChange={e => setQuery(e.target.value)} /></label></div>
    <div className="mx-layers-body">
      {project && <section aria-label="Active project layers"><h3>Project data</h3><label className="mx-spatial-check"><input type="checkbox" checked={isLayerOn(layerOn, layerIndex, `proj:${project.id}`)} onChange={() => toggleLayerOn(`proj:${project.id}`)} />Show this project</label>{projectRows(project)}{!project.boundary && <button type="button" disabled={locked} onClick={() => api.openSpatialImport(project.id, [], 'boundary')}>+ Import tenement boundary</button>}<h3>Imported reference files</h3>{imported(project)}{!(project.spatialLayers || []).some(l => !l.archivedAt) && <p className="mx-spatial-muted">No imported reference layers. Add geology, faults, traverses or tenement files without changing collected records.</p>}
        {(project.spatialLayers || []).some(l => l.archivedAt) && <details><summary>Archived sources</summary>{project.spatialLayers.filter(l => l.archivedAt).map(l => <div className="mx-spatial-actions" key={l.recordId}><span>{l.name}</span><button type="button" disabled={locked} onClick={() => action(() => api.updateSpatial(project.id, l.recordId, { archivedAt: null }))}>Restore layer</button><button type="button" onClick={() => api.exportSpatial(project.id, l.recordId, 'original')}>Export original</button></div>)}</details>}
      </section>}
      <section aria-label="Public reference layers"><h3>Public reference layers</h3>{selectedPublic.length > 0 && <label className="mx-spatial-check"><input type="checkbox" checked={isLayerOn(layerOn,layerIndex,'pub')} onChange={()=>toggleLayerOn('pub')} />Show public overlays</label>}{selectedPublic.filter(row => matches(row.label)).map(referenceRow)}{!selectedPublic.length && <p className="mx-spatial-muted">No public overlays selected. The catalogue stays out of your working layer stack.</p>}<button type="button" aria-expanded={catalogue} onClick={() => setCatalogue(value => !value)}>{catalogue ? 'Close reference catalogue' : 'Add reference layers'}</button>
        {(catalogue || query) && <div className="mx-layer-catalogue">{!selectedPublic.length && <label className="mx-spatial-check"><input type="checkbox" checked={isLayerOn(layerOn, layerIndex, 'pub')} onChange={() => toggleLayerOn('pub')} />Show public overlays</label>}{THEME_ORDER.map(theme => { const rows = (WMS_LAYERS_BY_THEME.get(theme) || []).filter(row => matches(`${row.label} ${THEME_LABELS[theme]}`)); return rows.length ? <details key={theme} open={!!query || isExpanded(`catalogue:${theme}`, false)} onToggle={e => { const expanded = e.currentTarget.open; setExpanded(prev => prev[`catalogue:${theme}`] === expanded ? prev : { ...prev, [`catalogue:${theme}`]: expanded }); }}><summary>{THEME_LABELS[theme]} · {rows.length}</summary>{rows.map(referenceRow)}</details> : null; })}</div>}
      </section>
      <details className="mx-layer-analysis"><summary>Analysis overlays</summary><p>Computed terrain suggestions are not mapped geology. Layers use the last run; toggling them does not rerun analysis.</p><button type="button" disabled={flowState.status === 'running'} onClick={onRerunFlow}>{flowState.status === 'running' ? 'Analysing…' : 'Run analysis for this view'}</button>{flowState.status !== 'idle' && <><p>{flowState.status}{flowState.error ? `: ${flowState.error}` : ''}</p>{['flow', 'flow:hydraulics', 'drainage', 'heatmap', 'targets', 'correlated'].map(id => { const row = layerIndex.get(id); return <LayerRow key={id} {...expansion(row)} row={row} layerOn={layerOn} layerIndex={layerIndex} onToggle={() => toggleLayerOn(id)} opacity={row.supportsOpacity ? layerOpacityOf(layerOpacity, layerIndex, id) : undefined} onOpacity={row.supportsOpacity ? v => opacity(id, v) : undefined} />; })}{publicRows.filter(row => row.engine === 'vector-query').map(referenceRow)}</>}</details>
      {store.projects.length > 1 && <details><summary>Other projects · {store.projects.length - 1}</summary><p>Visibility is independent of the active project. Nothing is moved between projects.</p>{store.projects.filter(p => p.id !== project?.id).map(p => <details key={p.id}><summary>{p.name}</summary><label className="mx-spatial-check"><input type="checkbox" checked={isLayerOn(layerOn, layerIndex, `proj:${p.id}`)} onChange={() => toggleLayerOn(`proj:${p.id}`)} />Show {p.name}</label>{projectRows(p)}{imported(p)}</details>)}</details>}
      <details><summary>Map appearance</summary><label>Colour samples by<select value={activeElement} onChange={e => setActiveElement(e.target.value)}>{availableElements.map(element => <option key={element}>{element}</option>)}</select></label><p>{activeElement}: anomaly ≥ {elementInfo(activeElement).anom}; high ≥ {elementInfo(activeElement).high} {elementInfo(activeElement).unit}. Pending, unreviewed and indeterminate results are distinct.</p><label>Basemap<select value={basemap} onChange={e => setBasemap(e.target.value)}><option value="satellite">Satellite</option><option value="topo">Topographic</option></select></label></details>
      {spatialError && <p role="alert" className="mx-spatial-error">{spatialError}</p>}{message && <p role="status">{message}</p>}
    </div><footer className="mx-spatial-footer"><small role={preferencesSaved ? 'status' : 'alert'}>{preferencesSaved ? 'Layer visibility, opacity and basemap saved on this device.' : 'Layer preferences could not be saved. Keep this tab open; export a workspace backup.'}</small></footer>
  </section>;
}
function LayerRow({ row, count, layerOn, layerIndex, onToggle, onZoom, opacity, onOpacity, error, children, expanded, onExpanded }) {
  const on = isLayerOn(layerOn, layerIndex, row.id), shown = effectiveOn(layerOn, layerIndex, row.id);
  return <div className="mx-layer-item" data-layer-id={row.id}>
    <div className="mx-layer-line"><label><input type="checkbox" aria-label={`Show ${row.label}`} checked={on} onChange={onToggle} /><span>{row.label}</span>{count != null && <small>{count}</small>}</label>{onZoom && <button type="button" aria-label={`Zoom to ${row.label}`} onClick={onZoom}>Zoom</button>}</div>
    {on && !shown && <small className="mx-spatial-muted">Hidden by parent group</small>}{error && <small role="status" className="mx-spatial-error">Provider unavailable</small>}
    {(children || onOpacity) && <details open={expanded} onToggle={e => onExpanded?.(e.currentTarget.open)}><summary>Layer details</summary>{onOpacity && <label>Opacity · {Math.round(opacity * 100)}%<input type="range" aria-label={`${row.label} opacity`} min="0" max="100" value={Math.round(opacity * 100)} onChange={e => onOpacity(Number(e.target.value) / 100)} /></label>}{children}</details>}
  </div>;
}
