'use client';
import {useEffect,useState} from 'react';import Link from 'next/link';import {authClient,api,downloadBlob} from '@/lib/ops/client';import {Message,Heading} from './primitives';import {useOperations} from './OperationsProvider';
export default function Account(){const {context,refresh,exportVault,pack}=useOperations();const[user,setUser]=useState<any>(null),[factors,setFactors]=useState<any[]>([]),[enrolled,setEnrolled]=useState<any>(null),[code,setCode]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const load=async()=>{try{const db=authClient();const{data,error}=await db.auth.getUser();if(error)throw new Error('Sign in before managing your account.');setUser(data.user);const f=await db.auth.mfa.listFactors();if(f.error)throw f.error;setFactors(f.data.totp||[]);}catch(e){setError((e as Error).message);}};
 useEffect(()=>{load();},[]);
 const perform=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <><Heading title="Your account" description="Named access, authenticator verification and device recovery."/>{error&&<Message error>{error}</Message>}{message&&<Message>{message}</Message>}{!user?<section className="ops-card"><Link href="/ops/login">Sign in with your invited account</Link></section>:<>
 <section className="ops-card"><h2>{user.email}</h2><p className="ops-account-id">Account {user.id}</p><p>Authenticator: {context?.aal==='aal2'?'verified for this session':'verification required for accountable actions'}</p><button disabled={busy} onClick={()=>perform(async()=>{const r=await api('claim',{});await refresh();setMessage(`${r.accepted} pending workspace invitations accepted.`);})}>Check assigned invitations</button></section>
 <section className="ops-card"><h2>Authenticator</h2><p>Required for analytical release, gold movements, period close and access changes. This does not change your assigned responsibilities.</p>
 {enrolled&&<><p>Scan with your authenticator, then enter its six-digit code.</p><img src={enrolled.totp.qr_code} alt="New authenticator enrolment QR code"/><details><summary>Manual setup key</summary><code>{enrolled.totp.secret}</code></details></>}
 {!enrolled&&!factors.some(f=>f.status==='verified')&&<button disabled={busy} onClick={()=>perform(async()=>{const{data,error}=await authClient().auth.mfa.enroll({factorType:'totp',friendlyName:'MineralX staff authenticator'});if(error)throw error;setEnrolled(data);})}>Set up authenticator</button>}
 {(enrolled||factors.some(f=>f.status==='verified'))&&<form className="ops-actions" onSubmit={e=>{e.preventDefault();perform(async()=>{const id=enrolled?.id||factors.find(f=>f.status==='verified')?.id;const{error}=await authClient().auth.mfa.challengeAndVerify({factorId:id,code:code.trim()});if(error)throw new Error('Authenticator code was not accepted. Nothing was approved.');setCode('');setEnrolled(null);await load();await refresh();setMessage('Authenticator verified. Return to the retained work entry and check access again before submitting.');});}}><label>Six-digit code<input aria-label="Authenticator code" inputMode="numeric" pattern="[0-9]{6}" autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value)} required/></label><button className="ops-primary" disabled={busy}>Verify authenticator</button></form>}
 </section><section className="ops-card"><h2>Password</h2><form onSubmit={e=>{e.preventDefault();perform(async()=>{const{error}=await authClient().auth.updateUser({password});if(error)throw error;setPassword('');setMessage('Password updated.');});}}><label>New password<input type="password" autoComplete="new-password" minLength={12} required value={password} onChange={e=>setPassword(e.target.value)}/></label><div className="ops-actions"><button disabled={busy}>Update password</button></div></form></section>
 <section className="ops-card"><h2>Sign out safely</h2><p>Encrypted field work stays on this device under its existing account. The passphrase is required to unlock it; it is not uploaded with your work.</p>{pack&&<p>{pack.outbox.length} changes are still awaiting acknowledgement.</p>}<div className="ops-actions"><button disabled={busy} onClick={()=>perform(async()=>{const recovery=await exportVault();if(recovery)downloadBlob('MineralX-encrypted-field-recovery.json',JSON.stringify(recovery));else setMessage('No unlocked device workspace to export.');})}>Export encrypted recovery</button><button disabled={busy} onClick={()=>perform(async()=>{if(pack?.outbox.length&&!confirm(`Sign out with ${pack.outbox.length} unsynchronised changes? They remain encrypted on this device, not in the company database.`))return;const{error}=await authClient().auth.signOut();if(error)throw error;location.assign('/ops/login');})}>Sign out</button></div></section></>}
 </>;
}
