'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {api,authClient,downloadBlob} from '@/lib/ops/client';
import {useOperations} from './OperationsProvider';
import {Heading,Message} from './primitives';
export {default as Login} from './Login';
export function Account(){
 const {context,refresh,pack,exportVault}=useOperations(),router=useRouter();const [factor,setFactor]=useState(''),[qr,setQr]=useState(''),[secret,setSecret]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <><Heading title="Your account" description="Named access and independent review protect the records behind each decision."/>{error&&<Message error>{error}</Message>}{message&&<Message>{message}</Message>}
 <section className="ops-card"><h2>Authenticator verification</h2><p>{context?.aal==='aal2'?'Your second factor is verified for this session.':'Verify a second factor for gold custody, analytical approval, period close and access administration.'}</p>{!factor?<button disabled={busy} onClick={()=>run(async()=>{const db=authClient(),{data,error}=await db.auth.mfa.listFactors();if(error)throw error;const verified=data.totp.find(f=>f.status==='verified');if(verified){setFactor(verified.id);return;}const {data:enrolled,error:issue}=await db.auth.mfa.enroll({factorType:'totp',friendlyName:'MineralX '+new Date().toISOString()});if(issue)throw issue;setFactor(enrolled.id);setQr(enrolled.totp.qr_code);setSecret(enrolled.totp.secret);})}>Set up or verify authenticator</button>:<form onSubmit={e=>{e.preventDefault();run(async()=>{const {error}=await authClient().auth.mfa.challengeAndVerify({factorId:factor,code});if(error)throw new Error('The code could not be verified. Try the current code from your authenticator.');setQr('');setSecret('');setCode('');setFactor('');await refresh();setMessage('Account verified. You can return to your review.');});}}>{qr&&<><p>Scan with your authenticator app.</p>{/* eslint-disable-next-line @next/next/no-img-element */}<img width={200} height={200} alt="Authenticator setup QR" src={qr.startsWith('data:image/')?qr:`data:image/svg+xml;charset=utf-8,${encodeURIComponent(qr)}`}/><details><summary>Manual setup key</summary><code>{secret}</code></details></>}<label>Current six-digit code<input autoComplete="one-time-code" inputMode="numeric" pattern="[0-9]{6}" required value={code} onChange={e=>setCode(e.target.value)} maxLength={6}/></label><button disabled={busy} className="ops-primary">Verify account</button></form>}</section>
 <section className="ops-card"><h2>Set a new password</h2><form onSubmit={e=>{e.preventDefault();const form=e.currentTarget,data=new FormData(form);run(async()=>{const password=String(data.get('password'));if(password!==data.get('confirm'))throw new Error('Passwords do not match.');const {error}=await authClient().auth.updateUser({password});if(error)throw error;form.reset();setMessage('Password updated.');});}}><div className="ops-form-grid"><label>New password<input type="password" name="password" autoComplete="new-password" minLength={12} required/></label><label>Repeat new password<input type="password" name="confirm" autoComplete="new-password" minLength={12} required/></label></div><button disabled={busy}>Update password</button></form></section>
 <section className="ops-card"><h2>Session & access</h2><p>{context?`Account ${context.userId}`:'Sign in to manage your account.'}</p><div className="ops-actions"><button disabled={busy} onClick={()=>run(async()=>{const result=await api('claim',{});await refresh();setMessage(`Invitation claims checked. ${result.accepted??0} newly assigned workspaces.`);})}>Check assigned invitations</button>{pack&&<button onClick={()=>run(async()=>{const file=await exportVault();if(file)downloadBlob('MineralX-encrypted-field-recovery.json',JSON.stringify(file));})}>Save encrypted recovery copy</button>}<button disabled={busy} onClick={()=>run(async()=>{if(pack?.outbox.length&&!confirm(`${pack.outbox.length} changes are saved only on this device. Sign out and lock them? Keep your passphrase and recovery copy.`))return;const {error}=await authClient().auth.signOut({scope:'local'});if(error)throw error;await refresh();router.replace('/ops/login');})}>Sign out of this device</button></div></section></>;
}
