'use client';
import {useState} from 'react';
import Link from 'next/link';
import {useSearchParams,useRouter} from 'next/navigation';
import {api,authClient,downloadBlob} from '@/lib/ops/client';
import {safeOpsPath} from '@/lib/ops/contracts';
import {useOperations} from './OperationsProvider';
import {Heading,Message} from './primitives';
export function Login(){
 const {refresh}=useOperations(),router=useRouter(),query=useSearchParams();const [mode,setMode]=useState('signin'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const configured=Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL&&(process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY));
 return <main className="ops-login" id="main-content"><Link href="/ops" className="ops-brand">MINERAL<span>X</span><small>OPERATIONS</small></Link><h1>{mode==='signin'?'Your work starts here.':'Reset your password'}</h1><p>Use your named MineralX account. Workspace access follows your assigned responsibilities.</p>{!configured&&<Message>Staff sign-in is awaiting identity service configuration.</Message>}{query.get('expired')&&<Message error>This sign-in link could not be verified. Request a new link.</Message>}{error&&<Message error>{error}</Message>}{message&&<Message>{message}</Message>}
 <form onSubmit={async e=>{e.preventDefault();const data=new FormData(e.currentTarget);setBusy(true);setError('');try{const db=authClient(),email=String(data.get('email'));if(mode==='reset'){const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/ops/auth/complete?next=/ops/account'});if(error)throw error;setMessage('If this address has an account, a reset link will be sent.');}else{const {error}=await db.auth.signInWithPassword({email,password:String(data.get('password'))});if(error)throw new Error('Sign-in failed. Check your email and password.');await api('claim',{});await refresh();router.replace(safeOpsPath(query.get('next')||'/ops'));}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
 <label>Email<input type="email" name="email" autoComplete="username" required disabled={busy||!configured}/></label>{mode==='signin'&&<label>Password<input type="password" name="password" autoComplete="current-password" required disabled={busy||!configured}/></label>}<button className="ops-primary" disabled={busy||!configured}>{busy?'Please wait…':mode==='signin'?'Sign in':'Send reset link'}</button></form><button className="ops-link" onClick={()=>{setMode(mode==='signin'?'reset':'signin');setMessage('');setError('');}}>{mode==='signin'?'Forgot password?':'Return to sign in'}</button><Link href="/ops/field">Unlock prepared field records</Link></main>;
}
export function Account(){
 const {context,refresh,pack,exportVault}=useOperations(),router=useRouter();const [factor,setFactor]=useState(''),[qr,setQr]=useState(''),[secret,setSecret]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <><Heading title="Your account" description="Named access and independent review protect the records behind each decision."/>{error&&<Message error>{error}</Message>}{message&&<Message>{message}</Message>}
 <section className="ops-card"><h2>Authenticator verification</h2><p>{context?.aal==='aal2'?'Your second factor is verified for this session.':'Verify a second factor for gold custody, analytical approval, period close and access administration.'}</p>{!factor?<button disabled={busy} onClick={()=>run(async()=>{const db=authClient(),{data,error}=await db.auth.mfa.listFactors();if(error)throw error;const verified=data.totp.find(f=>f.status==='verified');if(verified){setFactor(verified.id);return;}const {data:enrolled,error:issue}=await db.auth.mfa.enroll({factorType:'totp',friendlyName:'MineralX '+new Date().toISOString()});if(issue)throw issue;setFactor(enrolled.id);setQr(enrolled.totp.qr_code);setSecret(enrolled.totp.secret);})}>Set up or verify authenticator</button>:<form onSubmit={e=>{e.preventDefault();run(async()=>{const {error}=await authClient().auth.mfa.challengeAndVerify({factorId:factor,code});if(error)throw new Error('The code could not be verified. Try the current code from your authenticator.');setQr('');setSecret('');setCode('');setFactor('');await refresh();setMessage('Account verified. You can return to your review.');});}}>{qr&&<><p>Scan with your authenticator app.</p>{/* eslint-disable-next-line @next/next/no-img-element */}<img width={200} height={200} alt="Authenticator setup QR" src={qr.startsWith('data:image/')?qr:`data:image/svg+xml;charset=utf-8,${encodeURIComponent(qr)}`}/><details><summary>Manual setup key</summary><code>{secret}</code></details></>}<label>Current six-digit code<input autoComplete="one-time-code" inputMode="numeric" pattern="[0-9]{6}" required value={code} onChange={e=>setCode(e.target.value)} maxLength={6}/></label><button disabled={busy} className="ops-primary">Verify account</button></form>}</section>
 <section className="ops-card"><h2>Set a new password</h2><form onSubmit={e=>{e.preventDefault();const form=e.currentTarget,data=new FormData(form);run(async()=>{const password=String(data.get('password'));if(password!==data.get('confirm'))throw new Error('Passwords do not match.');const {error}=await authClient().auth.updateUser({password});if(error)throw error;form.reset();setMessage('Password updated.');});}}><div className="ops-form-grid"><label>New password<input type="password" name="password" autoComplete="new-password" minLength={12} required/></label><label>Repeat new password<input type="password" name="confirm" autoComplete="new-password" minLength={12} required/></label></div><button disabled={busy}>Update password</button></form></section>
 <section className="ops-card"><h2>Session & access</h2><p>{context?`Account ${context.userId}`:'Sign in to manage your account.'}</p><div className="ops-actions"><button disabled={busy} onClick={()=>run(async()=>{const result=await api('claim',{});await refresh();setMessage(`Invitation claims checked. ${result.accepted??0} newly assigned workspaces.`);})}>Check assigned invitations</button>{pack&&<button onClick={()=>run(async()=>{const file=await exportVault();if(file)downloadBlob('MineralX-encrypted-field-recovery.json',JSON.stringify(file));})}>Save encrypted recovery copy</button>}<button disabled={busy} onClick={()=>run(async()=>{if(pack?.outbox.length&&!confirm(`${pack.outbox.length} changes are saved only on this device. Sign out and lock them? Keep your passphrase and recovery copy.`))return;const {error}=await authClient().auth.signOut({scope:'local'});if(error)throw error;await refresh();router.replace('/ops/login');})}>Sign out of this device</button></div></section></>;
}
