'use client';
import {useEntryGuard} from './navigation';
import React,{useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {api,newCommand,uploadEvidence} from '@/lib/ops/client';
import type {Command} from '@/lib/ops/contracts';
import {localDateTime,zonedTimestamp} from '@/lib/ops/time';
import {useOperations} from './OperationsProvider';import {Message} from './primitives';import type {ActionSpec,Field} from './action-specs';
import {scopeLabel} from '@/lib/ops/suite-navigation';

export function EvidencePicker({value,onChange,family='gold',required=false,files=[]}:{value:string;onChange:(id:string)=>void;family?:string;required?:boolean;files?:any[]}){
 const {scope,context,online,offlineMode,development}=useOperations();const [error,setError]=useState(''),[busy,setBusy]=useState(false),[added,setAdded]=useState<any[]>([]);const identity=useRef<{id:string;requestId:string;fingerprint:string}|undefined>();
 const candidates=[...new Map([...files,...added].map(f=>[f.id,f])).values()].filter(f=>f.status==='verified'&&(f.family===family||f.family==='plant'&&family==='gold'));
 return <div className="ops-evidence"><select required={required} value={value||''} onChange={e=>onChange(e.target.value)} aria-label="Verified source evidence"><option value="">{required?'Choose verified source':'Not yet attached'}</option>{candidates.map(f=><option key={f.id} value={f.id}>{f.name} · {f.sha256?.slice(0,8)}</option>)}</select><label className="ops-file-button">{busy?'Uploading and verifying…':'Attach original file'}<input type="file" disabled={busy||(!development&&(!online||offlineMode))||!context?.capabilities.evidence} onChange={async e=>{const file=e.target.files?.[0];if(!file||!scope)return;if(!file.size||file.size>10485760){setError('Choose a non-empty file up to 10 MiB.');return;}const bytes=await file.arrayBuffer();const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),x=>x.toString(16).padStart(2,'0')).join('');const fingerprint=`${scope.id}:${family}:${file.name}:${digest}`;if(identity.current?.fingerprint!==fingerprint)identity.current={id:crypto.randomUUID(),requestId:crypto.randomUUID(),fingerprint};setBusy(true);setError('');try{const f=await uploadEvidence(scope.id,family,file,identity.current);setAdded(a=>[...a,f]);onChange(f.id);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}/></label>{!context?.capabilities.evidence&&<small>Private file service is awaiting activation.</small>}{error&&<Message error>{error} Keep the source file; select it again to retry.</Message>}{value&&<small>{development?'File bytes saved in this browser only; download a development backup.':'Verified primary copy. Independent backup status is shown in Files.'}</small>}</div>;
}
function Fields({fields,values,onChange,resources,zone,prefix='entry'}:{fields:Field[];values:any;onChange:(next:any)=>void;resources:Record<string,any[]>;zone:string;prefix?:string}){
 return <div className="ops-form-grid">{fields.filter(f=>!f.advanced&&(!f.when||f.when(values))).map(f=>{
 const id=`${prefix}-${f.key}`,value=values[f.key]??f.default??'',rows=(resources[f.resource||'']||[]).filter(row=>!f.resourceFilter||f.resourceFilter(row,values));const set=(v:any)=>onChange({...values,[f.key]:v,...Object.fromEntries((f.clearOnChange||[]).map(key=>[key,'']))});
 if(f.type==='repeat')return <fieldset className="ops-wide ops-repeated" key={id}><legend>{f.label}</legend>{(Array.isArray(value)?value:[]).map((row:any,index:number)=><div className="ops-repeat-row" key={index}><Fields fields={f.fields||[]} values={row} onChange={next=>set(value.map((v:any,i:number)=>i===index?next:v))} resources={resources} zone={zone} prefix={`${id}-${index}`}/><button type="button" onClick={()=>set(value.filter((_:any,i:number)=>i!==index))}>Remove row {index+1}</button></div>)}<button type="button" onClick={()=>set([...(Array.isArray(value)?value:[]),{}])}>Add {f.label.toLowerCase()} row</button>{f.hint&&<small>{f.hint}</small>}</fieldset>;
 if(f.type==='multi')return <fieldset className="ops-wide ops-multiselect" key={id}><legend>{f.label}</legend>{rows.map(r=><label key={r.recordId||r.id}><input type="checkbox" checked={Array.isArray(value)&&value.includes(r.recordId||r.id)} onChange={e=>set(e.target.checked?[...(Array.isArray(value)?value:[]),r.recordId||r.id]:(value||[]).filter((v:string)=>v!==(r.recordId||r.id)))}/>{r.reference||r.name||r.id} <small>{r.status||''}</small></label>)}{!rows.length&&<p>No available records. Record the upstream work first.</p>}</fieldset>;
 if(f.type==='evidence')return <fieldset key={id} className="ops-wide"><legend>{f.label}</legend><EvidencePicker value={value} onChange={set} family={f.family} required={f.required} files={resources.files||[]}/></fieldset>;
 return <label key={id} htmlFor={id} className={f.type==='textarea'?'ops-wide':''}><span>{f.label}{f.required&&<span aria-label="required"> *</span>}</span>
 {f.type==='select'?<select id={id} required={f.required} value={value} onChange={e=>set(e.target.value)}><option value="">{f.emptyLabel||'Select…'}</option>{f.options?.map(o=><option value={o} key={o}>{o.replaceAll('_',' ')}</option>)}{rows.map(r=><option key={r.recordId||r.id||r.user_id} value={r.recordId||r.id||r.user_id}>{r.reference||r.name||r.title||r.id}{r.net_g?' · '+r.net_g+' g':''}{r.au_percent?' · '+r.au_percent+'% Au':''}{r.status?' · '+r.status:''}</option>)}</select>:
 f.type==='textarea'?<textarea id={id} rows={3} required={f.required} maxLength={4000} value={value} onChange={e=>set(e.target.value)}/>:
 f.type==='check'?<input id={id} type="checkbox" checked={!!value} onChange={e=>set(e.target.checked)}/>:
 <input id={id} type={f.type==='datetime'?'datetime-local':f.type==='date'?'date':f.type==='number'?'number':'text'} step={f.type==='datetime'?1:f.type==='number'?'any':undefined} inputMode={f.type==='decimal'?'decimal':undefined} required={f.required} maxLength={f.type==='decimal'?24:240} value={f.type==='datetime'&&typeof value==='string'&&/(Z|[+-]\d\d:\d\d)$/.test(value)?localDateTime(value,zone):value} onChange={e=>set(e.target.value)}/>}
 {f.type==='datetime'&&<small>{zone}; actual observation time</small>}{f.hint&&<small>{f.hint}</small>}</label>;
 })}{fields.some(f=>f.advanced&&(!f.when||f.when(values)))&&<details className="ops-wide ops-entry-details"><summary>Additional planning details & evidence</summary><Fields fields={fields.filter(f=>f.advanced).map(f=>({...f,advanced:false}))} values={values} onChange={onChange} resources={resources} zone={zone} prefix={prefix+'-details'}/></details>}</div>;
}
export function serialiseFields(fields:Field[],values:any,zone:string):any{
 const output={...values};for(const f of fields){const v=values[f.key]??f.default;if(values[f.key]===undefined&&f.default!==undefined)output[f.key]=f.default;if(f.when&&!f.when(values)){delete output[f.key];continue;}
 if(f.type==='repeat'){output[f.key]=(v||[]).map((r:any)=>serialiseFields(f.fields||[],r,zone));continue;}
 if(f.type==='datetime'&&v)output[f.key]=/(Z|[+-]\d\d:\d\d)$/.test(v)?v:zonedTimestamp(v,zone);
 if(f.type==='number')output[f.key]=v===''||v==null?null:Number(v);
 if(['select','decimal'].includes(f.type||'')&&(v===''||v==null))output[f.key]=null;
 }
 return output;
}
export default function ActionForm({spec,initial={},recordId,expectedVersion=0,resources={},onComplete,onClose,extra={}}:{spec:ActionSpec;initial?:any;recordId?:string;expectedVersion?:number;resources?:Record<string,any[]>;onComplete?:(result:any)=>void;onClose:()=>void;extra?:any}){
 const {scope,context,development,send,pack,saveDraft}=useOperations(),[values,setValues]=useState<any>(()=>({...spec.defaults,...initial})),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(''),[preview,setPreview]=useState<any>(null),[previewMark,setPreviewMark]=useState(''),[unconfirmed,setUnconfirmed]=useState(false);const request=useRef<Command|null>(null),fingerprint=useRef('');
 useEntryGuard(dirty||unconfirmed,busy);
 const draftKey=`${spec.action}:${recordId||'new'}`;const hasPack=pack?.scope.id===scope?.id;
 useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 useEffect(()=>{if(!dirty||!hasPack)return;const timer=setTimeout(()=>saveDraft(draftKey,{values,command:request.current}).catch(e=>setError(e.message)),600);return()=>clearTimeout(timer);},[dirty,values,draftKey,hasPack,saveDraft]);
 const buildPayload=()=>{const serialised=serialiseFields(spec.fields,values,scope?.timezone||'Australia/Brisbane');return {...(spec.prepare?spec.prepare(serialised,resources):serialised),...extra};};
 const currentPreviewMark=JSON.stringify({values,extra,recordId,expectedVersion});
 const previewEntry=async()=>{if(!scope||!context)return;setBusy(true);setError('');try{const payload=buildPayload();const result=await api('geology',{...newCommand(scope.id,spec.action,payload,recordId,expectedVersion),expectedActorId:context.userId});setPreview(result);setPreviewMark(currentPreviewMark);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const can=!!scope?.permissions.includes(spec.permission),needsMfa=spec.mfa&&context?.aal!=='aal2';
 const close=()=>{if(busy)return;if(dirty&&!window.confirm('Leave the open entry? Any encrypted device draft is retained, but it has not been submitted.'))return;onClose();};
 return <section className="ops-card ops-editor" aria-label={spec.title}><div className="ops-editor-heading"><div><h2>{spec.title}</h2><p>{spec.description}</p></div><button type="button" onClick={close} disabled={busy}>Close</button></div><p className="ops-context-line">{scopeLabel(scope, development)} · {recordId?`record revision ${expectedVersion}`:'new record'} · {context?.capabilities.development?'development browser, not a named staff sign-off':'named account'}</p>{!can&&<Message error>This action is not assigned to your account.</Message>}{needsMfa&&<Message error>{context?.capabilities.development?<>This sign-off requires a named staff account. Development mode cannot approve production or sign custody. <a href="/ops/login">Open staff sign-in</a></>:<>Verify your authenticator in <Link href={`/ops/account?scope=${scope?.id}`}>Account</Link> before committing this action. The draft stays here.</>}</Message>}{error&&<Message error>{error}</Message>}{saved&&<Message>{saved}</Message>}
 {Boolean(pack?.drafts[draftKey])&&<button type="button" onClick={()=>{const draft:any=pack?.drafts[draftKey];setValues(draft.values||draft);request.current=draft.command||null;if(draft.command){fingerprint.current=JSON.stringify({payload:draft.command.payload,id:recordId,version:expectedVersion,actor:context?.userId});setUnconfirmed(true);}setDirty(true);}}>Restore saved device draft</button>}
 <form onSubmit={async e=>{e.preventDefault();if(!scope||!context||!can)return;setBusy(true);setError('');setSaved('');try{
  if(spec.preview&&!unconfirmed&&previewMark!==currentPreviewMark)throw new Error('Preview the current source and destination before committing.');const full=unconfirmed&&request.current?request.current.payload:buildPayload();
  if(spec.action==='transformation.record')full.outputs=full.outputs.map((o:any,i:number)=>({...o,id:request.current?.payload.outputs&&(request.current.payload.outputs as any[])[i]?.id||crypto.randomUUID()}));
  if(spec.action==='gold.transfer'&&!full.transfer_id)full.transfer_id=request.current?.payload.transfer_id||crypto.randomUUID();
  const mark=JSON.stringify({payload:full,id:recordId,version:expectedVersion,actor:context.userId});if(!request.current||fingerprint.current!==mark){request.current={...newCommand(scope.id,spec.action,full,recordId,expectedVersion),expectedActorId:context.userId};fingerprint.current=mark;}
  if(hasPack)await saveDraft(draftKey,{values,command:request.current});const result=await send(request.current);setUnconfirmed(false);setDirty(false);try{await saveDraft(draftKey,null);}catch{setError('The record was committed, but this device draft could not be cleared. The same request is safe to retry.');}setSaved(result.developmentOnly?'Saved in this browser — development only; not queued for production.':result.localOnly?'Saved on this device; waiting for authorised synchronisation.':'Committed to MineralX.');onComplete?.(result);
 }catch(e){if((e as any).code==='unavailable')setUnconfirmed(true);setError((e as Error).message);}finally{setBusy(false);}}}>
 {unconfirmed&&<Message>Save acknowledgement was not received. Retry this exact entry to recover the result safely. Editing is locked until the result is confirmed.</Message>}
 <fieldset disabled={busy||unconfirmed} className="ops-form-fields"><Fields fields={spec.fields} values={values} onChange={next=>{setValues(next);setDirty(true);}} resources={resources} zone={scope?.timezone||'Australia/Brisbane'}/></fieldset>
 {spec.action==='geo.sample.capture'&&!unconfirmed&&<button type="button" onClick={()=>{if(!navigator.geolocation){setError('GPS is unavailable on this device. Enter confirmed coordinates.');return;}navigator.geolocation.getCurrentPosition(pos=>{setValues((v:any)=>({...v,lat:pos.coords.latitude,lng:pos.coords.longitude,coordinateAccuracyM:pos.coords.accuracy,coordSource:'gps'}));setDirty(true);},()=>setError('GPS could not be captured. Check device permission or enter confirmed coordinates.'),{enableHighAccuracy:true,timeout:15000,maximumAge:0});}}>Capture current GPS location</button>}
 {spec.preview&&<section className="ops-preview"><button type="button" disabled={busy||needsMfa} onClick={previewEntry}>Preview source & changes</button>{preview&&<><p>{previewMark===currentPreviewMark?'Current source preview':'Entry changed — preview again before committing'}</p><ul>{preview.summary?.filter((x:any)=>x.changed>0).map((x:any)=><li key={x.kind}>{x.kind}: {x.existing} existing → {x.after} after import ({x.changed} changed)</li>)}</ul>{preview.warnings?.map((w:string,i:number)=><Message key={i}>{w}</Message>)}{preview.project?.stats&&<pre>{JSON.stringify(preview.project.stats,null,2)}</pre>}</>}</section>}
 <div className="ops-form-footer"><button type="submit" className="ops-primary" disabled={busy||!can||needsMfa||Boolean(spec.preview&&!unconfirmed&&previewMark!==currentPreviewMark)}>{busy?'Confirming save…':unconfirmed?'Retry original save':spec.button}</button><span>{dirty?'Draft — not yet submitted':'No unsubmitted changes'}</span></div></form></section>;
}
