// Internal presentation contracts, not an end-user workflow builder. Database commands
// remain the authority for permissions, transitions and quantities.
export type Field={advanced?:boolean;key:string;label:string;type?:'text'|'textarea'|'decimal'|'number'|'date'|'datetime'|'select'|'multi'|'check'|'evidence'|'repeat';required?:boolean;options?:string[];resource?:string;family?:string;fields?:Field[];hint?:string;emptyLabel?:string;clearOnChange?:string[];resourceFilter?:(row:any,values:any)=>boolean;when?:(v:any)=>boolean;default?:any};
export type ActionSpec={title:string;action:string;permission:string;description:string;button:string;fields:Field[];mfa?:boolean;preview?:boolean;defaults?:any;prepare?:(v:any,resources:Record<string,any[]>)=>any};
const text=(key:string,label:string,required=true):Field=>({key,label,required}),decimal=(key:string,label:string,required=true):Field=>({key,label,type:'decimal',required}),date=(key:string,label:string,required=true):Field=>({key,label,type:'datetime',required}),select=(key:string,label:string,resource:string,required=true):Field=>({key,label,type:'select',resource,required});
const reason:Field={key:'reason',label:'Reason / review decision',type:'textarea',required:true,hint:'Describe the observation or decision. This is kept with the authenticated record.'};
const source=(family='gold',required=true):Field=>({key:'source_file_id',label:'Source evidence',type:'evidence',family,required});
const runFeeds:Field={key:'feeds',label:'Measured feed',type:'repeat',fields:[select('feed_lot_id','Feed lot','feed'),decimal('quantity_t','Measured tonnes'),{key:'basis',label:'Mass basis',type:'select',options:['dry','wet'],required:true},decimal('moisture_percent','Moisture %',false)]};
const processingProgram=(emptyLabel='No processing program'):Field=>({key:'campaign_id',label:'Processing program (optional)',type:'select',resource:'processingPrograms',required:false,emptyLabel,hint:'Optional. Select the shared processing program only when this record belongs to planned or active processing work.'});
export const actions:Record<string,ActionSpec>={
 feed:{title:'Record feed lot',action:'feed.create',permission:'plant.capture',description:'Identify the actual feed source. A quantity or moisture result that is not measured stays unrecorded.',button:'Record feed lot',fields:[text('reference','Feed / stockpile reference'),text('owner_reference','Material owner / counterparty',false),decimal('quantity_t','Received quantity, t',false),{key:'mass_basis',label:'Mass basis',type:'select',options:['dry','wet'],required:true},decimal('moisture_percent','Moisture %',false),{...source('plant',false)}],defaults:{mass_basis:'dry'}},
 campaign:{title:'Create processing program',action:'campaign.create',permission:'plant.capture',description:'Group related runs in the shared Operations program register. A processing program is optional for individual runs.',button:'Create program',fields:[text('name','Processing program name')]},
 run:{title:'Processing run',action:'run.save',permission:'plant.capture',description:'Save timing, feed and operating observations. Gold output is recorded separately when a clean-up actually occurs.',button:'Save run draft',fields:[processingProgram('Standalone run — no processing program'),date('started_at','Actual start',false),date('ended_at','Actual end',false),decimal('downtime_minutes','Downtime, minutes',false),runFeeds,{key:'notes',label:'Shift notes / handover',type:'textarea'}],defaults:{feeds:[{basis:'dry'}]}},
 submitRun:{title:'Submit run for review',action:'run.submit',permission:'plant.capture',description:'Submit the measured entry to the supervisor. Submitting does not assert gold production.',button:'Submit run',fields:[]},
 reviewRun:{title:'Review run',action:'run.review',permission:'plant.review',description:'Check timing, feed quantity and basis against source evidence. The recorder cannot review their own run.',button:'Review run',fields:[reason]},
 returnRun:{title:'Return run for correction',action:'run.return',permission:'plant.review',description:'Re-open editing with the prior entry retained in history.',button:'Return for correction',fields:[reason]},
 voidRun:{title:'Void duplicate or invalid run',action:'run.void',permission:'plant.review',description:'The original record remains in the audit. A run linked to physical output cannot be voided.',button:'Void run',fields:[reason]},
 cleanup:{title:'Record clean-up / physical gold lot',action:'cleanup.record',permission:'gold.capture',description:'Create the physical lot at the actual clean-up time. It can cover multiple runs. Leave its assay pending until evidence arrives.',button:'Record physical lot',fields:[text('reference','Lot / clean-up reference'),{key:'form',label:'Physical form',type:'select',options:['concentrate','recovered_metal','dore','residue'],required:true},date('produced_at','Actual clean-up time'),processingProgram(),{key:'run_ids',label:'Processing runs covered',type:'multi',resource:'runs',required:true},text('owner_reference','Material owner',false),{key:'notes',label:'Clean-up observations',type:'textarea'}],defaults:{form:'recovered_metal'}},
 weight:{title:'Record weight observation',action:'weight.record',permission:'gold.capture',description:'A new measurement is appended. Gross weight and tare are only used when both were measured.',button:'Record weight',fields:[{key:'basis',label:'Weight basis',type:'select',options:['net','gross_tare'],required:true},{...decimal('net_g','Net product mass, g'),when:v=>v.basis==='net'},{...decimal('gross_g','Gross mass, g'),when:v=>v.basis==='gross_tare'},{...decimal('tare_g','Tare, g'),when:v=>v.basis==='gross_tare'},text('instrument','Scale / instrument reference'),decimal('resolution_g','Scale resolution, g'),date('observed_at','Actual weighing time'),source('gold',false)],defaults:{basis:'net'}},
 assay:{title:'Record product assay',action:'assay.stage',permission:'gold.capture',description:'Preserve the laboratory result as reported. Qualified results cannot establish exact fine gold.',button:'Stage assay for review',fields:[text('laboratory','Laboratory'),text('certificate','Certificate number'),text('certificate_revision','Certificate revision'),text('method','Analytical method'),text('raw_result','Result exactly as reported'),decimal('reported_value','Reported numeric value'),{key:'unit',label:'Reported unit',type:'select',options:['%','g/kg','g/t'],required:true},{key:'qualifier',label:'Qualifier',type:'select',options:['=','<','>'],required:true},source()],defaults:{certificate_revision:'1',unit:'%',qualifier:'='}},
 reviewGold:{title:'Verify gold measurement and assay',action:'gold.review',permission:'gold.review',mfa:true,description:'Independently review the selected weight and exact assay. New measurements do not silently replace accepted figures.',button:'Verify selected evidence',fields:[select('weight_id','Weight observation','weights'),select('assay_id','Product assay','assays'),reason]},
 holdGold:{title:'Hold gold lot',action:'gold.hold',permission:'gold.review',mfa:true,description:'Retain the physical record and flag unresolved evidence for investigation.',button:'Place on hold',fields:[reason]},
 recognise:{title:'Recognise production',action:'gold.recognize',permission:'gold.review',mfa:true,description:'Count this verified lot at the agreed facility recognition point. Ancestor/descendant lots cannot be counted twice.',button:'Recognise verified production',fields:[{...reason,required:false,hint:'A reason is mandatory when amending an already recognised measurement basis.'}]},
 receiveGold:{title:'Record custody receipt',action:'gold.receive',permission:'gold.custody',mfa:true,description:'Record physical possession separately from ownership, purity and production.',button:'Acknowledge physical custody',fields:[text('location','Controlled custody location'),source('custody')]},
 transfer:{title:'Hand over gold lot',action:'gold.transfer',permission:'gold.custody',mfa:true,description:'The currently recorded holder starts the handover. The named recipient must acknowledge receipt separately.',button:'Record dispatch / handover',fields:[select('to_holder','Receiving staff member','people',false),text('external_recipient','External recipient (when no staff recipient)',false),text('destination','Destination / custody location'),text('reference','Handover / carrier reference'),text('seal','Container seal'),date('shipped_at','Actual handover time'),{key:'notes',label:'Custody notes',type:'textarea'}]},
 acknowledge:{title:'Acknowledge received transfer',action:'transfer.receive',permission:'gold.custody',mfa:true,description:'Confirm actual receipt. Dispatching a lot does not prove that it arrived.',button:'Acknowledge receipt',fields:[date('received_at','Actual receipt time'),{key:'receipt_file_id',label:'Receipt evidence',type:'evidence',family:'custody',required:true}]},
 transferException:{title:'Record custody exception',action:'transfer.exception',permission:'gold.custody',mfa:true,description:'Record the mismatch without silently completing the transfer.',button:'Flag custody exception',fields:[{key:'receipt_file_id',label:'Discrepancy evidence',type:'evidence',family:'custody',required:true},reason,{key:'notes',label:'Observed discrepancy',type:'textarea'}]},
 period:{title:'Open reconciliation period',action:'period.create',permission:'balance.prepare',description:'Define the physical accounting boundary and measurement unit before entering its balance.',button:'Open period',fields:[text('name','Period name'),{key:'kind',label:'Accounting boundary',type:'select',options:['circuit','custody'],required:true},date('starts_at','Period begins'),date('ends_at','Period ends (exclusive)'),{key:'unit',label:'Balance quantity',type:'select',options:['fine_au_g','product_g'],required:true},{key:'boundary_description',label:'Boundary / included locations and streams',type:'textarea',required:true}],defaults:{kind:'circuit',unit:'fine_au_g'}},
 preparePeriod:{title:'Prepare measured balance',action:'period.prepare',permission:'balance.prepare',description:'Enter independent opening, input, output and closing measurements. Missing values are not zero. Internal movements cancel within the chosen boundary.',button:'Submit measured balance',fields:[{key:'lines',label:'Balance observations',type:'repeat',fields:[{key:'kind',label:'Category',type:'select',options:['opening','input','output','closing'],required:true},text('label','Stream / location'),decimal('amount_g','Observed amount, g'),date('observed_at','Observation time'),text('method','Measurement / sampling basis'),source()]},decimal('tolerance_g','Approved tolerance, g'),{key:'tolerance_basis',label:'Tolerance justification / protocol',type:'textarea',required:true},{key:'exception_reason',label:'Investigation of differences',type:'textarea'}],defaults:{lines:['opening','input','output','closing'].map(kind=>({kind}))}},
 reviewPeriod:{title:'Review reconciliation',action:'period.review',permission:'balance.close',mfa:true,description:'Check the actual observations, source files and difference. The preparer cannot review their own account.',button:'Review account',fields:[reason]},
 closePeriod:{title:'Close reviewed account',action:'period.close',permission:'balance.close',mfa:true,description:'Freeze a reproducible snapshot. Later assays or corrections cannot silently rewrite this closed account.',button:'Close period',fields:[]},
 reopenPeriod:{title:'Reopen for a documented amendment',action:'period.reopen',permission:'balance.close',mfa:true,description:'The prior closed snapshot remains intact. A new preparation and independent review are required.',button:'Open amendment',fields:[reason]},
 work:{title:'Record an operational action',action:'work.save',permission:'work.write',description:'Use for a specific handover or exception that is not already represented by a record queue.',button:'Save action',fields:[text('title','Required action'),select('assigned_to','Assigned staff member','people',false),date('due_at','Required by',false),{key:'notes',label:'Context / handover',type:'textarea'}]},
 resolveWork:{title:'Resolve action',action:'work.resolve',permission:'work.write',description:'Keep the original action and record how it was resolved.',button:'Resolve action',fields:[reason]},
 document:{title:'Publish controlled document',action:'document.publish',permission:'work.write',description:'Link the approved procedure, plan or decision to its original file. Revisions preserve the previous document.',button:'Publish document reference',fields:[text('title','Document title'),{key:'category',label:'Document type',type:'select',options:['procedure','plan','handover','certificate','decision','other'],required:true},{key:'file_id',label:'Verified source',type:'evidence',family:'plant',required:true},select('supersedes','Supersedes previous document','documents',false)],defaults:{category:'procedure'}},
 allocation:{title:'Record ownership allocation',action:'allocation.record',permission:'commercial.write',description:'Document the commercial interests without changing measured mass or fine gold.',button:'Record allocation for review',fields:[{key:'interests',label:'Documented interests',type:'repeat',fields:[text('owner_reference','Owner / interest reference'),decimal('percent','Interest %')]},{key:'basis',label:'Allocation basis / agreement',type:'textarea',required:true},source()],defaults:{interests:[{}]}},
 transformation:{title:'Record pour / material transformation',action:'transformation.record',permission:'gold.custody',mfa:true,description:'Identify every held input and every weighed output, including residue. The transformation preserves material lineage and does not create new production.',button:'Record measured transformation',fields:[{key:'input_lot_ids',label:'Held input lots',type:'multi',resource:'lots',required:true},{key:'outputs',label:'Weighed outputs',type:'repeat',fields:[text('reference','Output lot reference'),{key:'form',label:'Physical form',type:'select',options:['dore','recovered_metal','concentrate','residue'],required:true},decimal('net_g','Net mass, g'),text('instrument','Scale / instrument'),decimal('resolution_g','Resolution, g')]},date('observed_at','Actual pour / transformation time'),text('location','Controlled output location'),source(),reason],defaults:{outputs:[{form:'dore'},{form:'residue'}]},prepare:(v,r)=>{const {input_lot_ids,...rest}=v;return {...rest,inputs:(input_lot_ids||[]).map((id:string)=>({lot_id:id,version:r.lots.find(l=>l.id===id)?.version}))};}},
 reviewAllocation:{title:'Review ownership allocation',action:'allocation.review',permission:'commercial.write',mfa:true,description:'Review independently against the source agreement. Physical custody is unchanged.',button:'Review allocation',fields:[reason]},
 settlement:{title:'Record refinery / commercial settlement',action:'settlement.record',permission:'commercial.write',description:'Refinery and payment records do not count as new production or silently revise the original assay.',button:'Record settlement for review',fields:[text('reference','Settlement reference'),text('counterparty','Refinery / buyer'),decimal('refinery_net_g','Refinery measured product, g',false),decimal('refinery_au_percent','Refinery Au %',false),decimal('payable_amount','Payable amount',false),{key:'currency',label:'Currency',required:false,default:'AUD'},source(),{key:'notes',label:'Deductions / differences',type:'textarea'}]},
 reviewSettlement:{title:'Review settlement',action:'settlement.review',permission:'commercial.write',mfa:true,description:'Compare settlement evidence independently. No spot-price estimate becomes booked revenue.',button:'Review settlement',fields:[reason]},
};
