'use client';
import {useState} from 'react';import Link from 'next/link';import {useOperations} from './OperationsProvider';import {Heading,Message,useResource} from './primitives';import {api} from '@/lib/ops/client';import {permissionProfiles} from '@/lib/ops/contracts';
export default function Admin(){const{context,scope,refresh}=useOperations(),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<string[]>(['operator']);const dir=useResource(scope?`directory?scope=${scope.id}`:null),bootstrap=useResource('bootstrap');const org=context?.organisations.find(o=>o.id===scope?.org_id&&o.admin)||context?.organisations.find(o=>o.admin);const names=Object.keys(permissionProfiles);
 const perform=async(fn:()=>Promise<any>)=>{setBusy(true);setError('');setMessage('');try{const r=await fn();setMessage(r.message||'Access change recorded. Permissions are checked on every accountable request.');await refresh();dir.reload();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const post=(action:string,id:string,payload:any,expectedVersion=0)=>api('admin',{action,orgId:org?.id,id,expectedVersion,payload});
 const checkbox=<fieldset className="ops-wide ops-multiselect"><legend>Assigned responsibilities</legend>{names.map(n=><label key={n}><input type="checkbox" checked={selected.includes(n)} onChange={e=>setSelected(e.target.checked?[...selected,n]:selected.filter(x=>x!==n))}/>{n.replaceAll('_',' ')}<small>{permissionProfiles[n as keyof typeof permissionProfiles].includes('gold.custody' as never)?' · sensitive custody':''}</small></label>)}</fieldset>;
 return <><Heading title="Access & settings" description="Create the real project or facility; assign named responsibilities. Access administration never implies analytical or gold approval authority."/>{context?.aal!=='aal2'&&<Message error>Verify your authenticator in <Link href="/ops/account">Account</Link> before administrative changes.</Message>}{(error||dir.error)&&<Message error>{error||dir.error}</Message>}{message&&<Message>{message}</Message>}
 {!org&&<section className="ops-card"><h2>Initial organisation setup</h2><p>Only an existing GIC owner can establish the Operations organisation. Existing production data is not copied or reinterpreted.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);perform(()=>api('admin',{action:'organisation.bootstrap',workspaceId:f.get('workspace'),name:f.get('name')}));}}><div className="ops-fields"><label>Existing owner workspace<select name="workspace" required><option value="">Choose…</option>{bootstrap.data?.workspaces.map((w:any)=><option key={w.workspace_id} value={w.workspace_id}>{w.workspace?.name||w.workspace_id}</option>)}</select></label><label>Organisation name<input name="name" required maxLength={128}/></label></div><button disabled={busy||context?.aal!=='aal2'||!bootstrap.data?.workspaces.length}>Establish organisation</button></form></section>}
 {org&&<><section className="ops-card"><h2>New workspace</h2><p>{org.name} · existing staff permissions are not copied automatically.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);perform(()=>post('scope.create',crypto.randomUUID(),{kind:f.get('kind'),code:f.get('code'),name:f.get('name'),timezone:f.get('timezone'),reason:f.get('reason')}));}}><div className="ops-fields"><label>Type<select name="kind"><option value="project">Exploration project</option><option value="facility">Processing facility</option><option value="reporting">Reporting scope</option></select></label><label>Name<input name="name" required maxLength={128}/></label><label>Code<input name="code" required maxLength={32}/></label><label>Timezone<input name="timezone" defaultValue="Australia/Brisbane" required/></label><label className="ops-wide">Reason / scope definition<textarea name="reason" required maxLength={500}/></label></div><button disabled={busy||context?.aal!=='aal2'}>Create workspace</button></form></section>
 {scope&&scope.org_id===org.id&&<><section className="ops-card"><h2>Invite a named employee or contractor</h2><p>Invitation assigns only {scope.name}. The email address must be verified by the identity provider. Invitations expire after seven days.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);perform(()=>api('admin',{action:'invitation.prepare',orgId:org.id,id:crypto.randomUUID(),expectedVersion:0,payload:{scope_id:scope.id,email:f.get('email'),profiles:selected,reason:f.get('reason')},sendEmail:f.get('emailDelivery')==='on'}));}}><div className="ops-fields"><label>Email<input name="email" type="email" required/></label><label>Reason<input name="reason" required maxLength={500}/></label>{checkbox}<label className="ops-wide"><input type="checkbox" name="emailDelivery" defaultChecked disabled={!context?.capabilities.invitationEmail}/>Send managed identity-provider invitation email</label></div><button disabled={busy||context?.aal!=='aal2'||!selected.length}>Record invitation</button></form></section>
 <section className="ops-card"><h2>Assigned staff</h2><div className="ops-table-scroll"><table><thead><tr><th>Name</th><th>Profiles</th><th>State</th><th>Access change</th></tr></thead><tbody>{dir.data?.map((m:any)=><tr key={m.user_id}><td>{m.name}</td><td>{m.profiles?.join(', ')}</td><td>{m.revoked_at?'Revoked':m.expires_at?`Expires ${m.expires_at}`:'Assigned'}</td><td><button disabled={busy||context?.aal!=='aal2'} onClick={()=>{const reason=prompt(`Reason to ${m.revoked_at?'restore selected profiles for':'revoke'} ${m.name} in ${scope.name}`);if(reason)perform(()=>post(m.revoked_at?'member.grant':'member.revoke',m.user_id,{scope_id:scope.id,profiles:selected,reason},m.version));}}>{m.revoked_at?'Restore selected profiles':'Revoke'}</button><button disabled={busy||context?.aal!=='aal2'} onClick={()=>{const reason=prompt(`Assign ${selected.join(', ')} to ${m.name}. Reason:`);if(reason)perform(()=>post('member.grant',m.user_id,{scope_id:scope.id,profiles:selected,reason},m.version));}}>Apply selected profiles</button></td></tr>)}</tbody></table></div><button disabled={busy||context?.aal!=='aal2'} onClick={()=>{const reason=prompt(`Assign ${selected.join(', ')} to your own named account for ${scope.name}. This does not bypass independent review. Reason:`);if(reason&&context)perform(()=>post('member.grant',context.userId,{scope_id:scope.id,profiles:selected,reason},dir.data?.find((m:any)=>m.user_id===context.userId)?.version||0));}}>Assign selected responsibilities to my account</button></section>
 {scope.kind==='facility'&&<section className="ops-card"><h2>Production recognition policy</h2><p>Choose the physical material form at which fine gold is first recognised. Transformations and later refinery receipt must not become duplicate production.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);perform(()=>post('scope.policy',scope.id,{recognition_form:f.get('form'),reason:f.get('reason')},scope.version));}}><div className="ops-fields"><label>Recognition form<select name="form" defaultValue={String(scope.policy.recognition_form||'dore')}><option value="dore">Doré</option><option value="recovered_metal">Recovered metal</option><option value="concentrate">Concentrate</option></select></label><label>Approved basis / reason<input name="reason" required maxLength={500}/></label></div><button disabled={busy||context?.aal!=='aal2'}>Confirm recognition policy</button></form></section>}</>}
 </>}
 </>;
}
