'use client';
import {useState} from 'react';
import Link from 'next/link';
import {api} from '@/lib/ops/client';
import {permissionProfiles} from '@/lib/ops/contracts';
import {useOperations} from './OperationsProvider';
import {Heading,Message,Empty,useResource} from './primitives';
export default function Admin(){
 const {context,scope,refresh}=useOperations(),orgs=context?.organisations.filter(o=>o.admin)||[],[org,setOrg]=useState(''),[selected,setSelected]=useState(''),[profiles,setProfiles]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const orgId=org||orgs[0]?.id,{data,reload,error:loadError}=useResource('admin'+(orgId?'?org='+orgId:''));const workspace=data?.scopes?.find((s:any)=>s.id===(selected||scope?.id))||data?.scopes?.[0];const verified=context?.aal==='aal2';
 const commit=async(action:string,payload:any,id=crypto.randomUUID(),expectedVersion=0)=>{setBusy(true);setError('');setMessage('');try{const result=await api('admin',{orgId,action,id,expectedVersion,payload});setMessage(result.message||'Access decision recorded.');reload();await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const reason=()=>window.prompt('Reason for this access change (recorded in the audit):')||'';
 return <><Heading title="Access & settings" description="Assign named responsibilities within explicit project and facility boundaries."/>{!verified&&<Message>Verify your authenticator in <Link href="/ops/account">Account</Link> before changing access or recognition policy.</Message>}{(error||loadError)&&<Message error>{error||loadError}</Message>}{message&&<Message>{message}</Message>}
 {!orgs.length?<section className="ops-card"><h2>Connect the existing operation</h2><p>A current GIC owner can establish the organisation boundary. This grants access administration only; operational roles are assigned separately.</p>{data?.legacyWorkspaces?.length?<form onSubmit={async e=>{e.preventDefault();const values=new FormData(e.currentTarget);setBusy(true);setError('');try{await api('admin',{action:'organisation.bootstrap',workspaceId:values.get('workspace'),name:values.get('name')});await refresh();reload();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label>Owned GIC operation<select name="workspace">{data.legacyWorkspaces.map((w:any)=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label>Organisation name<input name="name" required maxLength={128}/></label><button disabled={busy||!verified}>Establish organisation</button></form>:<Empty title="No administration responsibility assigned">Ask your existing operation owner to establish or grant the appropriate named access.</Empty>}</section>:<>
 <section className="ops-card"><label>Organisation<select value={orgId} onChange={e=>{setOrg(e.target.value);setSelected('');}}>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><h2>Create a workspace</h2><form onSubmit={e=>{e.preventDefault();commit('scope.create',Object.fromEntries(new FormData(e.currentTarget)));}}><div className="ops-form-grid"><label>Name<input name="name" required maxLength={128}/></label><label>Code<input name="code" required maxLength={32}/></label><label>Boundary<select name="kind"><option value="project">Geological project</option><option value="facility">Processing facility</option><option value="reporting">Reporting boundary</option></select></label><label>Time zone<input name="timezone" defaultValue="Australia/Brisbane" required/></label><label className="ops-wide">Reason<input name="reason" required maxLength={500}/></label></div><button disabled={busy||!verified}>Create workspace</button></form></section>
 {workspace&&<><section className="ops-card"><label>Manage workspace<select value={workspace.id} onChange={e=>setSelected(e.target.value)}>{data.scopes.map((s:any)=><option key={s.id} value={s.id}>{s.name} · {s.kind}</option>)}</select></label><h2>Invite a named account</h2><form onSubmit={e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.currentTarget));commit('invitation.prepare',{...p,scope_id:workspace.id,profiles});}}><div className="ops-form-grid"><label>Account email<input type="email" name="email" required/></label><label>Reason<input name="reason" required maxLength={500}/></label></div><fieldset className="ops-profile-options"><legend>Assigned responsibilities</legend>{Object.keys(permissionProfiles).map(p=><label key={p}><input type="checkbox" checked={profiles.includes(p)} onChange={e=>setProfiles(e.target.checked?[...profiles,p]:profiles.filter(x=>x!==p))}/>{p.replaceAll('_',' ')}<small>{permissionProfiles[p as keyof typeof permissionProfiles].join(', ')}</small></label>)}</fieldset><button disabled={busy||!verified||!profiles.length}>Record access invitation</button><p className="ops-muted">An existing verified account claims the invitation on sign-in. New identity accounts must be invited through the configured identity service; no email is sent from this form.</p></form></section>
 <section className="ops-card"><h2>Current memberships</h2><div className="ops-table-scroll"><table><thead><tr><th>Named account</th><th>Responsibilities</th><th>Status</th><th>Access change</th></tr></thead><tbody>{data.members.filter((m:any)=>m.scope_id===workspace.id).map((m:any)=><tr key={m.user_id}><td>{m.name}<small className="ops-block">{m.email}</small></td><td>{m.profiles.join(', ')}</td><td>{m.revoked_at?'Revoked':m.expires_at&&Date.parse(m.expires_at)<Date.now()?'Expired':'Active'}</td><td><button disabled={busy||!verified} onClick={()=>{const why=reason();if(why.trim())commit('member.revoke',{scope_id:workspace.id,reason:why},m.user_id,m.version);}}>Revoke access</button><button disabled={busy||!verified||!profiles.length} onClick={()=>{const why=reason();if(why.trim())commit('member.grant',{scope_id:workspace.id,profiles,reason:why},m.user_id,m.version);}}>Apply selected responsibilities</button></td></tr>)}</tbody></table></div><h3>Pending invitations</h3>{data.invitations.filter((i:any)=>i.scope_id===workspace.id&&!i.accepted_at&&!i.revoked_at).map((i:any)=><p key={i.id}>{i.email} · {i.profiles.join(', ')} · expires {new Date(i.expires_at).toLocaleDateString('en-AU')}</p>)}</section>
 {workspace.kind==='facility'&&<section className="ops-card"><h2>Production recognition point</h2><p>Current: {workspace.policy.recognition_confirmed?workspace.policy.recognition_form.replaceAll('_',' '):'Unconfirmed — production recognition blocked'}. This defines which physical form is counted as production. It does not define ownership or process recovery.</p><form onSubmit={e=>{e.preventDefault();commit('scope.policy',Object.fromEntries(new FormData(e.currentTarget)),workspace.id,workspace.version);}}><label>Agreed recognition form<select name="recognition_form" defaultValue={workspace.policy.recognition_form}><option value="dore">Doré</option><option value="recovered_metal">Recovered metal</option><option value="concentrate">Concentrate</option></select></label><label>Approved basis / decision reference<textarea name="reason" required maxLength={500}/></label><button disabled={busy||!verified}>Confirm recognition policy</button></form></section>}</>}
 </>}</>;
}
