'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {api,downloadBlob} from '@/lib/ops/client';
import {listVaults,readVault,type VaultEnvelope} from '@/lib/ops/offline';
import {useOperations} from './OperationsProvider';
import {Heading,Message,Status} from './primitives';
import Geology from './Geology';
export default function Field(){
 const {context,scope,online,offlineMode,pack,prepare,unlock,exportVault,sync,syncing,resolveConflict,retryBlocked}=useOperations();const [vaults,setVaults]=useState<any[]>([]),[chosen,setChosen]=useState(''),[imported,setImported]=useState<VaultEnvelope|null>(null),[passphrase,setPassphrase]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[comparison,setComparison]=useState<any>(null),[reason,setReason]=useState(''),[offlineReady,setOfflineReady]=useState(false);
 const list=()=>listVaults().then(setVaults).catch(e=>setError(e.message));useEffect(()=>{list();},[]);
 useEffect(()=>{let stopped=false;if(!('serviceWorker' in navigator))return;async function ready(){try{const r=await navigator.serviceWorker.register('/ops/sw.js',{scope:'/ops/'});await navigator.serviceWorker.ready;const worker=r.active||r.waiting||r.installing;worker?.postMessage({type:'prepare-shell',assets:performance.getEntriesByType('resource').map(r=>r.name).filter(url=>new URL(url).origin===location.origin&&new URL(url).pathname.startsWith('/_next/static/'))});const listener=(event:MessageEvent)=>{if(!stopped&&event.data?.type==='ops-shell-ready')setOfflineReady(true);};navigator.serviceWorker.addEventListener('message',listener);return()=>navigator.serviceWorker.removeEventListener('message',listener);}catch{if(!stopped)setError('Offline page preparation failed. Keep this page open; reload recovery has not been verified.');}}let clean:(()=>void)|undefined;ready().then(c=>clean=c);return()=>{stopped=true;clean?.();};},[]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setMessage('');try{await fn();await list();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const visible=vaults.filter(v=>!context||offlineMode||v.userId===context.userId),blocked=pack?.outbox.find(q=>q.state==='blocked');
 return <><Heading title={offlineMode?'Field workspace':'Prepare for the field'} description="Keep an encrypted project copy and a recoverable queue on this device."/>{error&&<Message error>{error}</Message>}{message&&<Message>{message}</Message>}
 {offlineMode&&pack?<><div className="ops-actions"><Status tone="warning">Device copy · shared authorisation checked on sync</Status><button disabled={!online||syncing} onClick={()=>run(sync)}>Reconnect & sync</button><Link href="/ops/login?next=/ops/field">Sign in to renew access</Link></div><Geology/></>:<>
 {context&&scope?.kind==='project'&&<section className="ops-card"><h2>Prepare {scope.name}</h2><p>Preparation downloads current project geometry and records. Capture is available for eight hours before access must be renewed online.</p><form onSubmit={e=>{e.preventDefault();run(async()=>{const geology=await api(`geology?scope=${scope.id}`);await prepare(passphrase,geology);setPassphrase('');setMessage('Encrypted field records saved. Export a recovery copy and complete an offline device check before leaving.');});}}><label>Device passphrase<input type="password" autoComplete="new-password" required={!pack} minLength={12} value={passphrase} onChange={e=>setPassphrase(e.target.value)}/></label><p className="ops-muted">Use at least 12 characters. This passphrase is not sent to MineralX and cannot be recovered by an administrator.</p><button className="ops-primary" disabled={busy||!online||offlineMode}>{pack?.scope.id===scope.id?'Refresh field records':'Prepare encrypted project copy'}</button></form><p><Status tone={offlineReady?'neutral':'warning'}>{offlineReady?'Offline page and loaded app assets saved':'Offline page preparation not yet confirmed'}</Status></p><p className="ops-muted">Basemap imagery is not included. Keep this page open during fieldwork. iOS storage eviction, a closed browser and operating-system suspension can interrupt work; foreground sync remains required.</p></section>}
 <section className="ops-card"><h2>Unlock saved work</h2><form onSubmit={e=>{e.preventDefault();run(async()=>{const ref=visible.find(v=>`${v.userId}:${v.scopeId}`===(chosen||`${visible[0]?.userId}:${visible[0]?.scopeId}`)),envelope=imported||(ref&&await readVault(ref.userId,ref.scopeId));if(!envelope)throw new Error('Choose a device copy or encrypted recovery file.');await unlock(envelope,passphrase,!context||!online||offlineMode);setPassphrase('');});}}>{visible.length>0&&<label>Encrypted device copy<select value={chosen||`${visible[0].userId}:${visible[0].scopeId}`} onChange={e=>{setChosen(e.target.value);setImported(null);}}>{visible.map(v=><option key={`${v.userId}:${v.scopeId}`} value={`${v.userId}:${v.scopeId}`}>Project {v.scopeId.slice(0,8)} · account {v.userId.slice(0,8)} · {new Date(v.savedAt).toLocaleString('en-AU')}</option>)}</select></label>}<label>Or import an encrypted recovery copy<input type="file" accept=".json,application/json" onChange={e=>run(async()=>{const file=e.target.files?.[0];if(!file)return;if(file.size>32*1024*1024)throw new Error('The recovery file exceeds the supported size.');const parsed=JSON.parse(await file.text());if(parsed.version!==1||!Array.isArray(parsed.ciphertext))throw new Error('Choose a MineralX encrypted field recovery file.');setImported(parsed);setMessage('Recovery file selected. Enter its original device passphrase.');})}/></label><label>Device passphrase<input type="password" autoComplete="current-password" minLength={12} required value={passphrase} onChange={e=>setPassphrase(e.target.value)}/></label><button disabled={busy||(!visible.length&&!imported)}>Unlock encrypted records</button></form><p className="ops-muted">Unlocking a historical copy never replaces a newer device revision. Decryption and account identity are checked before it is opened.</p></section></>}
 {pack&&<section className="ops-card"><div className="ops-section-heading"><h2>Synchronisation & recovery</h2><button onClick={()=>run(async()=>{const e=await exportVault();if(e)downloadBlob('MineralX-encrypted-field-recovery.json',JSON.stringify(e));})}>Export encrypted recovery</button></div><p>{pack.outbox.length} queued changes · last sync {pack.lastSyncedAt?new Date(pack.lastSyncedAt).toLocaleString('en-AU'):'Not yet synchronised'}. Offline capture window ends {new Date(pack.leaseUntil).toLocaleString('en-AU')}.</p><button disabled={busy||syncing||!online} onClick={()=>run(sync)}>{syncing?'Synchronising…':'Sync now'}</button>{pack.outbox.map(q=><article className="ops-queued" key={q.command.requestId}><h3>{q.command.action.replaceAll('geo.','').replaceAll('.',' ')}</h3><p><Status tone={q.state==='blocked'?'warning':'neutral'}>{q.state}</Status> · {q.command.payload.id as string||q.command.id.slice(0,8)}</p>{q.error&&<Message error>{q.error}</Message>}</article>)}
 {blocked&&<div className="ops-conflict"><h3>Compare before resubmitting</h3><p>The original proposed change stays in the encrypted recovery history. Nothing is overwritten automatically.</p><button disabled={!online||busy} onClick={()=>run(async()=>{const current=await api(`geology?scope=${pack.scope.id}`);setComparison(current);})}>Load current shared record</button><button disabled={!online||busy} onClick={()=>run(async()=>{await retryBlocked(blocked.command.requestId);await sync();})}>Retry unchanged after restoring access</button>{comparison&&<><div className="ops-form-grid"><div><h4>Proposed field observation</h4><pre>{JSON.stringify(blocked.command.payload,null,2)}</pre></div><div><h4>Current shared record</h4><pre>{JSON.stringify(Object.entries(comparison.project).filter(([,v])=>Array.isArray(v)).flatMap(([,v])=>v as any[]).find(r=>r.recordId===blocked.command.id)||'Record does not exist',null,2)}</pre></div></div><label>Reason for applying the retained proposal<textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={10} required/></label><button disabled={busy||reason.trim().length<10} onClick={()=>run(async()=>{const current=Object.entries(comparison.versions).find(([k])=>k.endsWith(':'+blocked.command.id));await resolveConflict(blocked.command.requestId,Number(current?.[1]||0),reason);setComparison(null);setReason('');await sync();})}>Submit proposal against compared version</button></>}</div>}</section>}
 {!context&&<Link href="/ops/login">Staff sign in</Link>}</>;
}
