'use client';
import {useEffect,useState} from 'react';import {useOperations} from './OperationsProvider';import {Heading,Message,Empty,useResource,LinkTo} from './primitives';import {listVaults,readVault,type VaultEnvelope} from '@/lib/ops/offline';import {downloadBlob} from '@/lib/ops/client';import Geology from './Geology';
export default function Field(){const{context,scope,online,offlineMode,pack,prepare,unlock,sync,exportVault,syncing}=useOperations();const shared=useResource(scope?.permissions.includes('geo.read')?`geology?scope=${scope.id}`:null);const[vaults,setVaults]=useState<Awaited<ReturnType<typeof listVaults>>>([]),[selected,setSelected]=useState(''),[pass,setPass]=useState(''),[again,setAgain]=useState(''),[upload,setUpload]=useState<VaultEnvelope|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[showRecords,setShowRecords]=useState(false);
 useEffect(()=>{listVaults().then(setVaults).catch(e=>setError(e.message));},[pack]);
 const task=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <><Heading title="Field preparation & recovery" description="Device saves, server acknowledgement and review are separate. Original files and licensed offline basemaps require their own preparation."/>{error&&<Message error>{error}</Message>}{message&&<Message>{message}</Message>}{shared.error&&<Message error>{shared.error}</Message>}
 {pack&&<section className="ops-card"><h2>{pack.scope.name} · unlocked on this device</h2><p>Prepared {pack.preparedAt} · last confirmed sync {pack.lastSyncedAt||'not confirmed'} · offline capture authorised until {pack.leaseUntil}</p><p>{pack.outbox.length} pending changes. {pack.outbox.filter(q=>q.state==='blocked').length} require review.</p><div className="ops-actions"><button disabled={!online||syncing||busy} onClick={()=>task(sync)}>Sync now</button><button onClick={()=>task(async()=>{const e=await exportVault();if(e)downloadBlob('MineralX-encrypted-field-recovery.json',JSON.stringify(e));})}>Export encrypted recovery</button>{offlineMode?<button onClick={()=>setShowRecords(!showRecords)}>{showRecords?'Hide field records':'Open offline capture'}</button>:<LinkTo area="geology">Open project →</LinkTo>}</div>
 {!!pack.outbox.length&&<details><summary>Pending changes and rejected commands</summary>{pack.outbox.map(q=><div className="ops-card" key={q.command.requestId}><strong>{q.command.action}</strong><p>{q.state} · {q.createdAt}</p>{q.error&&<Message error>{q.error}</Message>}<small>Request {q.command.requestId} · expected record revision {q.command.expectedVersion}</small></div>)}<p>Blocked high-consequence values are never overwritten automatically. Export the encrypted package and review the current shared record with a supervisor. The pending command stays preserved.</p></details>}
 </section>}{offlineMode&&showRecords&&<Geology/>}
 {!offlineMode&&context&&scope?.kind==='project'&&<section className="ops-card"><h2>Prepare this project</h2><p>Downloads authorised field records, identity dictionaries and existing project vectors. Basemap tiles and private source file bytes are not included. Keep the passphrase separately; it cannot be reset to decrypt an existing pack.</p><form onSubmit={e=>{e.preventDefault();task(async()=>{if(!shared.data)throw new Error('Wait for a complete shared-project read.');if(!pack&&pass!==again)throw new Error('Passphrases do not match.');await prepare(pass,shared.data);setPass('');setAgain('');let worker='The offline application shell is not yet prepared.';if('serviceWorker'in navigator){await navigator.serviceWorker.register('/ops/worker.js',{scope:'/ops/'});const registration=await navigator.serviceWorker.ready;if(registration.scope!==location.origin+'/ops/')throw new Error('The field service worker scope could not be verified.');const target=registration.active;if(target){const channel=new MessageChannel();await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Offline shell preparation timed out. Records are saved; reopen while connected to retry.')),45000);channel.port1.onmessage=e=>{clearTimeout(timer);e.data.ok?resolve():reject(new Error(e.data.error));};target.postMessage({type:'PREPARE_FIELD_SHELL'},[channel.port2]);});worker='Offline field screen prepared. Test reopening in airplane mode before leaving site.';}}setMessage('Encrypted device records saved. '+worker);});}}><div className="ops-fields">{!pack&&<><label>Device passphrase<input type="password" autoComplete="new-password" minLength={12} required value={pass} onChange={e=>setPass(e.target.value)}/></label><label>Repeat passphrase<input type="password" autoComplete="new-password" minLength={12} required value={again} onChange={e=>setAgain(e.target.value)}/></label></>}</div><button disabled={busy||!online||!shared.data||syncing} className="ops-primary">{busy?'Preparing…':pack?'Refresh field pack':'Prepare encrypted field pack'}</button></form></section>}
 <section className="ops-card"><h2>Unlock saved device work</h2><form onSubmit={e=>{e.preventDefault();task(async()=>{const v=upload||await readVault(selected.split('/')[0],selected.split('/')[1]);if(!v)throw new Error('Choose a saved workspace or encrypted recovery package.');await unlock(v,pass,!context||!online||offlineMode);setPass('');setShowRecords(true);});}}><div className="ops-fields"><label>Saved workspace<select value={selected} onChange={e=>{setSelected(e.target.value);setUpload(null);}}><option value="">Choose…</option>{vaults.filter(v=>!context||v.userId===context.userId).map(v=><option key={v.userId+'/'+v.scopeId} value={v.userId+'/'+v.scopeId}>Workspace {v.scopeId.slice(0,8)} · saved {v.savedAt}</option>)}</select></label><label>Or encrypted recovery file<input type="file" accept="application/json,.json" onChange={e=>task(async()=>{const f=e.target.files?.[0];if(!f)return;if(f.size>64*1024*1024)throw new Error('Recovery package exceeds 64 MiB.');const value=JSON.parse(await f.text());if(value.version!==1||!Array.isArray(value.ciphertext)||!value.userId||!value.scopeId)throw new Error('Not a supported encrypted field recovery package.');setUpload(value);})}/></label><label>Device passphrase<input type="password" autoComplete="current-password" minLength={12} required value={pass} onChange={e=>setPass(e.target.value)}/></label></div><button disabled={busy||(!upload&&!selected)}>{busy?'Verifying encryption…':'Unlock field records'}</button></form></section>
 <p className="ops-muted">Signing out or disconnecting does not erase encrypted work. Company access is rechecked on sync. This browser cannot guarantee remote revocation while disconnected or background uploads after the app closes.</p></>;
}
