'use client';
import {useState} from 'react';
import {downloadEvidence} from '@/lib/ops/client';
import {useOperations} from './OperationsProvider';
import {Heading,Message,Status,Empty,useResource} from './primitives';
import ActionForm,{EvidencePicker} from './ActionForm';
import {actions} from './action-specs';
export default function Files(){const {scope,context}=useOperations(),{data:files,error,reload}=useResource(scope?`files?scope=${scope.id}`:null),{data:documents}=useResource(scope?`documents?scope=${scope.id}`:null),[form,setForm]=useState(false),[family,setFamily]=useState(''),[chosen,setChosen]=useState(''),[issue,setIssue]=useState('');const allowed=['geo','plant','gold','custody'].filter(f=>scope?.permissions.includes('files.'+f)),selected=allowed.includes(family)?family:allowed[0];
 const open=async(id:string)=>{try{setIssue('');await downloadEvidence(scope!.id,id);}catch(e){setIssue((e as Error).message);}};
 return <><Heading title="Files & procedures" description="Original evidence and controlled documents, with their revision and protection status." action={scope?.permissions.includes('work.write')&&allowed.length>0&&<button className="ops-primary" onClick={()=>setForm(true)}>Publish document</button>}/>{(error||issue)&&<Message error>{error||issue}</Message>}{form&&<ActionForm spec={{...actions.document,fields:actions.document.fields.map(f=>f.key==='file_id'?{...f,family:selected}:f)}} resources={{files:files||[],documents:(documents||[]).filter((d:any)=>!documents.some((n:any)=>n.supersedes===d.id))}} onClose={()=>setForm(false)} onComplete={()=>setForm(false)}/>}
 {allowed.length>0&&<section className="ops-card"><h2>Attach original evidence</h2><label>Record family<select value={selected} onChange={e=>setFamily(e.target.value)}>{allowed.map(f=><option key={f}>{f}</option>)}</select></label><EvidencePicker key={selected} family={selected} files={files||[]} value={chosen} onChange={id=>{setChosen(id);reload();}}/><p className="ops-muted">{context?.capabilities.development?'Files remain on this device only. Do not use confidential evidence in a no-login workspace.':'Files are private and checked against their byte count and SHA-256 checksum before use.'}</p></section>}
 <section className="ops-card"><h2>Controlled documents</h2>{documents?.length?documents.map((d:any)=><article className="ops-document" key={d.id}><div><h3>{d.title}</h3><p>{d.category} · {documents.some((n:any)=>n.supersedes===d.id)?'Superseded — retained for history':'Current reference'} · {new Date(d.created_at).toLocaleDateString('en-AU')}</p></div><button onClick={()=>open(d.file_id)}>Open source</button></article>):<Empty title="No controlled documents published">Attach the approved source and publish its reference. A replacement preserves the earlier revision.</Empty>}</section>
 <section className="ops-card"><h2>Evidence register</h2>{files?.length?<div className="ops-table-scroll"><table><thead><tr><th>Original file</th><th>Family</th><th>Integrity</th><th>Protection</th><th>Source</th></tr></thead><tbody>{files.map((f:any)=><tr key={f.id}><td>{f.name}<small className="ops-block">{f.size_bytes} bytes · SHA-256 {f.sha256.slice(0,12)}…</small></td><td>{f.family}</td><td><Status>{f.status}</Status></td><td>{f.protection_status==='independent_copy_verified'?'Independent copy verified':'Primary copy only'}</td><td><button disabled={f.status!=='verified'} onClick={()=>open(f.id)}>Download</button></td></tr>)}</tbody></table></div>:<p>No accessible evidence in this workspace.</p>}<p className="ops-muted">{context?.capabilities.independentObjectBackup?'Independent object backup is enabled.':'An independent backup of source bytes has not been verified. Database backups alone do not restore file contents.'}</p></section></>;
}
