'use client';
import {useState} from 'react';import {useOperations} from './OperationsProvider';import {Heading,Message,Empty,useResource,Status} from './primitives';import {downloadEvidence,uploadEvidence} from '@/lib/ops/client';import ActionForm from './ActionForm';import {actions} from './action-specs';
export default function Files(){const {scope,context,refresh}=useOperations(),{data:files,error,reload}=useResource(scope?`files?scope=${scope.id}`:null),docs=useResource(scope?`documents?scope=${scope.id}`:null);const[family,setFamily]=useState(''),[busy,setBusy]=useState(false),[failure,setFailure]=useState(''),[editor,setEditor]=useState(false),[source,setSource]=useState<File|null>(null),[identity,setIdentity]=useState(()=>({id:crypto.randomUUID(),requestId:crypto.randomUUID()}));
 const families=['geo','plant','gold','custody','commercial'].filter(f=>scope?.permissions.includes('files.'+f));
 return <><Heading title="Files & procedures" description="Original evidence and controlled revisions for the selected workspace." action={scope?.permissions.includes('work.write')?<button onClick={()=>setEditor(true)}>Publish document reference</button>:undefined}/>{(failure||error||docs.error)&&<Message error>{failure||error||docs.error}</Message>}
 {editor&&<ActionForm spec={{...actions.document,fields:actions.document.fields.map(f=>f.type==='evidence'?{...f,family:families[0]||'plant'}:f)}} resources={{files:files||[],documents:docs.data||[]}} onClose={()=>setEditor(false)} onComplete={()=>{setEditor(false);docs.reload();}}/>}
 {!!families.length&&<section className="ops-card"><h2>Add source evidence</h2>{!context?.capabilities.evidence&&<Message error>Private source verification is not activated. Files will not be reported as saved.</Message>}<form onSubmit={async e=>{e.preventDefault();if(!source||!scope)return;setBusy(true);setFailure('');try{await uploadEvidence(scope.id,family||families[0],source,identity);setSource(null);setIdentity({id:crypto.randomUUID(),requestId:crypto.randomUUID()});reload();await refresh();}catch(e){setFailure((e as Error).message);}finally{setBusy(false);}}}><div className="ops-fields"><label>Evidence access group<select value={family||families[0]} onChange={e=>{setFamily(e.target.value);setIdentity({id:crypto.randomUUID(),requestId:crypto.randomUUID()});}}>{families.map(f=><option key={f}>{f}</option>)}</select></label><label>Original file<input type="file" required disabled={busy} onChange={e=>{setSource(e.target.files?.[0]||null);setIdentity({id:crypto.randomUUID(),requestId:crypto.randomUUID()});}}/></label></div><button disabled={busy||!context?.capabilities.evidence} className="ops-primary">{busy?'Uploading and verifying…':'Upload and verify'}</button>{source&&<small> {source.name} · source retained on failure; retry uses the same request.</small>}</form></section>}
 <section className="ops-card"><h2>Controlled documents</h2>{!docs.data?.length?<Empty title="No published documents">Publish a verified source with its title and revision relationship. External plant-review notes are not attributed to staff accounts.</Empty>:<ul className="ops-key-list">{docs.data.map((d:any)=><li key={d.id}><div><strong>{d.title}</strong><p>{d.category} · revision {d.version}{d.supersedes?' · supersedes prior document':''}</p></div><button onClick={()=>scope&&downloadEvidence(scope.id,d.file_id).catch(e=>setFailure(e.message))}>Open source</button></li>)}</ul>}</section>
 <section className="ops-card"><h2>Source register</h2><p className="ops-muted">Verified means bytes and checksum match. It does not prove laboratory validity. “Primary copy” is not an independent backup.</p>{!files?.length?<Empty title="No source files yet">Upload evidence here or directly in the associated record.</Empty>:<div className="ops-table-scroll"><table><thead><tr><th>File</th><th>Access</th><th>Integrity</th><th>Protection</th><th>Source</th></tr></thead><tbody>{files.map((f:any)=><tr key={f.id}><td>{f.name}<details><summary>Checksum / provenance</summary><code>{f.sha256}</code><p>{f.size_bytes} bytes · {f.created_at}</p></details></td><td>{f.family}</td><td><Status>{f.status}</Status></td><td>{f.protection_state||'Primary copy only'}</td><td><button disabled={f.status!=='verified'} onClick={()=>scope&&downloadEvidence(scope.id,f.id).catch(e=>setFailure(e.message))}>Download original</button></td></tr>)}</tbody></table></div>}</section></>;
}
