'use client';
import {useCallback,useEffect,useState} from 'react';import dynamic from 'next/dynamic';import {useSearchParams,useRouter} from 'next/navigation';import {useOperations} from './OperationsProvider';import {Heading,Message,Empty,Status,Quantity,useResource,LinkTo} from './primitives';import ActionForm,{EvidencePicker} from './ActionForm';import {geoActions} from './geology-specs';import {api,newCommand,downloadEvidence,downloadBlob} from '@/lib/ops/client';import {versionAt} from '@/lib/ops/geology.js';import {localDateTime} from '@/lib/ops/time';import {Facts,History} from './Plant';import {useEntryGuard} from './navigation';
const SharedMap=dynamic(()=>import('./SharedMap'),{ssr:false,loading:()=> <p role="status">Loading project map…</p>});
const views=[['map','Map'],['samples','Samples'],['collars','Drilling'],['programs','Programs'],['dispatches','Dispatch & receipt'],['lab','Laboratory'],['spatialLayers','Imported layers'],['targets','Targets']];
export default function Geology(){const{scope,context,pack,offlineMode,revision}=useOperations(),query=useSearchParams(),router=useRouter();const[view,setView]=useState(query.get('view')||'map'),[item,setItem]=useState(query.get('item')||''),[form,setForm]=useState<any>(query.get('action')==='sample'?{key:'sample'}:null),[filter,setFilter]=useState(''),[error,setError]=useState(''),[importer,setImporter]=useState(false);
 const fetched=useResource(scope?.permissions.includes('geo.read')&&!pack?.outbox.length?`geology?scope=${scope.id}`:null);const shared=(pack&&pack.scope.id===scope?.id&&(offlineMode||pack.outbox.length))?pack.geology:fetched.data;
 const project=shared?.project;const kind=view==='lab'?'assayBatches':view;
 useEffect(()=>{setView(query.get('view')||'map');setItem(query.get('item')||'');},[query]);
 const open=useCallback((kind:string,id:string)=>{const actual=kind==='boundary'?'map':kind==='assayBatches'?'lab':kind;setView(actual);setItem(id);if(!offlineMode&&scope)router.replace(`/ops/geology?scope=${scope.id}&view=${actual}${id?'&item='+id:''}`);},[scope,router,offlineMode]);
 if(!scope||scope.kind!=='project'||!scope.permissions.includes('geo.read'))return <><Heading title="Geology"/><Empty title="Choose an assigned geological project">Select a project in the workspace header. Existing local data remains in the original local geology workspace until a reviewed migration.</Empty><LinkTo area="admin">Workspace access</LinkTo></>;
 if(!project)return <><Heading title="Geology" description={scope.name}/>{fetched.error?<Message error>{fetched.error}</Message>:<p role="status">Loading the complete shared project…</p>}<LinkTo area="field">Unlock prepared device records</LinkTo></>;
 const lists=Object.fromEntries(['programs','samples','collars','targets'].map(k=>[k,(project[k]||[]).filter((r:any)=>!r.archivedAt).map((r:any)=>({...r,name:r.name||r.id,reference:r.id||r.name}))]));
 const row=(project[kind]||[]).find((r:any)=>r.recordId===item);const dispatched=new Set((project.dispatches||[]).flatMap((d:any)=>d.sampleRecordIds||[]));
 const resources={...lists,files:[],primarySamples:lists.samples.filter((r:any)=>!r.qaqcType||r.qaqcType==='none'),availableSamples:lists.samples.filter((s:any)=>!dispatched.has(s.recordId)),manifestSamples:lists.samples.filter((s:any)=>row?.sampleRecordIds?.includes(s.recordId)),receiptEvents:(row?.receiptEvents||[]).map((r:any)=>({...r,name:r.reference||r.recordedAt}))};
 const start=(key:string,existing?:any,more?:any)=>{setImporter(false);setForm({key,id:existing?.recordId,expected:existing?versionAt(shared.versions,kind,existing.recordId):0,initial:existing&&key==='correct'?{notes:existing.notes,lith:existing.lith}:existing&&key==='collar'?existing:key==='sample'?{date:localDateTime(new Date().toISOString(),scope.timezone).slice(0,10)}:undefined,...more});};
 const action=(key:string,existing?:any)=>scope.permissions.includes(geoActions[key].permission)&&<button key={key} onClick={()=>start(key,existing)}>{geoActions[key].title}</button>;
 const file=(id:string)=>downloadEvidence(scope.id,id).catch(e=>setError(e.message));
 return <><Heading title={scope.name} description="One physical sample, with separate field, custody, analytical and sync states." action={scope.permissions.includes('geo.capture')?<button className="ops-primary" data-ops-navigation onClick={()=>start('sample')}>Collect sample</button>:undefined}/>{!context?.capabilities.sharedGeology&&!offlineMode&&<Message error>The trusted shared-geology service has not been activated. Read access is separate from publication readiness.</Message>}{(error||fetched.error)&&<Message error>{error||fetched.error}</Message>}
 <nav className="ops-tabs" aria-label="Geology registers">{views.map(([v,label])=><button data-ops-navigation key={v} aria-selected={view===v} onClick={()=>{setForm(null);setImporter(false);open(v,'');}}>{label}</button>)}</nav>
 {form&&<ActionForm key={`${form.key}:${form.id||'new'}`} spec={geoActions[form.key]} recordId={form.id} expectedVersion={form.expected||0} initial={form.initial} extra={form.extra} resources={resources} onClose={()=>setForm(null)} onComplete={()=>{setForm(null);fetched.reload();}}/>}
 {!form&&<div className="ops-actions">{view==='programs'&&action('program')}{view==='collars'&&action('collar')}{view==='targets'&&action('target')}{view==='dispatches'&&!row&&action('manifest')}{view==='lab'&&!row&&action('assay')}{['samples','collars'].includes(view)&&!row&&action('csv')}{(view==='map'||view==='spatialLayers')&&scope.permissions.includes('geo.publish')&&<button onClick={()=>setImporter(true)}>Import map files / legacy backup</button>}<LinkTo area="field">Prepare for field / sync</LinkTo></div>}
 {importer&&<SpatialPublisher onClose={()=>setImporter(false)} onDone={()=>{setImporter(false);fetched.reload();}}/>}
 {view==='map'&&!form&&!importer&&<SharedMap project={project} userId={context!.userId} onOpen={open}/>}
 {view!=='map'&&row&&!form?<section className="ops-card"><button className="ops-link" onClick={()=>open(view,'')}>← Back to register</button><h2>{row.id||row.name||row.certificate||'Record'}</h2><p className="ops-context-line">{kind} · version {versionAt(shared.versions,kind,row.recordId)} · {row.recordId}</p><Facts record={row} omit={['recordId','sourceText']}/>
 {kind==='samples'&&<><div className="ops-actions">{action('correct',row)}{!row.archivedAt&&action('archive',row)}</div><h3>Analytical state</h3><Status>{row.assayReviewStatus||'pending'}</Status><p>Physical custody: {row.lifecycle||'collected'}</p><details><summary>Accepted results and preserved history</summary><pre>{JSON.stringify({assays:row.assays,detectionLimits:row.detectionLimits,lowerLimits:row.lowerLimits,history:row.assayHistory},null,2)}</pre></details></>}
 {kind==='collars'&&<>{action('collar',row)}<h3>Recorded sample intervals</h3>{project.intervals.filter((i:any)=>i.collarRecordId===row.recordId).map((i:any)=><p key={i.recordId}>{i.sampleId} · {i.from}–{i.to} m</p>)}</>}
 {kind==='targets'&&action('link',row)}
 {kind==='dispatches'&&<><h3>Physical bags</h3><p>{resources.manifestSamples.map((s:any)=>s.id).join(', ')}</p><div className="ops-actions">{row.status==='prepared'&&action('ship',row)}{['shipped','receipt_exception','received'].includes(row.status)&&action('receive',row)}{row.status==='receipt_exception'&&action('exception',row)}</div><details><summary>Shipment and receipt evidence</summary><pre>{JSON.stringify({shipments:row.shipments,receipts:row.receiptEvents,resolutions:row.exceptionResolutions},null,2)}</pre></details></>}
 {kind==='assayBatches'&&<>{row.sourceFileId&&<button onClick={()=>file(row.sourceFileId)}>Open original certificate / results</button>}<p>{row.errors?.join(' ')}</p><p>{row.warnings?.join?.(' ')||''}</p><div className="ops-actions">{row.status!=='released'&&action('release',row)}{action('hold',row)}</div><details open><summary>Staged analytical rows</summary><div className="ops-preview"><pre>{JSON.stringify(row.rows||row.results||row,null,2)}</pre></div></details></>}
 {kind==='spatialLayers'&&<><div className="ops-actions">{row.source?.fileId&&<button onClick={()=>file(row.source.fileId)}>Export exact original</button>}<button onClick={()=>downloadBlob(`${row.name||'Geology'}.geojson`,JSON.stringify(row.data),'application/geo+json')}>Export GeoJSON</button>{action(row.archivedAt?'layerRestore':'layerArchive',row)}</div><details><summary>Attributes and source provenance</summary><pre>{JSON.stringify({source:row.source,features:row.data.features},null,2)}</pre></details></>}
 </section>:view!=='map'&&!form&&!importer&&<section className="ops-card"><div className="ops-table-tools"><label>Find a record<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Bag, hole, name or certificate"/></label><span>{(project[kind]||[]).length} records</span></div>{!(project[kind]||[]).length?<Empty title="No records yet">Use the primary action for this workflow. Source imports preserve their own provenance.</Empty>:<div className="ops-table-scroll"><table><thead><tr><th>Reference</th><th>Work / method</th><th>State</th><th>Recorded</th><th>Details</th></tr></thead><tbody>{project[kind].filter((r:any)=>JSON.stringify([r.id,r.name,r.certificate]).toLowerCase().includes(filter.toLowerCase())).slice(0,500).map((r:any)=><tr key={r.recordId}><td>{r.id||r.name||r.certificate||r.recordId}</td><td>{r.sampleType||r.method||r.laboratory||r.form||'—'}</td><td><Status>{r.archivedAt?'archived':r.status||r.lifecycle||'recorded'}</Status></td><td>{r.date||r.createdAt||r.recordedAt||r.publishedAt||'—'}</td><td><button onClick={()=>open(view,r.recordId)}>Open record</button></td></tr>)}</tbody></table>{project[kind].length>500&&<p>First 500 matching records shown. Narrow the search; complete source exports retain all records.</p>}</div>}</section>}
 </>;
}
function SpatialPublisher({onClose,onDone}:{onClose:()=>void;onDone:()=>void}){
 const{scope,context,send}=useOperations(),[fileId,setFileId]=useState(''),[role,setRole]=useState('reference'),[name,setName]=useState(''),[replace,setReplace]=useState(false),[migration,setMigration]=useState(false),[legacyId,setLegacyId]=useState(''),[reason,setReason]=useState(''),[ack,setAck]=useState(false),[preview,setPreview]=useState<any>(null),[command,setCommand]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEntryGuard(!!fileId,busy);
 const reset=()=>{setPreview(null);setCommand(null);};
 return <section className="ops-card ops-editor"><div className="ops-editor-heading"><div><h2>{migration?'Review local-to-shared migration':'Publish project map source'}</h2><p>{scope?.name} · original bytes retained · no imported point becomes an approved sample</p></div><button onClick={()=>{if(!fileId||confirm('Close the unpublished import? The source file stays retained, but geometry is not published.'))onClose();}} disabled={busy}>Close</button></div>
 {error&&<Message error>{error}</Message>}<label><input type="checkbox" checked={migration} onChange={e=>{setMigration(e.target.checked);reset();}}/>Migrate one existing local project instead of a map layer</label><fieldset><legend>Original {migration?'single-project backup':'KML / KMZ / GeoJSON'}</legend><EvidencePicker value={fileId} onChange={id=>{setFileId(id);reset();}} family="geo" required files={[]}/></fieldset>
 <div className="ops-fields">{migration?<><label>Original project ID<input value={legacyId} onChange={e=>{setLegacyId(e.target.value);reset();}} required/></label><label>Migration reason<input value={reason} onChange={e=>{setReason(e.target.value);reset();}} required/></label><p className="ops-wide">Use the original workspace’s full backup. It must contain one project and the shared destination must be empty. Historical free-text reviewers remain unverified history; they do not become employee approvals.</p></>:<><label>Layer name<input value={name} onChange={e=>{setName(e.target.value);reset();}}/></label><label>Use as<select value={role} onChange={e=>{setRole(e.target.value);reset();}}><option value="reference">Separate geological reference layer</option><option value="boundary">Project tenement boundary and retained source layer</option></select></label>{role==='boundary'&&<label className="ops-wide"><input type="checkbox" checked={replace} onChange={e=>{setReplace(e.target.checked);reset();}}/>Replace the existing boundary (prior geometry remains in history)</label>}</>}
 <label className="ops-wide"><input type="checkbox" checked={ack} onChange={e=>{setAck(e.target.checked);reset();}}/>I have reviewed source scope, coordinate system and unsupported-content warnings</label></div>
 <div className="ops-actions"><button disabled={busy||!fileId} onClick={async()=>{if(!scope)return;setBusy(true);setError('');try{const cmd=newCommand(scope.id,migration?'geo.migrate':'geo.layer.import',migration?{sourceFileId:fileId,legacyProjectId:legacyId,confirm:true,reason}:{sourceFileId:fileId,name,role,replace,acknowledged:ack});const p=await api('geology',{...cmd,dryRun:true});setPreview(p);setCommand(cmd);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{busy?'Validating…':'Validate and preview'}</button>{preview&&<button className="ops-primary" disabled={busy||!ack||migration&&context?.aal!=='aal2'} onClick={async()=>{setBusy(true);setError('');try{await send(command);onDone();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Publish reviewed {migration?'migration':'map layer'}</button>}</div>
 {preview&&<section className="ops-check-answers"><h3>Preview — not published</h3><p>Destination: {scope?.name}. {migration?'A source-preserving migration does not authenticate old analytical approvals.':'All validated features are included; tenement mode uses all polygon parts and exclusions.'}</p><div className="ops-preview"><pre>{JSON.stringify({changes:preview.changes||preview.summary,warnings:preview.warnings,stats:preview.stats},null,2)}</pre></div>{migration&&context?.aal!=='aal2'&&<Message error>Verify your authenticator in Account before migration publication.</Message>}</section>}
 </section>;
}
