import type {ActionSpec,Field} from './action-specs';
import {SAMPLE_TYPES} from '@/components/mineralx/project-store.js';
const t=(key:string,label:string,required=true):Field=>({key,label,required});
const n=(key:string,label:string,required=true):Field=>({key,label,type:'number',required});
const choice=(key:string,label:string,resource:string,required=false):Field=>({key,label,type:'select',resource,required});
const options=(key:string,label:string,values:string[]):Field=>({key,label,type:'select',options:values,required:true});
const reason:Field={key:'reason',label:'Decision / correction reason',type:'textarea',required:true};
const source:Field={key:'sourceFileId',label:'Verified original source',type:'evidence',family:'geo',required:true};
// Sampling methods are a common vocabulary across Exploration and the
// Geology Globe. Older field records can retain their original method;
// this only keeps new-entry choices consistent.
const methods=[...SAMPLE_TYPES];
const drilling=(v:any)=>['rc','diamond_core'].includes(v.sampleType)&&!['blank','standard'].includes(v.qaqcType);
const surface=(v:any)=>!drilling(v)&&!['blank','standard'].includes(v.qaqcType);
const sampleFields:Field[]=[t('id','Physical sample / bag identifier'),{key:'date',label:'Actual collection date',type:'date',required:true},options('sampleType','Sampling method',methods),choice('programId','Sampling program','programs'),options('qaqcType','QA/QC role',['none','blank','standard','duplicate','triplicate']),{...t('referenceMaterial','Certified reference material'),when:v=>v.qaqcType==='standard'},{...choice('duplicateRecordId','Original physical sample','samples',true),when:v=>['duplicate','triplicate'].includes(v.qaqcType)},{...choice('collarRecordId','Drillhole','collars',true),when:drilling},{...n('from','From, m'),when:drilling},{...n('to','To, m'),when:drilling},{...n('lat','Latitude, WGS84'),when:surface},{...n('lng','Longitude, WGS84'),when:surface},{...options('coordSource','Coordinate source',['gps','survey','manual','unknown']),when:surface},{...n('coordinateAccuracyM','Reported coordinate accuracy, m',false),when:surface},{...n('recoveryPercent','Measured sample recovery, %',false),when:drilling},{...t('splitMethod','Split method',false),when:drilling},{key:'coreFraction',label:'Core fraction',type:'select',options:['whole','half','quarter'],when:v=>v.sampleType==='diamond_core'},t('lith','Lithology / field description',false),{key:'notes',label:'Field notes',type:'textarea'}];
export const geologyActions:Record<string,ActionSpec>={
 sample:{title:'Collect a physical sample',action:'geo.sample.capture',permission:'geo.capture',description:'Record the bag once. Field observations and laboratory results remain separate.',button:'Save sample',defaults:{sampleType:'rock_chip',qaqcType:'none',coordSource:'manual'},fields:sampleFields},
 correct:{title:'Correct sample observations',action:'geo.sample.correct',permission:'geo.capture',description:'Preserve the identity and original observations. Physical drill interval identity is not relabelled.',button:'Record correction',fields:[n('lat','Latitude, WGS84',false),n('lng','Longitude, WGS84',false),{key:'date',label:'Collection date',type:'date'},t('lith','Lithology',false),{key:'notes',label:'Notes',type:'textarea'},reason],prepare:v=>({reason:v.reason,patch:Object.fromEntries(Object.entries(v).filter(([k,value])=>k!=='reason'&&value!==''&&value!==null&&value!==undefined))})},
 archive:{title:'Archive sample',action:'geo.sample.archive',permission:'geo.capture',description:'Retain the historical identity and a documented reason.',button:'Archive sample',fields:[reason]},
 collar:{title:'Record drillhole',action:'geo.collar.save',permission:'geo.capture',description:'Actual drilled depth bounds physical samples. Planned depth does not establish a sampled interval.',button:'Save drillhole',fields:[t('id','Hole identifier'),choice('programId','Work program','programs'),n('lat','Collar latitude, WGS84'),n('lng','Collar longitude, WGS84'),n('actualDepth','Actual drilled depth, m'),n('plannedDepth','Planned depth, m',false),n('azimuth','Azimuth, degrees',false),n('dip','Dip, degrees',false),{key:'notes',label:'Collar notes',type:'textarea'},{...reason,required:false,hint:'Required when correcting an existing collar.'}]},
 program:{title:'Create sampling program',action:'geo.program.create',permission:'geo.capture',description:'Group collection under an explicit program.',button:'Create program',fields:[t('name','Program name'),options('method','Primary method',methods)],defaults:{method:'rock_chip'}},
 target:{title:'Record field target',action:'geo.target.create',permission:'geo.capture',description:'A target records planned work and its location. It is not a resource estimate.',button:'Record target',fields:[t('name','Target name'),choice('programId','Work program','programs'),n('lat','Latitude, WGS84'),n('lng','Longitude, WGS84'),{key:'notes',label:'Geological basis / planned follow-up',type:'textarea'}]},
 linkTarget:{title:'Link completed field sample',action:'geo.target.link',permission:'geo.capture',description:'Link the physical sample collected for this target.',button:'Link sample',fields:[choice('sampleRecordId','Collected sample','samples',true)]},
 dispatch:{title:'Prepare sample dispatch',action:'geo.dispatch.prepare',permission:'geo.capture',description:'Select actual bags. Preparing a manifest does not mark them shipped.',button:'Prepare manifest',fields:[t('laboratory','Receiving laboratory'),{key:'sampleRecordIds',label:'Physical samples',type:'multi',resource:'dispatchable',required:true}]},
 ship:{title:'Record dispatch shipment',action:'geo.dispatch.ship',permission:'geo.capture',description:'Record the actual shipment and carrier reference.',button:'Record shipment',fields:[t('tracking','Carrier / tracking reference'),{key:'shippedDate',label:'Actual shipping date',type:'date',required:true}]},
 receipt:{title:'Reconcile laboratory receipt',action:'geo.dispatch.receive',permission:'geo.capture',description:'Tick only bags actually acknowledged by the laboratory. Unreceived bags and discrepancies remain visible.',button:'Record receipt',fields:[t('reference','Laboratory receipt reference'),{key:'receivedIds',label:'Received physical samples',type:'multi',resource:'manifest'},{key:'exceptions',label:'Receipt exceptions',type:'repeat',fields:[t('sampleId','Bag reference, if known',false),{key:'reason',label:'Observed discrepancy',type:'textarea',required:true}]}]},
 receiptException:{title:'Resolve receipt exception',action:'geo.dispatch.exception',permission:'lab.review',mfa:true,description:'Document the independent decision against the original discrepancy.',button:'Resolve exception',fields:[choice('eventRecordId','Receipt event','receiptEvents',true),reason]},
 assay:{title:'Stage laboratory certificate',action:'geo.assay.stage',permission:'geo.capture',description:'Upload the original CSV certificate. Qualifiers, laboratory, method and revision are retained for independent review.',button:'Stage certificate',fields:[source,t('certificate','Certificate identifier'),t('laboratory','Laboratory'),t('method','Analytical method'),t('revision','Certificate revision'),{key:'confirmCanonical',label:'I confirm canonical units for headers without explicit units',type:'check',hint:'Only confirm after checking the certificate; otherwise ambiguous columns remain blocked.'}],defaults:{revision:'1'}},
 release:{title:'Release reviewed analytical results',action:'geo.assay.release',permission:'lab.review',mfa:true,description:'An independent reviewer confirms source identity, receipts and project-specific QA/QC. This does not certify a Mineral Resource or imply JORC compliance.',button:'Release results',fields:[reason]},
 hold:{title:'Hold laboratory certificate',action:'geo.assay.hold',permission:'lab.review',mfa:true,description:'Retain the original certificate and document the unresolved issue.',button:'Hold certificate',fields:[reason]},
 csv:{title:'Import geological register',action:'geo.log.import',permission:'geo.capture',description:'Validate the original CSV against physical identities and the declared coordinate reference system.',button:'Import reviewed CSV',fields:[source,options('kind','Record family',['samples','collars','intervals','surveys','geology']),t('crs','Source coordinate reference system',false),{key:'acknowledged',label:'I reviewed the parser warnings and source columns',type:'check'}],defaults:{kind:'samples'}},
 layer:{title:'Publish project map source',action:'geo.layer.import',permission:'geo.publish',description:'KML, KMZ and GeoJSON preserve multipart geometry, interior rings and original source bytes. Review the preview before publication.',button:'Publish reviewed map layer',fields:[source,t('name','Layer name'),options('role','Project role',['reference','boundary']),{key:'replace',label:'Replace the active boundary, retaining prior source layers',type:'check'},{key:'acknowledged',label:'I reviewed geometry, warnings and the destination project',type:'check'}],defaults:{role:'reference'}},
 archiveLayer:{title:'Archive map layer',action:'geo.layer.archive',permission:'geo.publish',description:'Retain the original source and record why it is no longer active.',button:'Archive layer',fields:[reason]},
 restoreLayer:{title:'Restore map layer',action:'geo.layer.restore',permission:'geo.publish',description:'Restore a retained layer to the current project context.',button:'Restore layer',fields:[reason]},
 migrate:{title:'Migrate a reviewed local project',action:'geo.migrate',permission:'geo.publish',mfa:true,description:'Use a complete backup from local geology. The shared destination must be empty; historical free-text review is retained as unverified provenance.',button:'Migrate reviewed project',fields:[source,t('legacyProjectId','Project ID from the local backup'),reason,{key:'confirm',label:'I reviewed the migration preview and confirm this empty destination',type:'check'}]},
 metadata:{title:'Update project details',action:'geo.project.update',permission:'geo.publish',description:'Keep stable identities while correcting the shared project description.',button:'Save project details',fields:[t('name','Project name'),t('idPrefix','Sample identifier prefix'),{key:'description',label:'Project description',type:'textarea'},reason]},
};
