import type {ActionSpec,Field} from './action-specs';
const t=(key:string,label:string,required=true):Field=>({key,label,required});
const n=(key:string,label:string,required=false):Field=>({key,label,type:'number',required});
const s=(key:string,label:string,options:string[],required=true):Field=>({key,label,type:'select',options,required});
const r=(key:string,label:string,resource:string,required=false):Field=>({key,label,type:'select',resource,required});
const reason:Field={key:'reason',label:'Decision / correction reason',type:'textarea',required:true};
const source:Field={key:'sourceFileId',label:'Verified original source',type:'evidence',family:'geo',required:true};
const reference=(v:any)=>['blank','standard'].includes(v.qaqcType);
const drilling=(v:any)=>['rc','diamond_core'].includes(v.sampleType)&&!reference(v);
const coordinate=(v:any)=>!reference(v)&&!drilling(v);
export const geoActions:Record<string,ActionSpec>={
 sample:{title:'Collect physical sample',action:'geo.sample.capture',permission:'geo.capture',description:'Record the real bag, location or drilled interval. Reference controls require no invented coordinates.',button:'Save sample',defaults:{sampleType:'rock_chip',qaqcType:'none'},fields:[t('id','Physical bag ID'),{key:'date',label:'Collection date',type:'date',required:true},s('sampleType','Sampling method',['rock_chip','soil','float','rc','diamond_core','other']),r('programId','Program','programs'),s('qaqcType','Control type',['none','blank','standard','duplicate','triplicate']),{...t('referenceMaterial','Certified reference material'),when:v=>v.qaqcType==='standard'},{...r('duplicateRecordId','Original physical sample','samples',true),when:v=>['duplicate','triplicate'].includes(v.qaqcType)},{...n('lat','Latitude (WGS84)',true),when:coordinate},{...n('lng','Longitude (WGS84)',true),when:coordinate},{...n('coordinateAccuracyM','GPS accuracy, m'),when:coordinate},{...r('collarRecordId','Drillhole','collars',true),when:drilling},{...n('from','From depth, m',true),when:drilling},{...n('to','To depth, m',true),when:drilling},{...n('recoveryPercent','Measured sample recovery %'),when:drilling},{...s('condition','Sample condition',['dry','damp','wet','unknown'],false),when:drilling},{...t('splitMethod','Splitting method',false),when:drilling},{...s('coreFraction','Core fraction',['whole','half','quarter'],false),when:v=>v.sampleType==='diamond_core'&&!reference(v)},{...t('lith','Lithology / material description',false)},{key:'notes',label:'Field observation',type:'textarea'}]},
 correct:{title:'Correct sample metadata',action:'geo.sample.correct',permission:'geo.capture',description:'Physical identity, interval and reviewed analytical values cannot be changed through metadata corrections.',button:'Save correction',fields:[t('lith','Lithology / material description',false),{key:'notes',label:'Field observation',type:'textarea'},reason],prepare:v=>({patch:{lith:v.lith,notes:v.notes},reason:v.reason})},
 archive:{title:'Archive sample',action:'geo.sample.archive',permission:'geo.capture',description:'Retain the bag, source and history. This does not erase evidence.',button:'Archive record',fields:[reason]},
 program:{title:'Create sampling program',action:'geo.program.create',permission:'geo.capture',description:'Group planned field work without changing physical sample identity.',button:'Create program',fields:[t('name','Program name'),s('method','Sampling method',['rock_chip','soil','float','rc','diamond_core','other'])],defaults:{method:'rock_chip'}},
 collar:{title:'Record drillhole / progress',action:'geo.collar.save',permission:'geo.capture',description:'Keep planned depth separate from measured actual drilled depth. Sampling beyond actual progress is blocked.',button:'Save drilling progress',fields:[t('id','Hole ID'),n('lat','Latitude (WGS84)',true),n('lng','Longitude (WGS84)',true),n('azimuth','Azimuth (0–<360°)'),n('dip','Dip (−90–90°)'),n('plannedDepth','Planned depth, m'),n('actualDepth','Actual drilled depth, m'),{...reason,required:false,hint:'Required when correcting an existing hole.'}]},
 target:{title:'Record exploration target',action:'geo.target.create',permission:'geo.capture',description:'A reference target is not a physical bag or an approved discovery.',button:'Save target',fields:[t('name','Target name'),n('lat','Latitude (WGS84)',true),n('lng','Longitude (WGS84)',true),{key:'notes',label:'Target basis / observation',type:'textarea'}]},
 link:{title:'Link actual sampling evidence',action:'geo.target.link',permission:'geo.capture',description:'Explicitly associate an actual primary sample. Proximity alone does not complete a target.',button:'Link evidence',fields:[r('sampleRecordId','Physical primary sample','primarySamples',true)]},
 manifest:{title:'Prepare laboratory dispatch',action:'geo.dispatch.prepare',permission:'geo.capture',description:'A prepared manifest does not claim that the bags have left site.',button:'Prepare manifest',fields:[t('laboratory','Receiving laboratory'),{key:'sampleRecordIds',label:'Physical bags to dispatch',type:'multi',resource:'availableSamples',required:true}]},
 ship:{title:'Record actual shipment',action:'geo.dispatch.ship',permission:'geo.capture',description:'Confirm the actual shipment date and tracking reference. Only a prepared manifest can be shipped.',button:'Record shipment',fields:[t('tracking','Shipment / tracking reference'),{key:'shippedDate',label:'Actual shipping date',type:'date',required:true}]},
 receive:{title:'Reconcile laboratory receipt',action:'geo.dispatch.receive',permission:'geo.capture',description:'Select only the bags confirmed received. Partial receipts remain exceptions; earlier receipts are retained.',button:'Record laboratory receipt',fields:[t('reference','Laboratory receipt reference'),{key:'receivedIds',label:'Bags received in this receipt',type:'multi',resource:'manifestSamples',required:true}]},
 exception:{title:'Resolve receipt exception',action:'geo.dispatch.exception',permission:'lab.review',mfa:true,description:'Record a reasoned disposition of the specific exception, not an invented laboratory receipt.',button:'Record exception decision',fields:[r('eventRecordId','Receipt event','receiptEvents',true),reason]},
 assay:{title:'Stage laboratory results',action:'geo.assay.stage',permission:'geo.capture',description:'Original certificate/source, laboratory and method are retained. Results remain staged until an independent reviewer releases them.',button:'Stage results',fields:[source,t('laboratory','Laboratory'),t('certificate','Certificate number'),t('revision','Certificate revision'),t('method','Analytical method'),{key:'confirmCanonical',label:'I have confirmed the CSV headers and declared result units',type:'check',required:true}],defaults:{revision:'1'}},
 release:{title:'Release reviewed certificate',action:'geo.assay.release',permission:'lab.review',mfa:true,description:'Compare the source, sample identities, receipt exceptions and QA/QC. The importing account cannot release its own batch.',button:'Release analytical revision',fields:[reason]},
 hold:{title:'Hold analytical batch',action:'geo.assay.hold',permission:'lab.review',mfa:true,description:'Retain original results and record the review blocker.',button:'Hold results',fields:[reason]},
 csv:{title:'Import geological CSV',action:'geo.log.import',permission:'geo.capture',description:'Upload a source with explicit IDs, units and coordinate reference. Unknown coordinate systems are never guessed.',button:'Import verified CSV',fields:[source,s('kind','Record type',['samples','collars','intervals','surveys','geology']),{key:'acknowledged',label:'I have checked the file structure and units; accept validation warnings',type:'check'}]},
 layerArchive:{title:'Archive imported layer',action:'geo.layer.archive',permission:'geo.publish',description:'Retains original source and geometry. Personal visibility does not require a published archival action.',button:'Archive layer',fields:[reason]},
 layerRestore:{title:'Restore archived layer',action:'geo.layer.restore',permission:'geo.publish',description:'Restore the retained published geometry, not a replacement source.',button:'Restore layer',fields:[reason]},
};
