'use client';
import {useCallback,useEffect,useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import {api,downloadBlob,downloadEvidence} from '@/lib/ops/client';
import {rowsToCsv} from '@/lib/ops/contracts';
import {versionAt} from '@/lib/ops/geology.js';
import {useOperations} from './OperationsProvider';
import {Heading,Message,Empty,Status,LinkTo,useResource} from './primitives';
import ActionForm from './ActionForm';
import {geologyActions} from './geology-specs';
import dynamic from 'next/dynamic';
import {mayNavigate} from './navigation';
const SharedMap=dynamic(()=>import('./SharedMap'),{ssr:false,loading:()=> <p role="status">Loading project map…</p>});
import {Facts} from './Plant';
import Link from 'next/link';
import {elementInfo} from '@/components/mineralx/project-store.js';
import {scopeLabel} from '@/lib/ops/suite-navigation';
import {openProgramChoices,programChoices} from '@/lib/ops/workflow-model';
const views=[['samples','Samples'],['collars','Drilling'],['map','Map & sources'],['dispatches','Dispatch'],['lab','Laboratory'],['targets','Targets']];
export default function Geology(){
 const {scope,pack,offlineMode,online,context,development}=useOperations(),query=useSearchParams(),router=useRouter(),view=query.get('view')||'samples',item=query.get('item');const [form,setForm]=useState<any>(null),[filter,setFilter]=useState(''),[issue,setIssue]=useState(''),[archived,setArchived]=useState(false);
 const {data,error,loading}=useResource(scope?.kind==='project'?`geology?scope=${scope.id}`:null),{data:files}=useResource(scope?.kind==='project'?`files?scope=${scope.id}`:null);
 const local=pack&&pack.scope.id===scope?.id?pack.geology:null,snapshot=local&&(offlineMode||!online||pack?.outbox.length)?local:data,project=snapshot?.project;
 const kind=view==='lab'||view==='assayBatches'?'assayBatches':view==='map'?'spatialLayers':view,record=project?.[kind]?.find((r:any)=>r.recordId===item);
 const open=useCallback((k:string,id:string)=>{if(!mayNavigate())return;setForm(null);const path=`/ops/${offlineMode?'field':'geology'}?scope=${scope?.id}&view=${k==='assayBatches'?'lab':k==='spatialLayers'||k==='boundary'?'map':k}&item=${id}`;if(offlineMode)window.history.pushState(null,'',path);else router.push(path);},[router,scope?.id,offlineMode]);
 useEffect(()=>{if(query.get('action')==='sample')setForm({key:'sample'});},[query]);
 if(!scope||scope.kind!=='project')return <><Heading title="Exploration"/><Empty title={development?'Opening Exploration':'Choose an exploration project'}>{development?'Exploration opens the compatible records in your Development workspace automatically.':'Select your assigned project. A processing facility is a separate operational boundary.'}</Empty></>;
 if(!scope.permissions.includes('geo.read'))return <><Heading title="Exploration"/><Empty title="Exploration access is not assigned">Project administration does not automatically grant access to field records.</Empty></>;
 const requestedProgram=query.get('program')||'',mapPrograms=programChoices(project?.programs),openPrograms=openProgramChoices(project?.programs),selectedProgram=mapPrograms.some((program:any)=>program.id===requestedProgram)?requestedProgram:'',selectedProgramIsOpen=openPrograms.some((program:any)=>program.id===selectedProgram);
 const mapProject=project&&selectedProgram?{...project,samples:project.samples.filter((r:any)=>r.programId===selectedProgram),collars:project.collars.filter((r:any)=>r.programId===selectedProgram),targets:project.targets.filter((r:any)=>r.programId===selectedProgram)}:project;
 const show=(key:string,r=record)=>{if(!mayNavigate())return;const editing=['correct','collar','metadata'].includes(key);setForm({key,id:r?.recordId,expected:r?versionAt(snapshot.versions,kind,r.recordId):0,initial:editing?r:undefined});};
 const action=(key:string,label?:string,r=record)=>scope.permissions.includes(geologyActions[key].permission)&&<button key={key} onClick={()=>show(key,r)}>{label||geologyActions[key].title}</button>;
 const changeView=(v:string)=>{if(!mayNavigate())return;setForm(null);const path=`/ops/${offlineMode?'field':'geology'}?scope=${scope.id}&view=${v}`;if(offlineMode)window.history.pushState(null,'',path);else router.push(path);};
 const resourceRecords=(rows:any[]=[])=>rows.map(r=>({...r,id:r.recordId,reference:r.id||r.name||r.certificate||r.reference}));
 const resources:Record<string,any[]>=project?{files:files||[],samples:resourceRecords(project.samples.filter((s:any)=>!s.archivedAt)),collars:resourceRecords(project.collars.filter((s:any)=>!s.archivedAt)),programs:openPrograms.map((program:any)=>({...program,reference:program.name||program.reference||program.id})),dispatchable:resourceRecords(project.samples.filter((s:any)=>!s.archivedAt&&!project.dispatches.some((d:any)=>d.status!=='cancelled'&&d.sampleRecordIds.includes(s.recordId)))),manifest:resourceRecords(project.samples.filter((s:any)=>record?.sampleRecordIds?.includes(s.recordId))),receiptEvents:(record?.receiptEvents||[]).filter((e:any)=>e.exceptions?.length&&!record.exceptionResolutions?.some((r:any)=>r.eventRecordId===e.recordId)).map((e:any)=>({...e,id:e.recordId,reference:e.reference}))}:{};
 const primary=view==='samples'?'sample':view==='collars'?'collar':view==='dispatches'?'dispatch':view==='lab'?'assay':view==='targets'?'target':view==='map'?'layer':null;
 const download=async(id:string)=>{try{await downloadEvidence(scope.id,id);}catch(e){setIssue((e as Error).message);}};
 return <><Heading title="Exploration" description={`${scopeLabel(scope, development)} · one physical identity from collection through analytical review.`} action={primary&&scope.permissions.includes(geologyActions[primary].permission)&&<button className="ops-primary" disabled={!project} onClick={()=>{if(mayNavigate())setForm({key:primary,initial:selectedProgramIsOpen?{programId:selectedProgram}:undefined});}}>{geologyActions[primary].title}</button>}/><nav className="ops-tabs" aria-label="Geological registers">{views.map(([v,label])=><button key={v} aria-current={view===v?'page':undefined} onClick={()=>changeView(v)}>{label}</button>)}{scope.permissions.includes('work.read')&&<Link href={`/ops/programs?scope=${scope.id}`}>Programs</Link>}</nav>{(issue||error)&&!(local&&!online)&&<Message error>{issue||error}</Message>}{loading&&!project&&<p role="status">Loading shared project…</p>}{!project&&!loading&&<Empty title="Project records are unavailable">{development ? 'Reload to reconnect to this Development workspace.' : <>Reconnect to load this project or <LinkTo area="field">unlock its prepared field pack</LinkTo>.</>}</Empty>}
 {project&&<><div className="ops-context-line">{development?'Development workspace':offlineMode||!online?'Encrypted device copy':'Shared project'} · revision {snapshot.revision} · {project.samples.length} physical samples · {project.collars.length} drillholes</div>
 {form&&<ActionForm key={`${form.key}:${form.id||'new'}`} spec={{...geologyActions[form.key],preview:['csv','layer','migrate','assay'].includes(form.key)}} recordId={form.id} expectedVersion={form.expected||0} initial={form.initial} resources={resources} onClose={()=>setForm(null)} onComplete={()=>setForm(null)}/>}
 {view==='map'&&!form&&<><section className="ops-map-programbar" aria-label="Exploration map work programs"><label>Work program<select value={selectedProgram} onChange={e=>{if(mayNavigate())router.push(`/ops/geology?scope=${scope.id}&view=map${e.target.value?'&program='+e.target.value:''}`);}}><option value="">All project work</option>{mapPrograms.map((program:any)=>{const closed=['completed','cancelled'].includes(String(program.state??program.status??'').toLowerCase());return <option key={program.id} value={program.id}>{program.name||program.reference||program.id}{closed?' · closed':''}</option>;})}</select></label>{scope.permissions.includes('work.write')&&<details className="ops-create-menu"><summary>Create program</summary><div>{[['drilling','Drill campaign'],['sampling','Sampling program'],['mapping','Geological mapping'],['geophysics','Geophysics'],['drone','Drone survey'],['environment','Environmental work'],['general','Other work']].map(([type,label])=><Link key={type} href={`/ops/programs?scope=${scope.id}&action=create&type=${type}`}>{label}</Link>)}</div></details>}{selectedProgram&&scope.permissions.includes('work.read')&&<Link href={`/ops/programs?scope=${scope.id}&item=${selectedProgram}`}>Program plan & tasks →</Link>}</section><SharedMap project={mapProject} userId={context?.userId||pack?.userId||'signed-out'} onOpen={open}/></>}
 {record?<section className="ops-card"><button className="ops-link" onClick={()=>changeView(view)}>← Back to register</button><div className="ops-section-heading"><h2>{record.id||record.name||record.certificate}</h2><Status>{record.archivedAt?'Archived':record.status||record.lifecycle||'Recorded'}</Status></div><Facts record={record} omit={['rawCsv','recordId','collector','importedBy','recordedBy','createdBy']}/>
 {kind==='samples'&&<><h3>Analytical state</h3><p>{record.assayReviewStatus||'Pending'} · physical state: {record.lifecycle}</p><div className="ops-table-scroll"><table><thead><tr><th>Analyte</th><th>Result / qualifier</th><th>Review</th></tr></thead><tbody>{[...new Set([...Object.keys(record.assays||{}),...Object.keys(record.detectionLimits||{}),...Object.keys(record.lowerLimits||{})])].map(a=><tr key={a}><td>{a} · {elementInfo(a).unit}</td><td>{record.assays?.[a]??(record.detectionLimits?.[a]!=null?'< '+record.detectionLimits[a]:record.lowerLimits?.[a]!=null?'> '+record.lowerLimits[a]:'Pending')}</td><td>{record.assayReviewStatus||'Pending'}</td></tr>)}</tbody></table></div><p className="ops-muted">Units follow the reviewed canonical certificate mapping. A qualified result is retained as a bound; it is not an exact grade.</p><div className="ops-actions">{!record.archivedAt&&<>{action('correct')}{action('archive')}</>}</div></>}
 {kind==='collars'&&<><div className="ops-actions">{action('collar','Correct collar / update drilled depth')}</div><h3>Physical intervals</h3><div className="ops-table-scroll"><table><thead><tr><th>Bag</th><th>From, m</th><th>To, m</th><th>Review</th></tr></thead><tbody>{project.samples.filter((s:any)=>s.collarRecordId===record.recordId).map((s:any)=><tr key={s.recordId}><td><button className="ops-link" onClick={()=>open('samples',s.recordId)}>{s.id}</button></td><td>{s.from}</td><td>{s.to}</td><td>{s.assayReviewStatus||'Pending'}</td></tr>)}</tbody></table></div><h3>Downhole logs & surveys</h3>{['geology','surveys'].map(k=><details key={k}><summary>{k} · {project[k].filter((r:any)=>r.holeId===record.id||r.collarRecordId===record.recordId).length} records</summary>{project[k].filter((r:any)=>r.holeId===record.id||r.collarRecordId===record.recordId).map((r:any)=><Facts key={r.recordId} record={r}/>)}</details>)}</>}
 {kind==='dispatches'&&<><h3>Physical manifest</h3><ul>{project.samples.filter((s:any)=>record.sampleRecordIds.includes(s.recordId)).map((s:any)=><li key={s.recordId}><button className="ops-link" onClick={()=>open('samples',s.recordId)}>{s.id}</button> · {record.receivedRecordIds?.includes(s.recordId)?'Received':'Receipt outstanding'}</li>)}</ul><div className="ops-actions">{record.status==='prepared'&&action('ship')}{record.status!=='prepared'&&action('receipt')}{record.receiptEvents?.some((e:any)=>e.exceptions?.length)&&action('receiptException')}<button onClick={()=>downloadBlob(`MineralX-${record.id}-manifest.csv`,rowsToCsv(project.samples.filter((s:any)=>record.sampleRecordIds.includes(s.recordId)).map((s:any)=>({sample:s.id,method:s.sampleType,qaqc:s.qaqcType,laboratory:record.laboratory,dispatch:record.id})),['sample','method','qaqc','laboratory','dispatch']),'text/csv')}>Download manifest</button></div>{record.receiptEvents?.map((e:any)=><article key={e.recordId}><h3>Receipt {e.reference}</h3>{e.exceptions?.map((x:any,i:number)=><p key={i}>{x.sampleId} · {x.reason}</p>)}<p>{record.exceptionResolutions?.find((r:any)=>r.eventRecordId===e.recordId)?.reason}</p></article>)}</>}
 {kind==='assayBatches'&&<><div className="ops-actions">{record.sourceFileId&&<button onClick={()=>download(record.sourceFileId)}>Original certificate</button>}{record.status!=='released'&&action('release')}{action('hold')}</div>{record.issues?.length>0&&<Message error>{record.issues.join(' ')}</Message>}<p className="ops-muted">Check standards, blanks, duplicates, receipt identity and the project protocol before release. The app does not invent a universal QA/QC threshold.</p><div className="ops-table-scroll"><table><thead><tr><th>Sample</th><th>Result as parsed</th><th>Exceptions</th></tr></thead><tbody>{record.results?.map((r:any,i:number)=><tr key={i}><td>{r.sampleId||r.id||project.samples.find((s:any)=>s.recordId===r.sampleRecordId)?.id}</td><td><pre>{JSON.stringify(r.assays||r.values||r,null,2)}</pre></td><td>{(r.issues||[]).join(' ')}</td></tr>)}</tbody></table></div>{record.rawCsv&&<details><summary>Retained source text</summary><pre>{record.rawCsv}</pre></details>}</>}
 {kind==='spatialLayers'&&<><p>Original source SHA-256: {record.source?.sha256||'Legacy source — revalidation required'}</p><div className="ops-actions">{record.source?.fileId&&<button onClick={()=>download(record.source.fileId)}>Download original source</button>}<button onClick={()=>downloadBlob(`${record.name||'Geology'}.geojson`,JSON.stringify(record.data),'application/geo+json')}>Export GeoJSON</button>{record.archivedAt?action('restoreLayer'):action('archiveLayer')}</div></>}
 {kind==='targets'&&<>{action('linkTarget')}<p>Linked field samples: {(record.linkedSampleIds||[]).join(', ')||'None yet'}</p></>}
 <details><summary>Record identity & provenance</summary><p>{record.recordId} · shared version {versionAt(snapshot.versions,kind,record.recordId)}</p><pre>{JSON.stringify(Object.fromEntries(Object.entries(record).filter(([k])=>['audit','assayHistory','history','source','legacyReviewHistory'].includes(k))),null,2)}</pre></details></section>:
 <section className="ops-card"><div className="ops-table-tools"><label>Find a record<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Identifier, reference or state"/></label><label className="ops-inline-check"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>Include archived</label></div>{(project[kind]||[]).length?<div className="ops-table-scroll"><table><thead><tr><th>Identity / reference</th><th>Physical state / type</th><th>Analytical review</th><th>Open</th></tr></thead><tbody>{(project[kind]||[]).filter((r:any)=>(archived||!r.archivedAt)&&(!filter||[r.id,r.name,r.certificate,r.status,r.lifecycle].some(v=>String(v||'').toLowerCase().includes(filter.toLowerCase())))).map((r:any)=><tr key={r.recordId}><td>{r.id||r.name||r.certificate}<small className="ops-block">{r.date||r.laboratory||''}</small></td><td><Status>{r.archivedAt?'Archived':r.lifecycle||r.status||r.method||'Recorded'}</Status></td><td>{r.assayReviewStatus||(['samples','assayBatches'].includes(kind)?r.status||'Pending':'—')}</td><td><button className="ops-link" onClick={()=>open(kind,r.recordId)}>Open <span className="ops-sr-only">{r.id||r.name||r.certificate}</span></button></td></tr>)}</tbody></table></div>:<Empty title="No records in this register">Capture the actual field observation or stage the original source. No example records have been added to your project.</Empty>}</section>}
 <section className="ops-card"><h2>Project preparation & imports</h2><div className="ops-actions">{!development&&<LinkTo area="field">Prepare encrypted field pack</LinkTo>}{action('csv',undefined,null)}{action('migrate',undefined,null)}</div><p className="ops-muted">Review the source preview before importing. Migration requires an empty shared destination.</p>{!context?.capabilities.sharedGeology&&!context?.capabilities.development&&!offlineMode&&<Message>Shared publication awaits activation of the private evidence service.</Message>}</section>
 </>}</>;
}
