'use client';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {useOperations} from './OperationsProvider';
import {Heading,Empty,Message,Quantity,useResource,Status} from './primitives';
import Plant from './Plant';
export default function Gold(){
 const {scope}=useOperations(),q=useSearchParams(),{data,error}=useResource(scope?.permissions.includes('gold.read')?`register?scope=${scope.id}&kind=lots`:null);
 if(!scope||scope.kind!=='facility')return <><Heading title="Gold"/><Empty title="Choose a processing facility">Gold lots and custody belong to the facility that handles the material.</Empty></>;
 if(q.get('view')||q.get('item')||q.get('action'))return <Plant asGold/>;
 return <><Heading title="Gold" description="Start with the actual clean-up. Follow each physical lot through evidence, review and handover." action={scope.permissions.includes('gold.capture')&&<Link className="ops-primary" href={`/ops/gold?scope=${scope.id}&view=lots&action=cleanup`}>Record a clean-up</Link>}/>{error&&<Message error>{error}</Message>}
 <section className="ops-card"><h2>Where to start</h2><div className="ops-launch-grid">{[['lots','1 · Clean-up & evidence','Record the physical lot, weigh it and attach the product assay.'],['production','2 · Review & production','Independently verify the measurement and recognition point.'],['custody','3 · Handover','The receiving holder acknowledges the actual movement.'],['periods','4 · Reconcile & close','Preserve independent measurements and account revisions.']].map(([v,t,d])=><Link key={v} href={`/ops/gold?scope=${scope.id}&view=${v}`}><h3>{t}</h3><p>{d}</p></Link>)}</div><p className="ops-muted">Custody can happen while an assay is pending. This sequence explains the work; it does not force false observations or complete unrelated stages.</p></section>
 <section className="ops-card"><div className="ops-section-heading"><h2>Physical lots needing attention</h2><Link href={`/ops/gold?scope=${scope.id}&view=lots`}>All lots →</Link></div>{data?.rows?.map((r:any)=><Link className="ops-task-line" key={r.id} href={`/ops/gold?scope=${scope.id}&view=lots&item=${r.id}`}><span><strong>{r.reference}</strong><small>{r.form.replaceAll('_',' ')} · actual output {r.produced_at}</small></span><Status>{r.review_state==='verified'?'Open next action':r.review_state}</Status></Link>)}{data?.rows?.length===0&&<Empty title="No clean-ups recorded">Record the run in Plant first. Create a gold lot when physical output is collected — not after every shift by assumption.</Empty>}{data?.next&&<p>First 100 lots shown. Open All lots for the remaining pages.</p>}</section>
 <div className="ops-actions"><Link href={`/ops/plant?scope=${scope.id}&view=runs`}>Processing runs</Link>{scope.permissions.includes('commercial.read')&&<><Link href={`/ops/gold?scope=${scope.id}&view=allocations`}>Ownership allocations</Link><Link href={`/ops/gold?scope=${scope.id}&view=settlements`}>Refinery / settlement</Link></>}<Link href={`/ops/reports?scope=${scope.id}`}>Reports & closed accounts</Link></div></>;
}
