'use client';
import React,{useState} from 'react';import Link from 'next/link';
import {ProgramCards,WorkflowEditor,WorkflowState,useWorkflow} from './Workflow';
import {mayNavigate} from './navigation';
import {localDay,taskDue,blockers} from '@/lib/ops/workflow-model';
import {useOperations} from './OperationsProvider';import {Heading,Message,Quantity,LinkTo,Empty,useResource} from './primitives';
function OperationalSummary(){const {scope,context}=useOperations(),{data,error,loading}=useResource(scope?`dashboard?scope=${scope.id}`:null);
 if(!scope)return <><Heading title="Your work" description="No operational workspace is assigned yet."/><Empty title="Access is not a role approval">An administrator can create the project/facility and assign named responsibilities. Existing production records have not been moved.</Empty>{context?.organisations.some(o=>o.admin)&&<LinkTo area="admin">Open access & settings</LinkTo>}</>;
 return <><Heading title={scope.name} description="What needs attention, and the records behind it." action={scope.kind==='project'?<LinkTo area="geology" params="action=sample">Collect a sample →</LinkTo>:<LinkTo area="plant" params="action=run">Record a processing run →</LinkTo>}/>{error&&<Message error>{error}</Message>}{loading&&<p role="status">Loading the current account…</p>}
 {data&&<><div className="ops-kpis">{data.gold&&<LinkTo area="gold" params="view=production"><span>Confirmed fine gold · last 30 days</span><strong><Quantity value={data.gold.confirmed_fine_au_g} missing={data.gold.confirmed_lots===0?'No production recognised':'Unrecorded'}/></strong><small>{data.gold.confirmed_lots} recognised lots · source-linked</small></LinkTo>}{data.pending&&<LinkTo area="gold" params="view=lots"><span>Output awaiting recognition</span><strong>{data.pending.lots} <small>lots</small></strong><small>{data.pending.unweighed} still need a weight observation</small></LinkTo>}{data.processing&&<LinkTo area="plant" params="view=runs"><span>Dry-basis feed · last 30 days</span><strong><Quantity value={data.processing.dry_t} unit="t"/></strong><small>{data.processing.basis_incomplete} feed entries lack a complete dry basis</small></LinkTo>}{data.geology&&<><LinkTo area="geology" params="view=samples"><span>Physical samples</span><strong>{data.geology.samples}</strong><small>One register from collection to analytical review</small></LinkTo><LinkTo area="geology" params="view=lab"><span>Laboratory exceptions</span><strong>{data.geology.receiptExceptions}</strong><small>Receipts requiring a decision</small></LinkTo></>}<LinkTo area="work"><span>Assigned / open actions</span><strong>{data.openActions}</strong><small>Specific handovers, not a second task system</small></LinkTo></div>
 <section className="ops-card"><div className="ops-section-heading"><h2>Continue the work</h2><small>As of {new Date(data.asOf).toLocaleString('en-AU',{timeZone:scope.timezone})} · {scope.timezone}</small></div><div className="ops-work-links">{data.processing&&<><LinkTo area="plant" params="view=runs">{data.processing.drafts} run drafts to complete <span>→</span></LinkTo><LinkTo area="plant" params="view=runs">{data.processing.submitted} submitted runs <span>→</span></LinkTo></>}{data.geology&&<LinkTo area="geology" params="view=lab">{data.geology.stagedCertificates} certificates awaiting review <span>→</span></LinkTo>}{data.pending&&<LinkTo area="gold" params="view=lots">Review physical output and missing evidence <span>→</span></LinkTo>}<LinkTo area="work">Open operational handovers <span>→</span></LinkTo></div></section>
 {data.gold&&<section className="ops-card"><h2>Production, not estimates</h2><p>Fine gold is derived from a selected measured mass and accepted assay. Purity is not recovery. Process transformations and custody movements are not new production.</p><p className="ops-muted">{data.recoveryNote}</p></section>}</>}
 <section className="ops-card"><h2>One record, fewer handovers</h2><p>Record observations where they happen. The same records feed review queues, inventory and reports; no separate dashboard entry is required.</p><div className="ops-actions"><LinkTo area="files">Procedures & source evidence</LinkTo><LinkTo area="field">Prepare for offline work</LinkTo><LinkTo area="reports">Reporting & closed accounts</LinkTo></div></section></>;
}

export default function Home(){
 const {scope,context}=useOperations(),{data,error,loading}=useWorkflow(),[editor,setEditor]=useState<string|null>(null);
 if(!scope)return <OperationalSummary/>;
 const today=localDay(scope.timezone),people=data?.people||[],mine=people.filter((p:any)=>p.user_id===context?.userId).map((p:any)=>p.id),tasks=(data?.tasks||[]).filter((t:any)=>!['resolved','cancelled'].includes(t.status)),myTasks=tasks.filter((t:any)=>mine.includes(t.responsible_id)||t.assigned_to===context?.userId),due=tasks.filter((t:any)=>taskDue(t,scope.timezone)&&String(taskDue(t,scope.timezone))<=today),blocked=tasks.filter((t:any)=>t.status==='blocked'||blockers(t,data).length);
 return <><Heading title={scope.name} description="Plan the work here. Continue it in the field, plant or gold register — without entering it twice." action={scope.permissions.includes('work.write')&&<div className="ops-actions"><button className="ops-primary" disabled={!data} onClick={()=>{if(mayNavigate())setEditor('program');}}>Create work program</button><button disabled={!data} onClick={()=>{if(mayNavigate())setEditor('task');}}>Create task</button></div>}/><WorkflowState data={data} error={error} loading={loading}/>
 {editor&&data&&<WorkflowEditor key={editor} kind={editor} data={data} initial={editor==='program'?{type:scope.kind==='project'?'drilling':'processing'}:{}} onClose={()=>setEditor(null)}/>}
 {data&&!editor&&<><div className="ops-home-grid"><section className="ops-card"><div className="ops-section-heading"><h2>My next actions</h2><Link href={`/ops/work?scope=${scope.id}`}>All work →</Link></div>{(myTasks.length?myTasks:tasks.filter((t:any)=>!t.responsible_id)).slice(0,5).map((t:any)=><Link className="ops-task-line" key={t.id} href={`/ops/work?scope=${scope.id}&item=${t.id}`}><span><strong>{t.title}</strong><small>{taskDue(t,scope.timezone)||'No due date'} · {t.responsible_id?'Assigned to you':'Unassigned team work'}</small></span><span>→</span></Link>)}{!myTasks.length&&<p className="ops-muted">No tasks linked to your account. Assign planning personnel in <Link href={`/ops/work?scope=${scope.id}&view=people`}>People & workload</Link>; this never grants account access.</p>}</section>
 <section className="ops-card"><h2>Needs attention</h2><Link className="ops-task-line" href={`/ops/work?scope=${scope.id}&filter=Due`}><strong>{due.length} due / overdue</strong><span>→</span></Link><Link className="ops-task-line" href={`/ops/work?scope=${scope.id}&filter=Blocked`}><strong>{blocked.length} blocked</strong><span>→</span></Link><Link className="ops-task-line" href={`/ops/work?scope=${scope.id}&filter=Unassigned`}><strong>{tasks.filter((t:any)=>!t.responsible_id&&!t.assigned_to).length} unassigned</strong><span>→</span></Link><div className="ops-actions">{scope.kind==='project'?<Link href={`/ops/geology?scope=${scope.id}&view=map`}>Open Geology Globe</Link>:<><Link href={`/ops/plant?scope=${scope.id}`}>Plant & engineering</Link><Link href={`/ops/gold?scope=${scope.id}`}>Gold next actions</Link></>}</div></section></div>
 <section className="ops-section-heading"><h2>Active programs</h2><Link href={`/ops/programs?scope=${scope.id}`}>All programs →</Link></section><ProgramCards data={data} scopeId={scope.id} limit={6}/>
 <section className="ops-card"><h2>Coming up</h2><p className="ops-muted">Next 14 days · {scope.timezone}. Dates stay explicitly planned until observations establish completion.</p>{tasks.filter((t:any)=>{const d=taskDue(t,scope.timezone);return d&&d>=today&&d<=localDay(scope.timezone,new Date(Date.now()+14*864e5));}).sort((a:any,b:any)=>(taskDue(a,scope.timezone)||'').localeCompare(taskDue(b,scope.timezone)||'')).slice(0,8).map((t:any)=><Link key={t.id} className="ops-task-line" href={`/ops/work?scope=${scope.id}&item=${t.id}`}><span>{t.title}</span><span>{taskDue(t,scope.timezone)}</span></Link>)}</section></>}
 <details className="ops-card"><summary>Operational totals & source records</summary><OperationalSummary/></details>
 <details className="ops-card"><summary>Start here — how the suite fits together</summary><p>Create a program to plan a campaign or project; use a task for a single action. Assign people and dates, then capture actual work in Geology or Plant. Gold records follow physical clean-ups, not forecasts. Each record has its own next action and source history.</p><p>Planning personnel do not create login accounts. Development mode stays on this browser; named shared work requires the commissioned backend. Download a backup before changing devices.</p></details></>;
}
