'use client';
import React from 'react';import {useOperations} from './OperationsProvider';import {Heading,Message,Quantity,LinkTo,Empty,useResource} from './primitives';
export default function Home(){const {scope,context}=useOperations(),{data,error,loading}=useResource(scope?`dashboard?scope=${scope.id}`:null);
 if(!scope)return <><Heading title="Your work" description="No operational workspace is assigned yet."/><Empty title="Access is not a role approval">An administrator can create the project/facility and assign named responsibilities. Existing production records have not been moved.</Empty>{context?.organisations.some(o=>o.admin)&&<LinkTo area="admin">Open access & settings</LinkTo>}</>;
 return <><Heading title={scope.name} description="What needs attention, and the records behind it." action={scope.kind==='project'?<LinkTo area="geology" params="action=sample">Collect a sample →</LinkTo>:<LinkTo area="plant" params="action=run">Record a processing run →</LinkTo>}/>{error&&<Message error>{error}</Message>}{loading&&<p role="status">Loading the current account…</p>}
 {data&&<><div className="ops-kpis">{data.gold&&<LinkTo area="plant" params="view=production"><span>Confirmed fine gold · last 30 days</span><strong><Quantity value={data.gold.confirmed_fine_au_g} missing={data.gold.confirmed_lots===0?'No production recognised':'Unrecorded'}/></strong><small>{data.gold.confirmed_lots} recognised lots · source-linked</small></LinkTo>}{data.pending&&<LinkTo area="plant" params="view=lots"><span>Output awaiting recognition</span><strong>{data.pending.lots} <small>lots</small></strong><small>{data.pending.unweighed} still need a weight observation</small></LinkTo>}{data.processing&&<LinkTo area="plant" params="view=runs"><span>Dry-basis feed · last 30 days</span><strong><Quantity value={data.processing.dry_t} unit="t"/></strong><small>{data.processing.basis_incomplete} feed entries lack a complete dry basis</small></LinkTo>}{data.geology&&<><LinkTo area="geology" params="view=samples"><span>Physical samples</span><strong>{data.geology.samples}</strong><small>One register from collection to analytical review</small></LinkTo><LinkTo area="geology" params="view=lab"><span>Laboratory exceptions</span><strong>{data.geology.receiptExceptions}</strong><small>Receipts requiring a decision</small></LinkTo></>}<LinkTo area="work"><span>Assigned / open actions</span><strong>{data.openActions}</strong><small>Specific handovers, not a second task system</small></LinkTo></div>
 <section className="ops-card"><div className="ops-section-heading"><h2>Continue the work</h2><small>As of {new Date(data.asOf).toLocaleString('en-AU',{timeZone:scope.timezone})} · {scope.timezone}</small></div><div className="ops-work-links">{data.processing&&<><LinkTo area="plant" params="view=runs">{data.processing.drafts} run drafts to complete <span>→</span></LinkTo><LinkTo area="plant" params="view=runs">{data.processing.submitted} submitted runs <span>→</span></LinkTo></>}{data.geology&&<LinkTo area="geology" params="view=lab">{data.geology.stagedCertificates} certificates awaiting review <span>→</span></LinkTo>}{data.pending&&<LinkTo area="plant" params="view=lots">Review physical output and missing evidence <span>→</span></LinkTo>}<LinkTo area="work">Open operational handovers <span>→</span></LinkTo></div></section>
 {data.gold&&<section className="ops-card"><h2>Production, not estimates</h2><p>Fine gold is derived from a selected measured mass and accepted assay. Purity is not recovery. Process transformations and custody movements are not new production.</p><p className="ops-muted">{data.recoveryNote}</p></section>}</>}
 <section className="ops-card"><h2>One record, fewer handovers</h2><p>Record observations where they happen. The same records feed review queues, inventory and reports; no separate dashboard entry is required.</p><div className="ops-actions"><LinkTo area="files">Procedures & source evidence</LinkTo><LinkTo area="field">Prepare for offline work</LinkTo><LinkTo area="reports">Reporting & closed accounts</LinkTo></div></section></>;
}
