'use client';
import {mayNavigate} from './navigation';
import React,{useState} from 'react';
import Link from 'next/link';import {usePathname} from 'next/navigation';
import {useOperations} from './OperationsProvider';import {Message,Status} from './primitives';import {api,downloadBlob} from '@/lib/ops/client';import {OPS_RELEASE} from '@/lib/ops/contracts';
import DevelopmentTools from './DevelopmentTools';
const navigation=[['','Home'],['programs','Programs'],['geology','Geology'],['pit','Pits & stockpiles'],['plant','Plant'],['gold','Gold'],['work','Work'],['reports','Reports']];
export default function OperationsShell({children}:{children:React.ReactNode}){
 const {development,context,scope,loading,failure,online,offlineMode,pack,saveState,syncing,sync,selectScope,refresh,exportVault}=useOperations();const path=usePathname();const [query,setQuery]=useState(''),[matches,setMatches]=useState<any[]|null>(null),[error,setError]=useState(''),[menu,setMenu]=useState(false);
 if(path.startsWith('/ops/auth/'))return <main className="ops-shell ops-field-unlock">{children}</main>;
 if(path==='/ops/login'||!context&&(path==='/ops/field'||path==='/ops/account'))return <main className="ops-shell ops-field-unlock">{children}</main>;
 if(loading&&!context)return <main className="ops-shell ops-loading" id="main-content"><h1>MineralX Operations</h1><p role="status">{development?'Opening the development workspace on this device…':'Checking your named account and assigned workspaces…'}</p></main>;
 if(!context)return <main className="ops-shell ops-entry" id="main-content"><p className="ops-eyebrow">MineralX / staff portal</p><h1>One place for the work.</h1><p>Geology, processing and accountable gold records.</p>{failure&&<Message error>{failure.message}</Message>}{development&&<p>Development mode does not need a login. Your existing records have not been erased. Close another development tab or retry loading.</p>}<div className="ops-actions"><a className="ops-primary" href="/ops/login">Staff sign in</a><Link href="/ops/field">Unlock offline field records</Link><button onClick={()=>{if(mayNavigate())void refresh();}}>Check access again</button></div><hr/><p>Existing work remains available:</p><div className="ops-actions"><Link href="/gic">Existing processing register</Link><Link href="/mineralx">Local geology & migration export</Link><Link href="/plant">Public plant plan</Link></div></main>;
 const href=(area:string)=>{
  const kind=area==='geology'?'project':['plant','gold'].includes(area)?'facility':null;
  const permission=area==='geology'?'geo.read':area==='gold'?'gold.read':'plant.read';
  const target=kind&&(!scope||scope.kind!==kind||!scope.permissions.includes(permission))?context.scopes.find(s=>s.kind===kind&&s.permissions.includes(permission)):scope;
  return `/ops${area?'/'+area:''}${target?'?scope='+target.id:''}`;
 };
 return <div className="ops-shell"><header className="ops-topbar"><Link href={href('')} className="ops-brand">MINERAL<span>X</span><small>OPERATIONS</small></Link><button className="ops-mobile-menu" aria-expanded={menu} onClick={()=>setMenu(!menu)}>Menu</button><label className="ops-scope"><span>Workspace / site</span><select aria-label="Workspace or site" value={scope?.id||''} onChange={e=>selectScope(e.target.value)}>{context.scopes.map(s=><option key={s.id} value={s.id}>{s.name} · {s.kind}</option>)}</select></label><form className="ops-search" onSubmit={async e=>{e.preventDefault();if(!scope)return;try{setError('');const legacy=await api<any[]>(`search?scope=${scope.id}&q=${encodeURIComponent(query)}`);const work=await api<any>(`workflow?scope=${scope.id}`).catch(()=>null);const term=query.trim().toLowerCase();const extra=[...(work?.programs||[]).filter((p:any)=>String(p.data.name).toLowerCase().includes(term)).map((p:any)=>({id:p.id,kind:'programs',label:p.data.name,status:p.data.state})),...(work?.tasks||[]).filter((t:any)=>t.title.toLowerCase().includes(term)).map((t:any)=>({id:t.id,kind:'work',label:t.title,status:t.status}))];setMatches([...extra,...legacy]);}catch(e){setError((e as Error).message);}}}><label className="ops-sr-only" htmlFor="ops-search">Find a sample, run or lot</label><input id="ops-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find programs, tasks or records" minLength={2}/><button type="submit">Find</button></form>{scope?.permissions.includes('work.write')&&<details className="ops-create-menu"><summary>Create</summary><div><Link href={href('programs')+'&action=create'}>Work program / campaign</Link><Link href={href('work')+'&action=task'}>Task / to-do</Link><Link href={href('work')+'&action=task&kind=handover'}>Handover</Link>{scope.kind==='project'?<Link href={href('geology')+'&action=sample'}>Physical sample</Link>:<><Link href={href('plant')+'&view=runs&action=run'}>Processing run</Link><Link href={href('gold')+'&view=lots&action=cleanup'}>Clean-up / gold lot</Link></>}</div></details>}<a href="/ops/login">{development?'Staff sign-in':'Switch account'}</a>{!development&&<Link href={href('account')}>Account{context.aal==='aal2'?' · verified':''}</Link>}</header>
 <aside className={`ops-sidebar ${menu?'is-open':''}`}><nav aria-label="Operations"><span className="ops-nav-caption">WORKSPACE</span>{navigation.map(([area,label])=><Link key={area} onClick={()=>setMenu(false)} href={href(area)} aria-current={path==='/ops'+(area?'/'+area:'')?'page':undefined}>{label}</Link>)}<div className="ops-nav-utility"><Link href={href('work')+'&view=people'}>People & workload</Link><Link href={href('files')}>Files & procedures</Link><Link href={href('field')}>Field preparation</Link>{development?<Link href={href('admin')}>Development settings</Link>:context.organisations.some(o=>o.admin)&&<Link href={href('admin')}>Access & settings</Link>}<Link href="/gic">Legacy processing register ↗</Link><Link href="/mineralx">Local geology / migration ↗</Link></div></nav><footer><span>Release {OPS_RELEASE}</span><span>{development?'Development · browser-local records':'Named access · source-linked records'}</span></footer></aside>
 <div className="ops-content">{development&&<section className="ops-development-banner" aria-label="Temporary development access"><strong>Temporary development access — no sign-in</strong><p>Work stays in this browser. This is not the production database. Do not enter confidential data. No cloud sync, staff approvals or real custody changes.</p><Link href={href('admin')}>Save development backup</Link><a href="/ops/login">Open protected staff workspace →</a></section>}<div className="ops-connection" aria-live="polite"><Status tone={offlineMode||!online?'warning':'neutral'}>{development?'Development · saved on this device':offlineMode||!online?'Offline · device records only':'Connected to MineralX'}</Status>{saveState&&<span>{saveState}</span>}<button disabled={loading||!online} onClick={()=>{if(mayNavigate())void refresh();}}>Refresh records</button>{pack&&<><span>{pack.outbox.length} pending</span><button disabled={!online||syncing} onClick={()=>sync().catch(e=>setError(e.message))}>{syncing?'Synchronising…':'Sync now'}</button><button onClick={async()=>{const e=await exportVault();if(e)downloadBlob('MineralX-encrypted-field-recovery.json',JSON.stringify(e));}}>Recovery copy</button></>}</div>{failure&&<Message error>{failure.message}</Message>}{error&&<Message error>{error}<button onClick={()=>setError('')}>Dismiss</button></Message>}
 {matches&&<section className="ops-search-results"><h2>Search results</h2><button onClick={()=>setMatches(null)}>Close results</button>{matches.length?matches.map(r=><Link key={r.kind+r.id} href={href(['programs','work'].includes(r.kind)?r.kind:['samples','collars','dispatches','assayBatches'].includes(r.kind)?'geology':['lots','custody','production'].includes(r.kind)?'gold':'plant')+`&view=${r.kind}&item=${r.id}`} onClick={()=>setMatches(null)}>{r.label} <small>{r.kind} · {r.status}</small></Link>):<p>No matching records in this authorised workspace.</p>}</section>}
 <main id="main-content" key={`${context.userId}:${scope?.id||'none'}`}>{development&&(path==='/ops/admin'||path==='/ops/field')?<DevelopmentTools/>:children}</main><footer className="ops-footnote">{scope?.name||'No workspace assigned'} · {scope?.timezone||'Australia/Brisbane'} · {development?'Development workspace only — not production records.':offlineMode?'Not a live authorisation. Queued work is checked again on reconnection.':'Shared records use current account permissions.'}</footer></div></div>;
}
