'use client';
import React,{useState} from 'react';
import Link from 'next/link';import {usePathname} from 'next/navigation';
import {useOperations} from './OperationsProvider';import {Message,Status} from './primitives';import {api,downloadBlob} from '@/lib/ops/client';import {OPS_RELEASE} from '@/lib/ops/contracts';
const navigation=[['','Home'],['geology','Geology'],['plant','Plant & Gold'],['work','Work queue'],['reports','Reports']];
export default function OperationsShell({children}:{children:React.ReactNode}){
 const {context,scope,loading,failure,online,offlineMode,pack,saveState,syncing,sync,selectScope,refresh,exportVault}=useOperations();const path=usePathname();const [query,setQuery]=useState(''),[matches,setMatches]=useState<any[]|null>(null),[error,setError]=useState(''),[menu,setMenu]=useState(false);
 if(loading&&!context)return <main className="ops-shell ops-loading" id="main-content"><h1>MineralX Operations</h1><p role="status">Checking your named account and assigned workspaces…</p></main>;
 if(path==='/ops/login'||!context&&(path==='/ops/field'||path==='/ops/account'))return <main className="ops-shell ops-field-unlock">{children}</main>;
 if(!context)return <main className="ops-shell ops-entry" id="main-content"><p className="ops-eyebrow">MineralX / staff portal</p><h1>One place for the work.</h1><p>Geology, processing and accountable gold records.</p>{failure&&<Message error>{failure.message}</Message>}<div className="ops-actions"><Link className="ops-primary" href="/ops/login">Staff sign in</Link><Link href="/ops/field">Unlock offline field records</Link><button onClick={refresh}>Check access again</button></div><hr/><p>Existing work remains available:</p><div className="ops-actions"><Link href="/gic">Existing processing register</Link><Link href="/mineralx">Local geology & migration export</Link><Link href="/plant">Public plant plan</Link></div></main>;
 const href=(area:string)=>`/ops${area?'/'+area:''}${scope?'?scope='+scope.id:''}`;
 return <div className="ops-shell"><header className="ops-topbar"><Link href={href('')} className="ops-brand">MINERAL<span>X</span><small>OPERATIONS</small></Link><button className="ops-mobile-menu" aria-expanded={menu} onClick={()=>setMenu(!menu)}>Menu</button><label className="ops-scope"><span>Workspace / site</span><select aria-label="Workspace or site" value={scope?.id||''} onChange={e=>selectScope(e.target.value)}>{context.scopes.map(s=><option key={s.id} value={s.id}>{s.name} · {s.kind}</option>)}</select></label><form className="ops-search" onSubmit={async e=>{e.preventDefault();if(!scope)return;try{setError('');setMatches(await api(`search?scope=${scope.id}&q=${encodeURIComponent(query)}`));}catch(e){setError((e as Error).message);}}}><label className="ops-sr-only" htmlFor="ops-search">Find a sample, run or lot</label><input id="ops-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a sample, run or lot" minLength={2}/><button type="submit">Find</button></form><Link href={href('account')}>Account{context.aal==='aal2'?' · verified':''}</Link></header>
 <aside className={`ops-sidebar ${menu?'is-open':''}`}><nav aria-label="Operations"><span className="ops-nav-caption">WORKSPACE</span>{navigation.map(([area,label])=><Link key={area} onClick={()=>setMenu(false)} href={href(area)} aria-current={path==='/ops'+(area?'/'+area:'')?'page':undefined}>{label}</Link>)}<div className="ops-nav-utility"><Link href={href('files')}>Files & procedures</Link><Link href={href('field')}>Field preparation</Link>{context.organisations.some(o=>o.admin)&&<Link href={href('admin')}>Access & settings</Link>}<Link href="/gic">Legacy processing register ↗</Link><Link href="/mineralx">Local geology / migration ↗</Link></div></nav><footer><span>Release {OPS_RELEASE}</span><span>Named access · source-linked records</span></footer></aside>
 <div className="ops-content"><div className="ops-connection" aria-live="polite"><Status tone={offlineMode||!online?'warning':'neutral'}>{offlineMode||!online?'Offline · device records only':'Connected to MineralX'}</Status>{saveState&&<span>{saveState}</span>}{pack&&<><span>{pack.outbox.length} pending</span><button disabled={!online||syncing} onClick={()=>sync().catch(e=>setError(e.message))}>{syncing?'Synchronising…':'Sync now'}</button><button onClick={async()=>{const e=await exportVault();if(e)downloadBlob('MineralX-encrypted-field-recovery.json',JSON.stringify(e));}}>Recovery copy</button></>}</div>{failure&&<Message error>{failure.message}</Message>}{error&&<Message error>{error}<button onClick={()=>setError('')}>Dismiss</button></Message>}
 {matches&&<section className="ops-search-results"><h2>Search results</h2><button onClick={()=>setMatches(null)}>Close results</button>{matches.length?matches.map(r=><Link key={r.kind+r.id} href={href(['samples','collars','dispatches','assayBatches'].includes(r.kind)?'geology':'plant')+`&view=${r.kind}&item=${r.id}`} onClick={()=>setMatches(null)}>{r.label} <small>{r.kind} · {r.status}</small></Link>):<p>No matching records in this authorised workspace.</p>}</section>}
 <main id="main-content" key={`${context.userId}:${scope?.id||'none'}`}>{children}</main><footer className="ops-footnote">{scope?.name||'No workspace assigned'} · {scope?.timezone||'Australia/Brisbane'} · {offlineMode?'Not a live authorisation. Queued work is checked again on reconnection.':'Shared records use current account permissions.'}</footer></div></div>;
}
