'use client';
import GoldJourney from './GoldJourney';
import {mayNavigate} from './navigation';
import React,{useEffect,useState} from 'react';import {useSearchParams,useRouter} from 'next/navigation';
import {useOperations} from './OperationsProvider';import {Heading,Message,Quantity,Status,Register,Empty,useResource,LinkTo} from './primitives';import {api,downloadEvidence} from '@/lib/ops/client';
import ActionForm from './ActionForm';import {actions,type ActionSpec} from './action-specs';
import {processingProgramChoices} from '@/lib/ops/workflow-model';
// Programs are managed in the common Programs workspace. Processing keeps
// only the operational registers where runs and feed observations occur.
const plantViews=[['runs','Runs'],['feed','Feed']];
const goldViews=[['lots','Gold lots'],['custody','Custody'],['periods','Reconciliation'],['production','Production'],['allocations','Ownership'],['settlements','Settlements']];
export function Facts({record,omit=[]}:{record:any;omit?:string[]}){return <dl className="ops-facts">{Object.entries(record||{}).filter(([key,value])=>!omit.includes(key)&&!['id','scope_id','version','created_by','updated_by'].includes(key)&&value!==null&&typeof value!=='object').map(([key,value])=><div key={key}><dt>{key.replaceAll('_',' ')}</dt><dd>{String(value)}</dd></div>)}</dl>;}
export function History({events}:{events:any[]}){return <details className="ops-history"><summary>Record history · {events?.length||0} events</summary><ol>{events?.map(e=><li key={e.seq}><strong>{e.action==='campaign.create'?'processing program created':e.action.replaceAll('.',' ')}</strong><time>{new Date(e.recorded_at).toLocaleString('en-AU')}</time><p>{e.reason||'Recorded transaction'} · revision {e.version}</p><small>Account {e.actor_id}</small></li>)}</ol></details>;}
export function useChoices(extra:any={},includeProcessingPrograms=false){const {scope,revision}=useOperations(),[data,setData]=useState<Record<string,any[]>>({}),[error,setError]=useState('');
 useEffect(()=>{let stopped=false;setData({});setError('');if(!scope)return;const needsProcessingPrograms=includeProcessingPrograms&&scope.permissions.includes('plant.read'),pairs=[['feed','plant.read'],['runs','plant.read'],['lots','gold.read']];
 const requests=pairs.filter(([,p])=>scope.permissions.includes(p)).map(async([kind])=>{let after:string|null=null,rows:any[]=[];do{const page:{rows:any[];next:string|null}=await api(`register?scope=${scope.id}&kind=${kind}${after?'&after='+after:''}`);rows.push(...page.rows);after=page.next;if(rows.length>10000)throw new Error('The selection contains more than 10,000 records; narrow the operational workspace.');}while(after);return [kind,rows] as const;});
 if(needsProcessingPrograms)requests.push(api<any>(`processing-programs?scope=${scope.id}`).then(result=>['processingPrograms',processingProgramChoices(result)] as const));
 Promise.all(requests).then(entries=>{if(stopped)return;setData(d=>({...d,...Object.fromEntries(entries)}));}).catch(e=>{if(!stopped)setError(e.message);});
 api(`directory?scope=${scope.id}`).then(people=>{if(!stopped)setData(d=>({...d,people}));}).catch(()=>{});api(`files?scope=${scope.id}`).then(files=>{if(!stopped)setData(d=>({...d,files}));}).catch(()=>{});
 return()=>{stopped=true;};},[scope,revision,includeProcessingPrograms]);return {resources:{...data,...(includeProcessingPrograms?{processingPrograms:data.processingPrograms||[]}:{}),...extra},error};}
export default function Plant({asGold=false}:{asGold?:boolean}){
 const {scope,context,development}=useOperations(),query=useSearchParams(),router=useRouter();const views=asGold?goldViews:plantViews,requestedView=query.get('view'),view=views.some(([key])=>key===requestedView)?requestedView!:(asGold?'lots':'runs'),item=query.get('item');const [form,setForm]=useState<any>(query.get('action')==='run'?{key:'run'}:query.get('action')==='cleanup'?{key:'cleanup'}:null);
 const {data:detail,error:detailError}=useResource(scope&&item?`detail?scope=${scope.id}&kind=${view}&id=${item}`:null);
 const {resources,error}=useChoices(detail?{weights:detail.weights||[],assays:detail.assays||[]}:{},true);const record=detail?.record;
 if(!scope||scope.kind!=='facility')return <><Heading title={asGold?"Gold":"Processing"}/><Empty title={development?`Opening ${asGold?'Gold':'Processing'}`:'Choose a processing facility'}>{development?`${asGold?'Gold':'Processing'} opens the compatible records in your Development workspace automatically.`:'A geological project is not a processing or gold-accounting boundary. Choose the assigned facility in the workspace selector.'}</Empty></>;
 if(!scope.permissions.includes(asGold?'gold.read':'plant.read'))return <><Heading title={asGold?"Gold":"Processing"}/><Empty title={`${asGold?'Gold':'Processing'} records are not assigned to this role`}>Select an assigned workspace or ask an administrator to review your role.</Empty></>;
 const open=(r:any)=>{if(!mayNavigate())return;setForm(null);router.push(`/ops/${asGold?'gold':'plant'}?scope=${scope.id}&view=${view}&item=${r.id||r.lot_id}`);};
 const show=(key:string)=>{
  if(!mayNavigate())return;
  const child=['weight','assay','allocation','settlement'].includes(key);
  setForm({key,id:child?undefined:record?.id,expected:child&&['allocation','settlement'].includes(key)?0:record?.version||0,initial:key==='run'?{...record,feeds:detail?.feeds||[]}:key==='preparePeriod'&&detail?.lines?.length?{...record,lines:detail.lines}:undefined,extra:child?{lot_id:record?.id}:undefined});
 };
 const button=(key:string,label?:string)=>scope.permissions.includes(actions[key].permission)&&<button key={key} onClick={()=>show(key)}>{label||actions[key].title}</button>;
 const primaryKey=view==='runs'?'run':view==='lots'?'cleanup':view==='feed'?'feed':view==='periods'?'period':null,viewLabel=view;
 return <><Heading title={asGold?"Gold":"Processing"} description="Processing observations, physical material and supported production figures." action={primaryKey&&scope.permissions.includes(actions[primaryKey].permission)?<button className="ops-primary" onClick={()=>{if(mayNavigate())setForm({key:primaryKey});}}>{actions[primaryKey].title}</button>:null}/>
 {view==='lots'&&scope.permissions.includes('gold.custody')&&<div className="ops-actions"><button onClick={()=>{if(mayNavigate())setForm({key:'transformation'});}}>Record pour / transformation</button></div>}
 <nav className="ops-tabs" aria-label={asGold?'Gold registers':'Processing registers'}>{views.filter(([v])=>scope.permissions.includes(['feed','runs'].includes(v)?'plant.read':['allocations','settlements'].includes(v)?'commercial.read':v==='custody'?'gold.custody.read':v==='periods'?'balance.read':'gold.read')).map(([v,label])=><button key={v} aria-current={view===v?'page':undefined} onClick={()=>{if(!mayNavigate())return;setForm(null);router.push(`/ops/${asGold?'gold':'plant'}?scope=${scope.id}&view=${v}`);}}>{label}</button>)}</nav>
 {!asGold&&scope.permissions.includes('gold.read')&&<div className="ops-actions"><span className="ops-muted">When physical product is collected:</span><a href={`/ops/gold?scope=${scope.id}&view=lots&action=cleanup`}>Record clean-up / gold lot</a></div>}
 {(error||detailError)&&<Message error>{error||detailError}</Message>}{form&&<ActionForm key={`${form.key}:${form.id||'new'}`} spec={actions[form.key]} initial={form.initial} recordId={form.id} expectedVersion={form.expected||0} resources={resources} extra={form.extra} onClose={()=>setForm(null)} onComplete={()=>setForm(null)}/>}
 {record?<section className="ops-card"><div className="ops-section-heading"><div><p className="ops-eyebrow">{viewLabel} · revision {record.version||1}</p><h2>{record.reference||record.name||record.id}</h2></div><Status>{record.status||record.review_state||'Recorded'}</Status></div><button className="ops-link" onClick={()=>{if(mayNavigate())router.push(`/ops/${asGold?'gold':'plant'}?scope=${scope.id}&view=${view}`);}}>← Back to register</button>
 {view==='runs'&&<><Facts record={record} omit={['campaign_id']}/>{record.campaign_id&&<p><strong>Processing program:</strong> {resources.processingPrograms?.find((p:any)=>p.id===record.campaign_id)?.name||record.campaign_id}</p>}<h3>Feed measurements</h3>{detail.feeds?.map((f:any)=><p key={f.feed_lot_id}><Quantity value={f.quantity_t} unit="t"/> · {f.basis} · dry basis <Quantity value={f.dry_t} unit="t"/> · {resources.feed?.find((x:any)=>x.id===f.feed_lot_id)?.reference||f.feed_lot_id}</p>)}<div className="ops-actions">{['draft','returned'].includes(record.status)&&<>{button('run','Continue entry')}{button('submitRun')}</>}{record.status==='submitted'&&button('reviewRun')}{['submitted','reviewed'].includes(record.status)&&button('returnRun')}<details><summary>Other actions</summary>{button('voidRun')}</details></div></>}
 {view==='lots'&&<><GoldJourney detail={detail} onAction={show}/><div className="ops-kpis ops-small-kpis"><div><span>Accepted net product</span><strong><Quantity value={detail.weights?.find((w:any)=>w.id===record.active_weight_id)?.net_g}/></strong></div><div><span>Accepted Au</span><strong><Quantity value={detail.assays?.find((a:any)=>a.id===record.active_assay_id)?.au_percent} unit="%" missing="Assay pending"/></strong></div><div><span>Recognised fine Au</span><strong><Quantity value={detail.production?.fine_au_g} missing="Not recognised"/></strong></div></div><Facts record={record} omit={['active_weight_id','active_assay_id','campaign_id']}/>{record.campaign_id&&<p><strong>Processing program:</strong> {resources.processingPrograms?.find((p:any)=>p.id===record.campaign_id)?.name||record.campaign_id}</p>}
 <h3>Weight observations</h3>{detail.weights?.length?<div className="ops-table-scroll"><table><thead><tr><th>Net mass</th><th>Basis / instrument</th><th>Observed</th><th>Evidence</th></tr></thead><tbody>{detail.weights.map((w:any)=><tr key={w.id}><td><Quantity value={w.net_g}/></td><td>{w.basis} · {w.instrument}</td><td>{new Date(w.observed_at).toLocaleString('en-AU',{timeZone:scope.timezone})}</td><td>{w.source_file_id?<button className="ops-link" onClick={()=>downloadEvidence(scope.id,w.source_file_id)}>Open source</button>:'Not attached'}</td></tr>)}</tbody></table></div>:<p>No weight has been recorded. An unknown mass is not zero.</p>}
 <h3>Product assays</h3>{detail.assays?.length?<div className="ops-table-scroll"><table><thead><tr><th>Certificate</th><th>Reported result</th><th>Method</th><th>State</th></tr></thead><tbody>{detail.assays.map((a:any)=><tr key={a.id}><td><button className="ops-link" onClick={()=>downloadEvidence(scope.id,a.source_file_id)}>{a.certificate} · rev {a.certificate_revision}</button></td><td>{a.raw_result}</td><td>{a.method}</td><td>{a.status}</td></tr>)}</tbody></table></div>:<p>Assay pending; fine gold has not been assumed.</p>}
 <details className="ops-card"><summary>All measurement actions / corrections</summary><div className="ops-actions">{button('weight')}{button('assay')}{record.review_state!=='verified'&&button('reviewGold')}{record.review_state==='verified'&&button('recognise')}<details><summary>Custody, hold & commercial</summary><div className="ops-actions">{button('holdGold')}{['unassigned','external'].includes(detail.custody?.status)&&button('receiveGold')}{detail.custody?.status==='held'&&detail.custody.holder_id===context?.userId&&button('transfer')}{button('allocation')}{button('settlement')}</div></details></div></details>
 {detail.custody&&<section><h3>Restricted custody</h3><Facts record={detail.custody}/>{detail.transfers?.map((t:any)=><div className="ops-custody-card" key={t.id}><strong>{t.reference} · {t.status}</strong><p>{t.destination} · seal {t.seal}</p>{['sent','exception'].includes(t.status)&&t.from_holder!==context?.userId&&<div className="ops-actions"><button onClick={()=>setForm({key:'acknowledge',id:t.id,expected:t.version})}>Acknowledge receipt</button><button onClick={()=>setForm({key:'transferException',id:t.id,expected:t.version})}>Record exception</button></div>}</div>)}</section>}
 <h3>Processing provenance</h3>{detail.runs?.map((r:any)=><p key={r.id}>{r.reference} · {r.status}</p>)}{detail.lineage?.length>0&&<p>This lot participates in a documented transformation. Recognising an ancestor and this lot as new production is blocked.</p>}</>}
 {view==='periods'&&<><Facts record={record} omit={['exception_reason']}/><p><strong>Unexplained difference:</strong> <Quantity value={record.difference_g}/></p><p>{record.exception_reason}</p>{detail.lines?.length>0&&<div className="ops-table-scroll"><table><thead><tr><th>Category / source</th><th>Amount</th><th>Measurement basis</th><th>Evidence</th></tr></thead><tbody>{detail.lines.map((l:any)=><tr key={l.id}><td>{l.kind} · {l.label}</td><td><Quantity value={l.amount_g}/></td><td>{l.method}</td><td><button onClick={()=>downloadEvidence(scope.id,l.source_file_id)}>Source</button></td></tr>)}</tbody></table></div>}
 <div className="ops-actions">{record.status==='open'&&button('preparePeriod')}{record.status==='prepared'&&button('reviewPeriod')}{record.status==='reviewed'&&button('closePeriod')}{record.status!=='open'&&button('reopenPeriod')}{record.status==='closed'&&<button onClick={()=>window.print()}>Print closed account / save PDF</button>}</div>{detail.history?.map((h:any)=><details key={h.version}><summary>Preserved closed revision {h.version} · {new Date(h.closed_at).toLocaleString('en-AU')}</summary><Facts record={h.snapshot.period}/><div className="ops-table-scroll"><table><tbody>{h.snapshot.lines?.map((l:any)=><tr key={l.id}><td>{l.kind} · {l.label}</td><td><Quantity value={l.amount_g}/></td><td>{l.method}</td></tr>)}</tbody></table></div></details>)}</>}
 {!['runs','lots','periods'].includes(view)&&<Facts record={record}/>}
 {view==='allocations'&&<><h3>Documented interests</h3><ul>{record.interests?.map((i:any)=><li key={i.owner_reference}>{i.owner_reference} · {i.percent}%</li>)}</ul>{record.status==='recorded'&&button('reviewAllocation')}</>}{view==='settlements'&&record.status==='recorded'&&button('reviewSettlement')}
 <History events={detail.historyEvents||[]}/></section>:
 <Register kind={view} onOpen={view==='custody'||view==='production'?r=>router.push(`/ops/${asGold?'gold':'plant'}?scope=${scope.id}&view=lots&item=${r.lot_id}`):open} columns={view==='runs'?[{key:'reference',label:'Run'},{key:'started_at',label:'Start'},{key:'ended_at',label:'End'},{key:'status',label:'State',render:r=><Status>{r.status}</Status>}]:view==='lots'?[{key:'reference',label:'Gold lot'},{key:'form',label:'Physical form'},{key:'produced_at',label:'Clean-up / output time'},{key:'review_state',label:'Evidence state',render:r=><Status>{r.review_state}</Status>}]:view==='periods'?[{key:'name',label:'Period'},{key:'kind',label:'Boundary'},{key:'difference_g',label:'Difference',render:r=><Quantity value={r.difference_g}/>},{key:'status',label:'State'}]:view==='custody'?[{key:'lot_id',label:'Lot',render:r=>resources.lots?.find((l:any)=>l.id===r.lot_id)?.reference||r.lot_id},{key:'location',label:'Location'},{key:'status',label:'Custody state'}]:view==='production'?[{key:'lot_id',label:'Lot',render:r=>resources.lots?.find((l:any)=>l.id===r.lot_id)?.reference||r.lot_id},{key:'recognized_at',label:'Recognition time'},{key:'net_g',label:'Product',render:r=><Quantity value={r.net_g}/>},{key:'fine_au_g',label:'Fine Au',render:r=><Quantity value={r.fine_au_g}/>}]:view==='allocations'?[{key:'lot_id',label:'Lot',render:r=>resources.lots?.find((l:any)=>l.id===r.lot_id)?.reference||r.lot_id},{key:'basis',label:'Ownership basis'},{key:'status',label:'Review state'}]:view==='settlements'?[{key:'reference',label:'Settlement'},{key:'counterparty',label:'Refinery / buyer'},{key:'payable_amount',label:'Documented amount',render:r=><Quantity value={r.payable_amount} unit={r.currency||''}/>},{key:'status',label:'Review state'}]:view==='feed'?[{key:'reference',label:'Feed lot'},{key:'owner_reference',label:'Owner reference'},{key:'quantity_t',label:'Quantity',render:r=><Quantity value={r.quantity_t} unit="t"/>},{key:'mass_basis',label:'Basis'}]:[{key:'name',label:'Processing program'},{key:'created_at',label:'Recorded'}]}/>}
 </>;
}
