'use client';
import {mayNavigate} from './navigation';
import {useState} from 'react';
import Link from 'next/link';
import {useRouter,useSearchParams} from 'next/navigation';
import {Heading,Empty,Message,Status,useResource} from './primitives';
import {useOperations} from './OperationsProvider';
import {useWorkflow,WorkflowEditor,WorkflowState,WorkflowHistory,EvidenceLink} from './Workflow';
import {energySummary,tankBalance,localDay} from '@/lib/ops/workflow-model';
import {zonedTimestamp} from '@/lib/ops/time';
import {downloadBlob} from '@/lib/ops/client';
import {rowsToCsv} from '@/lib/ops/contracts';
import {PlantDashboard} from '@/components/plant/PlantDashboard';
import {plantSchema} from '@/lib/plant/model';
import plan from '@/data/plant-p5.json';
import Plant from './Plant';
import '@/app/plant/plant.css';
const model=plantSchema.parse(plan);
const legacy=['runs','feed','campaigns','lots','custody','periods','production','allocations','settlements'];
export default function PlantWorkspace(){
 const {scope}=useOperations(),query=useSearchParams(),router=useRouter(),view=query.get('view')||(query.get('action')==='run'?'runs':'overview'), {data,error,loading}=useWorkflow(),[editor,setEditor]=useState<any>(null),[selected,setSelected]=useState<any>(null);
 const tabs=[['overview','Overview'],['engineering','Engineering'],['runs','Processing'],['assets','Equipment'],['maintenance','Maintenance'],['energy','Energy'],['spares','Critical spares']];
 if(!scope||scope.kind!=='facility')return <><Heading title="Plant"/><Empty title="Choose a processing facility">A geological project is not a plant-operating boundary. Select the facility in the header.</Empty></>;
 if(!scope.permissions.includes('plant.read'))return <Empty title="Plant access is not assigned">Use the workspaces available to your role.</Empty>;
 const navigation=<nav className="ops-tabs" aria-label="Plant workspace">{tabs.map(([key,label])=><Link key={key} href={`/ops/plant?scope=${scope.id}&view=${key}`} aria-current={view===key?'page':undefined}>{label}</Link>)}</nav>;
 if(legacy.includes(view))return <>{navigation}<Plant/></>;
 const write=scope.permissions.includes('plant.capture');const edit=(kind:string,record?:any,initial?:any)=>{if(!mayNavigate())return;setSelected(null);setEditor({kind,record,initial});};
 return <><Heading title="Plant" description="Engineering reference, equipment, processing and energy — connected to the work plan."/>{navigation}<WorkflowState data={data} error={error} loading={loading}/>
 {editor&&data&&<WorkflowEditor key={`${editor.kind}:${editor.record?.id||'new'}`} {...editor} data={data} onClose={()=>setEditor(null)}/>}
 {!editor&&view==='overview'&&<><div className="ops-launch-grid">{[['runs','Record processing','Timing, feed and downtime'],['engineering','Open engineering plan','Flows, equipment layout and design decisions'],['energy','Record energy / diesel','Observed fuel, meter intervals and proposed solar'],['maintenance','Plan maintenance','Assign service work and verify completion']].map(([v,title,description])=><Link key={v} className="ops-card" href={`/ops/plant?scope=${scope.id}&view=${v}`}><h2>{title}</h2><p>{description}</p><span>Open →</span></Link>)}</div><section className="ops-card"><h2>Operating basis</h2><p>The P5 plan is the existing engineering reference, not an automatically certified as-built configuration. Approved and commissioned revisions are tracked separately.</p><Link href={`/ops/gold?scope=${scope.id}`}>Clean-ups, gold lots and next actions →</Link></section></>}
 {!editor&&view==='engineering'&&<><div className="ops-section-heading"><h2>Engineering revisions & change decisions</h2>{write&&<button disabled={!data} onClick={()=>edit('engineering')}>Add engineering revision</button>}</div>{data?.engineering.map((r:any)=><section className="ops-card" key={r.id}><h3>{r.title}</h3><p>{r.reference} · <Status>{r.state}</Status></p><p>{r.notes}</p><div className="ops-actions">{r.source_file_id&&<EvidenceLink id={r.source_file_id}/>}<button onClick={()=>setSelected(r)}>History</button>{write&&<button onClick={()=>edit('engineering',r)}>Review / update revision</button>}<Link href={`/ops/work?scope=${scope.id}&action=task&kind=issue&program=${r.program_id||''}`}>Raise linked work</Link></div></section>)}
 <details className="ops-card" open><summary>P5 engineering reference · existing layout</summary><p>This is the preserved engineering dashboard. Private decisions belong in the revision or work records above; no internal notes are sent to the public plant page.</p><div className="plant-app ops-embedded-plant"><PlantDashboard model={model} readOnly/></div></details></>}
 {!editor&&view==='assets'&&<><div className="ops-section-heading"><h2>Equipment & operating condition</h2>{write&&<button className="ops-primary" disabled={!data} onClick={()=>edit('asset')}>Add equipment</button>}</div>{data?.assets.map((a:any)=><section className="ops-card" key={a.id}><h3>{a.code} · {a.name}</h3><div className="ops-actions"><Status>{a.state}</Status><span>{a.kind} · {a.location||'Location not set'}</span><span>{a.capacity??'—'} {a.capacity_unit||''}</span></div><p>{a.model} {a.serial} · Next planned service: {a.service_due||'not set'}</p><p>{a.notes}</p><div className="ops-actions">{write&&<button onClick={()=>edit('asset',a)}>Edit equipment</button>}<Link href={`/ops/work?scope=${scope.id}&action=task&kind=maintenance&asset=${a.id}`}>Request maintenance</Link><button onClick={()=>setSelected(a)}>History</button></div></section>)}{data?.assets.length===0&&<Empty title="Record the equipment actually on site">Add installed assets or clearly label proposed equipment. The reference drawing does not automatically assert that a machine is commissioned.</Empty>}</>}
 {!editor&&view==='maintenance'&&<><Heading title="Maintenance" description="Request → assign and plan → complete the work → independent verification." action={<Link href={`/ops/work?scope=${scope.id}&action=task&kind=maintenance`}>Request maintenance</Link>}/>{data?.tasks.filter((t:any)=>t.kind==='maintenance').map((t:any)=><Link className="ops-card ops-task-line" key={t.id} href={`/ops/work?scope=${scope.id}&item=${t.id}`}><span><strong>{t.title}</strong><small>{data.assets.find((a:any)=>a.id===t.asset_id)?.name||'Asset unassigned'} · {t.due_on||'Due date not set'}</small></span><Status>{t.status==='resolved'&&!t.verified_at?'awaiting verification':t.status}</Status></Link>)}<section className="ops-card"><h3>Service dates</h3>{data?.assets.filter((a:any)=>a.service_due).map((a:any)=><p key={a.id}>{a.code} · {a.service_due} {a.service_due<localDay(scope.timezone)?'· due':''}</p>)}<p>No service interval or condition is assumed from a drawing. Record confirmed manufacturer/service requirements.</p></section></>}
 {!editor&&view==='energy'&&<Energy data={data} onEdit={edit}/>}
 {!editor&&view==='spares'&&<><Heading title="Critical spares" description="Small, source-linked stock register for uptime-critical items." action={write&&<button disabled={!data} onClick={()=>edit('spare')}>Add critical spare</button>}/>{data?.spares.map((s:any)=>{const events=data.spareMoves.filter((m:any)=>m.spare_id===s.id&&!m.void_reason),stock=events.filter((e:any)=>e.kind!=='count').reduce((n:number,e:any)=>n+(e.kind==='use'?-1:1)*Number(e.quantity),0),counts=events.filter((e:any)=>e.kind==='count').sort((a:any,b:any)=>b.occurred_at.localeCompare(a.occurred_at));return <section className="ops-card" key={s.id}><h3>{s.code} · {s.name}</h3><p>{events.length?stock:'Opening stock not recorded'} {s.unit} · {s.location} · Reorder at {s.reorder_at}</p>{stock<=Number(s.reorder_at)&&events.length>0&&<Message>At or below the recorded reorder threshold.</Message>}{counts.length>0&&<p>Last physical count: {counts[0].quantity} {s.unit} on {counts[0].occurred_at}; independent observation, not a balance adjustment.</p>}<div className="ops-actions">{write&&<><button onClick={()=>edit('spareMove',undefined,{spare_id:s.id})}>Record receipt / use / count</button><button onClick={()=>edit('spare',s)}>Edit spare</button></>}<Link href={`/ops/work?scope=${scope.id}&action=task`}>Raise replenishment task</Link></div><details><summary>Stock events / corrections</summary>{data.spareMoves.filter((e:any)=>e.spare_id===s.id).map((e:any)=><div className="ops-task-line" key={e.id}><span>{e.reference} · {e.kind} · {e.quantity} {s.unit} {e.void_reason?'· voided':''}</span>{!e.void_reason&&scope.permissions.includes('plant.review')&&<button onClick={()=>edit('spareVoid',e)}>Void with reason</button>}</div>)}</details></section>;})}</>}
 {selected&&<><button onClick={()=>setSelected(null)}>Close history</button><WorkflowHistory id={selected.id}/></>}
 </>;
}
function Energy({data,onEdit}:{data:any;onEdit:(kind:string,r?:any,initial?:any)=>void}){
 const {scope}=useOperations(),today=localDay(scope!.timezone),[from,setFrom]=useState(today.slice(0,7)+'01'),[to,setTo]=useState(today),[asset,setAsset]=useState(''),[error,setError]=useState('');
 const live=data?.energy||[],write=scope!.permissions.includes('plant.capture'),lo=zonedTimestamp(from+'T00:00:00',scope!.timezone),hi=zonedTimestamp(to+'T23:59:59',scope!.timezone),series=asset?live.filter((r:any)=>r.asset_id===asset):[],summary=energySummary(series,lo,hi),assets=data?.assets||[];
 return <><Heading title="Energy & fuel" description="Start with installed equipment and an opening tank balance. Record observations; keep proposed solar and capacity separate." action={write&&<div className="ops-actions"><button disabled={!data} className="ops-primary" onClick={()=>onEdit('fuel')}>Record diesel movement</button><button disabled={!data} onClick={()=>onEdit('energy')}>Record energy observation</button></div>}/><div className="ops-table-tools"><label>From<input type="date" value={from} onChange={e=>e.target.value&&setFrom(e.target.value)}/></label><label>Through<input type="date" value={to} onChange={e=>e.target.value&&setTo(e.target.value)}/></label><label>Meter / asset<select value={asset} onChange={e=>setAsset(e.target.value)}><option value="">Select one meter series</option>{assets.map((a:any)=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label></div>{from>to&&<Message error>End date must follow the start date.</Message>}
 {asset&&from<=to&&<><div className="ops-kpis">{[['Diesel generation',summary.diesel,'kWh'],['Solar generation',summary.solar,'kWh'],['Grid import',summary.grid,'kWh'],['Metered load',summary.load,'kWh'],['Generator operation',summary.hours,'h']].map(([k,v,u])=><div key={String(k)}><span>{k}</span><strong>{v===null?'Not recorded':Number(v).toLocaleString()} {v===null?'':u}</strong></div>)}</div>{summary.partial>0&&<Message>{summary.partial} observations overlap the chosen dates only partly and are excluded from these interval totals. No prorating was assumed.</Message>}</>}
 {!asset&&<Message>Select a meter series to view measured energy. Generation and load are not added together; nested meters are not assumed to represent total facility consumption.</Message>}
 <section className="ops-card"><h2>Diesel tank balances</h2><p className="ops-muted">Current all-time ledger since the recorded opening, separate from the selected energy period. Dips are independent checks.</p>{assets.filter((a:any)=>a.kind==='tank').map((a:any)=>{const b=tankBalance(a.id,data.fuel);return <div className="ops-task-line" key={a.id}><span><strong>{a.code} · {a.name}</strong><small>Last dip {b.dip?`${b.dip.observed} L · difference ${b.dip.difference??'not established'} L at ${b.dip.at}`:'not recorded'}</small></span><strong>{b.balance===null?'Opening not recorded':b.balance.toLocaleString()+' L'}</strong></div>;})}{!assets.some((a:any)=>a.kind==='tank')&&<p>Add the installed tank in Equipment before recording fuel.</p>}</section>
 <details className="ops-card"><summary>Energy design scenarios / proposed equipment</summary>{assets.filter((a:any)=>a.state==='proposed'&&['solar','battery','generator'].includes(a.kind)).map((a:any)=><p key={a.id}>{a.name} · {a.capacity??'Not rated'} {a.capacity_unit} · {a.notes}</p>)}<p>Rated capacity and proposal estimates do not become measured generation. Use an Energy / solar program for design and installation work.</p><Link href={`/ops/programs?scope=${scope!.id}&action=create&type=energy`}>Create an energy work program</Link></details>
 <section className="ops-card"><h2>Efficiency basis</h2><p>kWh/t, L/t and recovery are not established until the measurement boundary, complete operating period and matched dry-feed denominator are confirmed. Fuel issued to a generator is not automatically fuel consumed in that interval.</p></section>
 <details className="ops-card"><summary>Fuel observations & corrections</summary>{data?.fuel.map((r:any)=><div className="ops-task-line" key={r.id}><span>{r.reference} · {r.kind} · {r.litres} L · {r.occurred_at} {r.void_reason&&'· voided'}</span>{!r.void_reason&&scope!.permissions.includes('plant.review')&&<button onClick={()=>onEdit('fuelVoid',r)}>Void with reason</button>}</div>)}</details>
 <details className="ops-card"><summary>Energy observations & corrections</summary>{live.filter((r:any)=>!asset||r.asset_id===asset).map((r:any)=><div className="ops-task-line" key={r.id}><span>{r.kind} · {r.amount} {r.unit} · {r.started_at} → {r.ended_at}<small>{r.method} {r.void_reason&&'· voided'}</small></span>{!r.void_reason&&scope!.permissions.includes('plant.review')&&<button onClick={()=>onEdit('energyVoid',r)}>Void with reason</button>}</div>)}</details>
 <button disabled={!data?.complete} onClick={()=>downloadBlob('MineralX-energy-observations.csv',rowsToCsv(live,['id','asset_id','kind','started_at','ended_at','amount','unit','method','source_file_id','void_reason']),'text/csv')}>Export energy evidence register</button></>;
}
