'use client';
import {useState} from 'react';import Link from 'next/link';import {useOperations} from './OperationsProvider';import {Heading,Message,Quantity,Empty,useResource,LinkTo} from './primitives';import {downloadBlob} from '@/lib/ops/client';import {localDateTime,zonedTimestamp} from '@/lib/ops/time';
export default function Reports(){const{scope}=useOperations(),[from,setFrom]=useState(()=>new Date(Date.now()-30*864e5).toISOString()),[to,setTo]=useState(()=>new Date().toISOString()),[error,setError]=useState(''),[busy,setBusy]=useState(false);const dashboard=useResource(scope?`dashboard?scope=${scope.id}&from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`:null),d=dashboard.data;
 const exportFile=async(kind:string)=>{if(!scope)return;setBusy(true);setError('');try{const res=await fetch(`/api/ops/export?scope=${scope.id}&kind=${kind}`,{cache:'no-store'});if(!res.ok){const v=await res.json();throw new Error(v.error?.message||'Export was not confirmed');}downloadBlob(`MineralX-${scope.code}-${kind}-${new Date().toISOString().slice(0,10)}.${kind==='geology'?'json':'csv'}`,await res.blob());}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 if(!scope)return <Empty title="Choose a reporting scope">Select the actual assigned project or facility. Separate operations are not silently combined.</Empty>;
 return <><Heading title="Reports" description="Current operations retain provisional work. Closed accounts preserve the exact approved input revisions."/>{(error||dashboard.error)&&<Message error>{error||dashboard.error}</Message>}
 <section className="ops-card"><h2>Current operations</h2><form className="ops-fields" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const a=zonedTimestamp(String(f.get('from')),scope.timezone),b=zonedTimestamp(String(f.get('to')),scope.timezone);if(a>=b)throw new Error('End must follow start.');setFrom(a);setTo(b);setError('');}catch(e){setError((e as Error).message);}}}><label>From (inclusive)<input type="datetime-local" name="from" defaultValue={localDateTime(from,scope.timezone)} required/></label><label>To (exclusive)<input type="datetime-local" name="to" defaultValue={localDateTime(to,scope.timezone)} required/></label><div className="ops-actions"><button>Apply period</button><small>{scope.timezone} · authorised scope only</small></div></form>
 {d&&<><div className="ops-metrics">{d.gold&&<div className="ops-metric"><span>Confirmed fine Au</span><strong><Quantity value={d.gold.confirmed_fine_au_g} missing="Not established"/></strong><small>{d.gold.confirmed_lots} eligible outputs; counted at recognition</small></div>}{d.processing&&<div className="ops-metric"><span>Dry-basis feed</span><strong><Quantity value={d.processing.dry_t} unit="t"/></strong><small>{d.processing.basis_incomplete} entries need a complete basis</small></div>}{d.pending&&<div className="ops-metric"><span>Unrecognised outputs</span><strong>{d.pending.lots} lots</strong><small>Not automatically treated as fine gold</small></div>}<div className="ops-metric"><span>Metallurgical recovery</span><strong>Not established</strong><small>Requires matched representative inputs, outputs and retained material.</small></div></div>
 {!!d.productionBasisIssues&&<Message error>{d.productionBasisIssues} recognised outputs have a held or changed measurement basis. Review lots before relying on current production totals.</Message>}
 {d.trend?.length>0&&<><h3>Daily production</h3><div className="ops-table-scroll"><table><thead><tr><th>Date</th><th>Recognised fine Au, g</th></tr></thead><tbody>{d.trend.map((r:any)=><tr key={r.day}><td>{r.day}</td><td><Quantity value={r.fine_au_g||r.gold_g} missing="Not established"/></td></tr>)}</tbody></table></div></>}
 <p className="ops-muted">As of {d.asOf||d.as_of||'the current database snapshot'} · <LinkTo area="plant" params="view=production">Open contributing production records</LinkTo></p></>}
 </section><section className="ops-card"><h2>Closed accounts</h2><p>Open each period to inspect the approved balance, input versions, amendments and previous closed snapshots. Application rollback never rewinds the operational database.</p><LinkTo area="plant" params="view=periods">Open reconciliation periods →</LinkTo></section>
 <section className="ops-card"><h2>Controlled record exports</h2><p>Exports below include the complete selected register in this workspace, not just the current display page. They are working records, not a certified return or an independent source-file backup.</p><div className="ops-actions">{scope.permissions.includes('report.export')?['runs','production','lots','periods','geology'].filter(k=>k==='geology'?scope.permissions.includes('geo.read'):k==='periods'?scope.permissions.includes('balance.read'):k==='runs'?scope.permissions.includes('plant.read'):scope.permissions.includes('gold.read')).map(k=><button key={k} disabled={busy} onClick={()=>exportFile(k)}>Export {k}</button>):<p>Your account is not assigned export permission.</p>}</div><p><Link href="/gic/annual">Existing GIC annual-return workspace ↗</Link> — its historical records and reporting semantics remain separate during migration.</p></section></>;
}
