'use client';
import {useState} from 'react';import {useRouter,useSearchParams} from 'next/navigation';import Link from 'next/link';
import {authClient,api} from '@/lib/ops/client';import {safeOpsPath} from '@/lib/ops/contracts';import {Message} from './primitives';import {useOperations} from './OperationsProvider';
export default function SignIn(){const router=useRouter(),params=useSearchParams(),{refresh}=useOperations();const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const ready=Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL&&(process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY));
 return <section className="ops-card ops-auth"><p className="ops-eyebrow">MineralX / named staff access</p><h1>Sign in to Operations</h1><p>Use your invited MineralX account. Signing in does not grant access to an unassigned project or site.</p>{!ready&&<Message error>Identity is awaiting configuration. Existing local geology and processing links remain unchanged.</Message>}{params.get('notice')==='link'&&<Message error>This invitation or recovery link could not be verified. Request a fresh link; no access was granted.</Message>}{error&&<Message error>{error}</Message>}{message&&<Message>{message}</Message>}
 <form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const {error}=await authClient().auth.signInWithPassword({email:email.trim(),password});if(error)throw new Error('Sign-in was not accepted. Check your account details or ask your administrator.');setPassword('');try{await api('claim',{});}catch{/* Missing schema is explained by the authenticated context, not treated as new membership. */}await refresh();router.replace(safeOpsPath(params.get('next')));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
 <label>Email<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="ops-primary" disabled={busy||!ready}>{busy?'Checking account…':'Sign in'}</button></form>
 <div className="ops-actions"><button disabled={busy||!ready||!email.includes('@')} onClick={async()=>{setBusy(true);setError('');try{const{error}=await authClient().auth.resetPasswordForEmail(email.trim(),{redirectTo:window.location.origin+'/ops/auth/callback?next=/ops/account'});if(error)throw new Error('Password recovery could not be requested. Try again or contact your administrator.');setMessage('If this account is eligible, a recovery email will be sent. Check the link in the same browser.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Forgot password</button><Link href="/ops/field">Offline field records</Link></div><p><Link href="/mineralx">Existing local geology</Link> · <Link href="/gic">Existing processing register</Link></p></section>;
}
