'use client';
import React,{useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {useRouter,useSearchParams} from 'next/navigation';
import {useOperations} from './OperationsProvider';
import {Heading,Message,Empty,Status,useResource} from './primitives';
import {mayNavigate} from './navigation';
import WorkSchedule from './WorkSchedule';
import ActionForm from './ActionForm';
import {workflowSpecs} from './workflow-specs';
import {resourcesFor,programRows,blockers,localDay,taskDue,taskStates} from '@/lib/ops/workflow-model';
import {api,downloadBlob,downloadEvidence} from '@/lib/ops/client';
import {rowsToCsv} from '@/lib/ops/contracts';

export function useWorkflow(){
 const {scope}=useOperations();return useResource(scope?.permissions.includes('work.read')?`workflow?scope=${scope.id}`:null);
}
export function WorkflowState({data,error,loading}:{data:any;error:string|null;loading:boolean}){
 return <>{loading&&!data&&<p role="status">Loading current programs and assignments…</p>}{error&&<Message error>{error} The existing registers are unchanged. New shared workflows require the reviewed workflow database migration.</Message>}{data?.complete===false&&<Message error>This workspace exceeds the current 10,000-row interactive view. Totals here are incomplete; use a scoped export before reporting.</Message>}</>;
}
export function WorkflowEditor({kind,data,record,initial={},onClose,onComplete}:{kind:string;data:any;record?:any;initial?:any;onClose:()=>void;onComplete?:(r:any)=>void}){
 const {scope,context}=useOperations(),{data:members}=useResource(scope?`directory?scope=${scope.id}`:null),{data:files}=useResource(scope?`files?scope=${scope.id}`:null);
 const [otherTasks,setOtherTasks]=useState<any[]>([]),[includeOther,setIncludeOther]=useState(false),[lookupError,setLookupError]=useState('');
 useEffect(()=>{if(!includeOther||!context||!scope)return;let ignore=false;
 Promise.all(context.scopes.filter(s=>s.id!==scope.id&&s.org_id===scope.org_id&&s.permissions.includes('work.read')).map(async s=>{const result=await api<any>(`workflow?scope=${s.id}`);if(!result.complete)throw new Error('A linked workspace is too large for a complete prerequisite list.');return result.tasks.map((t:any)=>({...t,title:`${s.name} · ${t.title}`}));})).then(rows=>{if(!ignore)setOtherTasks(rows.flat());}).catch(e=>{if(!ignore)setLookupError(e.message);});return()=>{ignore=true;};
 },[includeOther,context,scope]);
 const resources:any={...resourcesFor(data,members||[],otherTasks),files:files||[]};
 for(const d of data?.dependencies||[])if(d.task_id===record?.id&&!resources.predecessors.some((r:any)=>r.id===d.predecessor_id))resources.predecessors.push({id:d.predecessor_id,scope_id:d.predecessor_scope,name:d.title});
 resources.predecessors=resources.predecessors.filter((r:any)=>r.id!==record?.id);resources.packages=resources.packages.filter((r:any)=>r.id!==record?.id);resources.assets=resources.assets.filter((r:any)=>kind!=='asset'||r.id!==record?.id);
 const values={...(kind==='program'?record?.data:record),...(record&&kind==='task'?{dependencyIds:(data.dependencies||[]).filter((d:any)=>d.task_id===record.id).map((d:any)=>d.predecessor_id)}:{}),...initial};
 // Existing record metadata is not a command payload. Only declared editable fields are transmitted.
 const sourceSpec=workflowSpecs[kind],spec={...sourceSpec,fields:sourceSpec.fields.map(f=>f.type==='evidence'&&scope?.kind==='project'&&scope.permissions.includes('files.geo')?{...f,family:'geo'}:f)};const allowed=new Set(spec.fields.map(f=>f.key));const clean=Object.fromEntries(Object.entries(values).filter(([k])=>allowed.has(k)));
 return <>{kind==='task'&&<div className="ops-actions"><label><input type="checkbox" checked={includeOther} onChange={e=>setIncludeOther(e.target.checked)}/> Include prerequisites from other authorised workspaces</label><Link href={`/ops/work?scope=${scope?.id}&view=people`}>Manage planning personnel</Link></div>}{lookupError&&<Message error>{lookupError}</Message>}<ActionForm spec={spec} recordId={record?.id} expectedVersion={record?.version||0} initial={clean} resources={resources} onClose={onClose} onComplete={r=>{if(onComplete)onComplete(r);else onClose();}}/></>;
}
export function ProgramCards({data,limit=100,scopeId}:{data:any;limit?:number;scopeId:string}){
 const programs=programRows(data).filter((p:any)=>!['completed','cancelled'].includes(p.state));
 return programs.length?<div className="ops-program-cards">{programs.slice(0,limit).map((p:any)=>{
  const progress=data.progress?.find((r:any)=>r.id===p.id),tasks=(data.tasks||[]).filter((t:any)=>t.program_id===p.id),open=tasks.filter((t:any)=>!['resolved','cancelled'].includes(t.status)),blocked=open.filter((t:any)=>t.status==='blocked'||blockers(t,data).length);
  return <Link className="ops-card ops-program-card" key={p.id} href={`/ops/programs?scope=${scopeId}&item=${p.id}`}><div className="ops-section-heading"><span className="ops-eyebrow">{data.types?.find((t:any)=>t.key===p.type)?.label||'Work program'}</span><Status>{p.state||'planned'}</Status></div><h3>{p.name}</h3><p>{p.objective||'Add the outcome and the next piece of work.'}</p><p>{data.people?.find((person:any)=>person.id===p.ownerId)?.name||'Owner unassigned'} · {p.plannedEnd||'Finish not planned'}</p><div className="ops-program-progress"><span>{open.length} open tasks</span>{blocked.length>0&&<strong>{blocked.length} blocked</strong>}{progress&&p.type==='drilling'&&<span>{progress.metres} / {p.plannedMetres||'—'} m drilled</span>}</div></Link>;
 })}</div>:<Empty title="No active work programs">Create a drill campaign, site project, plant improvement or general program. The same record follows the work across the suite.</Empty>;
}
export function WorkflowHistory({id}:{id:string}){
 const {scope}=useOperations();const {data,error}=useResource(scope?`workflow-history?scope=${scope.id}&id=${id}`:null);
 return <details className="ops-card"><summary>Record history & stable identity</summary><p className="ops-muted">{id}</p>{error&&<Message error>{error}</Message>}{data?.map((e:any)=><article key={e.seq}><strong>{e.action.replaceAll('.',' · ')} · revision {e.version}</strong><p>{new Date(e.recorded_at).toLocaleString('en-AU',{timeZone:scope?.timezone})} · {e.reason||'Record change'}</p><details><summary>Recorded fields</summary><pre>{JSON.stringify(e.snapshot,null,2)}</pre></details></article>)}</details>;
}
export function Programs({embedded=false}:{embedded?:boolean}){
 const {scope}=useOperations(),query=useSearchParams(),router=useRouter(),{data,error,loading}=useWorkflow();
 const item=query.get(embedded?'program':'item');const [editor,setEditor]=useState<any>(null),[view,setView]=useState('Overview'),[search,setSearch]=useState('');
 useEffect(()=>{if(query.get('action')==='program'||query.get('action')==='create')setEditor({kind:'program',initial:{type:query.get('type')||'general'}});},[query]);
 if(!scope)return <Empty title="Choose a workspace">Programs have an explicit owning project or facility.</Empty>;
 const programs=programRows(data),program=programs.find((p:any)=>p.id===item),raw=data?.programs?.find((p:any)=>p.id===item),tasks=data?.tasks?.filter((t:any)=>t.program_id===item)||[],progress=data?.progress?.find((p:any)=>p.id===item);
 const openEditor=(v:any)=>{if(mayNavigate())setEditor(v);};
 const taskLink=(t:any)=><Link key={t.id} className="ops-task-line" href={`/ops/work?scope=${scope.id}&item=${t.id}`}><span><strong>{t.title}</strong><small>{data.people?.find((p:any)=>p.id===t.responsible_id)?.name||'Unassigned'} · {taskDue(t,scope.timezone)||'No due date'}</small></span><Status>{blockers(t,data).length?'prerequisites outstanding':t.status}</Status></Link>;
 return <><Heading title={program?.name||'Programs'} description={program?.objective||'Plan once. Assign the next action. Follow actual records and close out with evidence.'} action={scope.permissions.includes('work.write')&&<button className="ops-primary" disabled={!data} onClick={()=>openEditor({kind:'program'})}>Create work program</button>}/><WorkflowState data={data} error={error} loading={loading}/>
 {editor&&data&&<WorkflowEditor key={`${editor.kind}:${editor.record?.id||'new'}`} {...editor} data={data} onClose={()=>{setEditor(null);if(query.get('action'))router.replace(`/ops/programs?scope=${scope.id}${item?'&item='+item:''}`);}} onComplete={r=>{setEditor(null);if(editor.kind==='program')router.push(`/ops/programs?scope=${scope.id}&item=${r.id}`);}}/>}
 {!editor&&data&&(program?<><div className="ops-actions"><Link href={`/ops/programs?scope=${scope.id}`}>← All programs</Link><Status>{program.state||'planned'}</Status>{scope.permissions.includes('work.write')&&<><button onClick={()=>openEditor({kind:'program',record:raw})}>Edit program plan</button><button onClick={()=>openEditor({kind:'task',initial:{program_id:program.id}})}>Add task / work package</button></>}{scope.kind==='project'&&<Link href={`/ops/geology?scope=${scope.id}&view=map&program=${program.id}`}>Open in Geology Globe</Link>}</div>
 <nav className="ops-tabs" aria-label="Program panels">{['Overview','Sequence','Records','People & equipment','Files & costs','Activity'].map(v=><button key={v} aria-current={view===v?'page':undefined} onClick={()=>setView(v)}>{v}</button>)}</nav>
 {view==='Overview'&&<><div className="ops-kpis"><div><span>Responsible person</span><strong>{data.people.find((p:any)=>p.id===program.ownerId)?.name||'Unassigned'}</strong></div><div><span>Planned window</span><strong>{program.plannedStart||'—'} → {program.plannedEnd||'—'}</strong></div><div><span>Work remaining</span><strong>{tasks.filter((t:any)=>!['resolved','cancelled'].includes(t.status)).length} tasks</strong></div>{progress&&<div><span>Actual field records</span><strong>{progress.metres} m · {progress.samples} samples</strong><small>{progress.released} with released results</small></div>}</div><section className="ops-card"><h2>Next work</h2>{tasks.filter((t:any)=>!['resolved','cancelled'].includes(t.status)).slice(0,8).map(taskLink)}{!tasks.length&&<p>Add the first task or work package. Operational progress is derived from linked records, not a manually typed percentage.</p>}</section></>}
 {view==='Sequence'&&<><WorkSchedule tasks={tasks}/><section className="ops-card"><h2>Work sequence</h2><p className="ops-muted">Dependencies control readiness. Dates are a plan, not evidence that work occurred.</p>{tasks.sort((a:any,b:any)=>String(a.start_on||'9999').localeCompare(b.start_on||'9999')).map((t:any)=><div key={t.id}>{taskLink(t)}{(data.dependencies||[]).filter((d:any)=>d.task_id===t.id).map((d:any)=><small className="ops-dependency" key={d.predecessor_id}>After: {d.title} · {d.status||'restricted'}</small>)}</div>)}{!tasks.length&&<p>No work sequence recorded.</p>}</section></>}
 {view==='Records'&&<ProgramRecords id={program.id} data={data}/>}
 {view==='People & equipment'&&<section className="ops-card"><h2>Assigned people</h2>{data.people.filter((p:any)=>p.id===program.ownerId||(program.personnelIds||[]).includes(p.id)||tasks.some((t:any)=>t.responsible_id===p.id)).map((p:any)=><p key={p.id}>{p.name} · {p.role||'Contributor'} {!p.active&&'· unavailable'}</p>)}<Link href={`/ops/work?scope=${scope.id}&view=people`}>Manage personnel and workload</Link><h3>Linked equipment</h3>{data.assets.filter((a:any)=>tasks.some((t:any)=>t.asset_id===a.id)).map((a:any)=><p key={a.id}><Link href={`/ops/plant?scope=${scope.id}&view=assets&asset=${a.id}`}>{a.code} · {a.name}</Link></p>)}</section>}
 {view==='Files & costs'&&<section className="ops-card"><h2>Source-linked costs</h2><p>Planning budget: {program.budget||'Not set'} {program.budget?program.currency:''}. Estimates, commitments and actuals are separate; they are not added together as expenditure.</p>{scope.permissions.includes('commercial.write')&&<button onClick={()=>openEditor({kind:'cost',initial:{program_id:program.id}})}>Add cost / commitment</button>}<CostRows rows={data.costs.filter((c:any)=>c.program_id===program.id)} onVoid={r=>openEditor({kind:'costVoid',record:r})}/><h3>Task evidence</h3>{tasks.filter((t:any)=>t.source_file_id).map((t:any)=><EvidenceLink key={t.id} id={t.source_file_id} label={t.title}/>)}<Link href={`/ops/files?scope=${scope.id}`}>Files & controlled procedures</Link></section>}
 {view==='Activity'&&<WorkflowHistory id={program.id}/>}</>:<><label className="ops-filter">Find a program<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Campaign, site work or project"/></label><ProgramCards scopeId={scope.id} data={{...data,programs:data.programs.filter((p:any)=>(p.data.name||'').toLowerCase().includes(search.toLowerCase()))}}/><details className="ops-card"><summary>Completed and cancelled programs</summary>{programs.filter((p:any)=>['completed','cancelled'].includes(p.state)).map((p:any)=><p key={p.id}><Link href={`/ops/programs?scope=${scope.id}&item=${p.id}`}>{p.name}</Link> · {p.state}</p>)}</details></>)}
 </>;
}
export function EvidenceLink({id,label='Open original evidence'}:{id:string;label?:string}){const {scope}=useOperations();const [error,setError]=useState('');return <span><button className="ops-link" onClick={()=>scope&&downloadEvidence(scope.id,id).catch(e=>setError(e.message))}>{label}</button>{error&&<Message error>{error}</Message>}</span>;}
export function CostRows({rows,onVoid}:{rows:any[];onVoid?:(r:any)=>void}){
 const {scope}=useOperations();const groups=new Map<string,number>();rows.filter(r=>!r.void_reason).forEach(r=>{const k=`${r.currency} ${r.kind}`;groups.set(k,(groups.get(k)||0)+Number(r.amount));});
 return <><div className="ops-actions">{[...groups].map(([k,v])=><span key={k}>{k}: {v.toLocaleString('en-AU',{maximumFractionDigits:2})}</span>)}</div>{!rows.length&&<p>No accessible cost records. A blank total is not zero expenditure.</p>}{rows.map(r=><div key={r.id} className="ops-task-line"><span>{r.reference} · {r.kind} · {r.amount} {r.currency} {r.void_reason&&'· voided'}{r.source_file_id&&<EvidenceLink id={r.source_file_id}/>}</span>{!r.void_reason&&onVoid&&scope?.permissions.includes('commercial.write')&&<button onClick={()=>onVoid(r)}>Void with reason</button>}</div>)}</>;
}
function ProgramRecords({id,data}:{id:string;data:any}){
 const {scope}=useOperations();const {data:geo}=useResource(scope?.kind==='project'&&scope.permissions.includes('geo.read')?`geology?scope=${scope.id}`:null);
 const {data:runs}=useResource(scope?.kind==='facility'&&scope.permissions.includes('plant.read')?`register?scope=${scope.id}&kind=runs`:null);
 return <section className="ops-card"><h2>Linked operational records</h2>{scope?.kind==='project'?['targets','collars','samples'].map(kind=><section key={kind}><h3>{kind==='collars'?'Drillholes':kind}</h3>{geo?.project?.[kind]?.filter((r:any)=>r.programId===id).map((r:any)=><p key={r.recordId}><Link href={`/ops/geology?scope=${scope.id}&view=${kind}&item=${r.recordId}`}>{r.name||r.id}</Link> · {r.assayReviewStatus||r.status||'recorded'}</p>)}</section>):runs?.rows?.filter((r:any)=>r.campaign_id===id).map((r:any)=><p key={r.id}><Link href={`/ops/plant?scope=${scope?.id}&view=runs&item=${r.id}`}>{r.reference}</Link> · {r.status}</p>)}<p className="ops-muted">Only explicitly linked records appear. Proximity on a map does not complete a program.</p>{runs?.next&&<Message>More runs exist than the first page. Open the processing register for the full paginated history.</Message>}</section>;
}
export function WorkBoard(){
 const {scope,context}=useOperations(),query=useSearchParams(),router=useRouter(),{data,error,loading}=useWorkflow();
 const [editor,setEditor]=useState<any>(null),[filter,setFilter]=useState(()=>['Active','Mine','Due','Blocked','Handover','Completed','All','Unassigned'].includes(query.get('filter')||'')?query.get('filter')!:'Active'),[layout,setLayout]=useState('List'),[search,setSearch]=useState('');const selected=data?.tasks.find((t:any)=>t.id===query.get('item')),view=query.get('view')||'tasks';
 useEffect(()=>{if(query.get('action')==='task')setEditor({kind:'task',initial:{kind:query.get('kind')||'task',program_id:query.get('program')||'',asset_id:query.get('asset')||''}});},[query]);
 if(!scope)return <Empty title="Choose a workspace">View permitted tasks and assignments.</Empty>;
 const today=localDay(scope.timezone),people=data?.people||[],mine=people.filter((p:any)=>p.user_id===context?.userId).map((p:any)=>p.id),programs=programRows(data);
 const filtered=(data?.tasks||[]).filter((t:any)=>{const finished=['resolved','cancelled'].includes(t.status),due=taskDue(t,scope.timezone);return (!search||t.title.toLowerCase().includes(search.toLowerCase()))&&(filter==='All'||filter==='Completed'?filter==='All'||finished:!finished)&&(filter!=='Mine'||mine.includes(t.responsible_id)||t.assigned_to===context?.userId)&&(filter!=='Due'||due&&due<=today)&&(filter!=='Blocked'||t.status==='blocked'||blockers(t,data).length)&&(filter!=='Handover'||t.kind==='handover')&&(filter!=='Unassigned'||!t.responsible_id&&!t.assigned_to);});
 const show=(v:any)=>{if(mayNavigate())setEditor(v);};const link=(t:any)=><Link key={t.id} className="ops-task-line" href={`/ops/work?scope=${scope.id}&item=${t.id}`}><span><strong>{t.title}</strong><small>{people.find((p:any)=>p.id===t.responsible_id)?.name||'Unassigned'} · {taskDue(t,scope.timezone)||'No due date'} · {t.priority}</small></span><Status>{blockers(t,data).length?'blocked by prerequisite':t.status}</Status></Link>;
 return <><Heading title={view==='people'?'People & workload':'Work'} description="Today’s actions, program work and handovers. Nothing needs to be entered twice." action={scope.permissions.includes('work.write')&&<button className="ops-primary" disabled={!data} onClick={()=>show({kind:view==='people'?'person':'task'})}>{view==='people'?'Add planning personnel':'Create task'}</button>}/><nav className="ops-tabs" aria-label="Work panels">{[['tasks','My work / team'],['people','People & workload']].map(([v,label])=><Link key={v} href={`/ops/work?scope=${scope.id}&view=${v}`} aria-current={view===v?'page':undefined}>{label}</Link>)}</nav><WorkflowState data={data} error={error} loading={loading}/>
 {editor&&data&&<WorkflowEditor key={`${editor.kind}:${editor.record?.id||'new'}`} {...editor} data={data} onClose={()=>{setEditor(null);if(query.get('action'))router.replace(`/ops/work?scope=${scope.id}`);}}/>}
 {!editor&&data&&(view==='people'?<section className="ops-card"><p>Planning names are not user accounts. Linking an existing authorised account enables “Mine”; creating a planning person never grants access.</p>{people.map((p:any)=><article className="ops-person" key={p.id}><div><h3>{p.name}</h3><p>{p.role||'Role not set'} · {p.active?'Available':'Unavailable'} · {p.user_id?'Linked staff account':'Planning identity only'}</p><small>{data.tasks.filter((t:any)=>t.responsible_id===p.id&&!['resolved','cancelled'].includes(t.status)).length} open assignments</small></div>{scope.permissions.includes('work.write')&&<button onClick={()=>show({kind:'person',record:p})}>Edit person</button>}</article>)}</section>:selected?<><section className="ops-card"><Link href={`/ops/work?scope=${scope.id}`}>← Work list</Link><h2>{selected.title}</h2><div className="ops-actions"><Status>{selected.status}</Status><span>{selected.kind} · {selected.priority}</span><span>{people.find((p:any)=>p.id===selected.responsible_id)?.name||'Unassigned'}</span></div>{selected.program_id&&<p><Link href={`/ops/programs?scope=${scope.id}&item=${selected.program_id}`}>{programs.find((p:any)=>p.id===selected.program_id)?.name}</Link></p>}<p>{selected.notes||'No additional instructions.'}</p><p>{selected.outcome}</p>{selected.source_file_id&&<EvidenceLink id={selected.source_file_id}/>}<h3>Prerequisites</h3>{data.dependencies.filter((d:any)=>d.task_id===selected.id).map((d:any)=><p key={d.predecessor_id}>{d.title} · {d.status||'restricted'}</p>)}{!data.dependencies.some((d:any)=>d.task_id===selected.id)&&<p>No prerequisites recorded.</p>}
 <div className="ops-actions">{scope.permissions.includes('work.write')&&<><button onClick={()=>show({kind:'taskState',record:selected,initial:{status:selected.status}})}>Update progress / resolve</button>{!['resolved','cancelled'].includes(selected.status)&&<button onClick={()=>show({kind:'task',record:selected})}>Edit task plan</button>}</>}{selected.kind==='maintenance'&&selected.status==='resolved'&&!selected.verified_at&&scope.permissions.includes('plant.review')&&<button onClick={()=>show({kind:'verify',record:selected})}>Verify maintenance</button>}</div>{selected.kind==='maintenance'&&<p>{selected.verified_at?'Independently verified '+selected.verified_at:'Completion still requires independent supervisor verification.'}</p>}</section><WorkflowHistory id={selected.id}/></>:<><div className="ops-table-tools"><label>Find work<input value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Show<select value={filter} onChange={e=>setFilter(e.target.value)}>{['Active','Mine','Due','Blocked','Handover','Unassigned','Completed','All'].map(v=><option key={v}>{v}</option>)}</select></label><label>View<select value={layout} onChange={e=>setLayout(e.target.value)}>{['List','Board','Schedule'].map(v=><option key={v}>{v}</option>)}</select></label></div>
 {layout==='Schedule'?<WorkSchedule tasks={filtered}/>:layout==='Board'?<div className="ops-board">{['open','ready','in_progress','blocked','on_hold','resolved','cancelled'].map(s=><section className="ops-card" key={s}><h3>{s.replaceAll('_',' ')}</h3>{filtered.filter((t:any)=>t.status===s).map(link)}</section>)}</div>:<section className="ops-card">{layout==='Schedule'&&<p className="ops-muted">Ordered by the due date in {scope.timezone}. Planned windows do not automatically reschedule other tasks.</p>}{filtered.sort((a:any,b:any)=>String(taskDue(a,scope.timezone)||'9999').localeCompare(taskDue(b,scope.timezone)||'9999')).map(link)}{!filtered.length&&<Empty title="No matching work">Create a task, handover or work package, or change the filter.</Empty>}</section>}
 <div className="ops-actions"><button disabled={!data.complete} onClick={()=>downloadBlob('MineralX-work.csv',rowsToCsv(filtered,['id','title','kind','priority','status','responsible_id','start_on','due_on','notes','outcome']),'text/csv')}>Export this work view</button><Link href={`/ops/geology?scope=${scope.id}&view=lab`}>Laboratory review queue</Link><Link href={`/ops/gold?scope=${scope.id}`}>Gold next actions</Link></div></>)}
 </>;
}
