import type {ActionSpec,Field} from './action-specs';
const text=(key:string,label:string,required=true):Field=>({key,label,required});
const select=(key:string,label:string,resource:string,required=false):Field=>({key,label,type:'select',resource,required});
const choices=(key:string,label:string,options:string[],required=true):Field=>({key,label,type:'select',options,required});
const day=(key:string,label:string):Field=>({key,label,type:'date'});
const decimal=(key:string,label:string,required=false):Field=>({key,label,type:'decimal',required});
const note=(key:string,label:string,required=false):Field=>({key,label,type:'textarea',required});
const evidence:Field={key:'source_file_id',label:'Original source / evidence',type:'evidence',family:'plant'};
const whenGeo=(v:any)=>['drilling','sampling'].includes(v.type);
export const workflowSpecs:Record<string,ActionSpec>={
 program:{title:'Plan a work program',action:'program.save',permission:'work.write',button:'Save program',description:'Create the plan once. Home, Geology, Work and the processing campaign use its stable identity.',defaults:{type:'general',state:'planned',method:'rock_chip',personnelIds:[],currency:'AUD'},fields:[text('name','Program name'),select('type','Type of work','types',true),note('objective','Outcome / purpose'),select('ownerId','Responsible person','people'),{key:'personnelIds',label:'Contributors / crew',type:'multi',resource:'people'},day('plannedStart','Planned start'),day('plannedEnd','Planned finish'),choices('state','Program state',['draft','planned','ready','in_progress','blocked','on_hold','completed','cancelled']),{...choices('method','Primary sampling method',['rock_chip','soil','float','rc','diamond_core','other']),when:whenGeo},{...decimal('plannedMetres','Planned drilling, m'),when:v=>v.type==='drilling'},{...decimal('plannedHoles','Planned hole count'),when:v=>v.type==='drilling'},decimal('budget','Planning budget (not actual cost)'),text('currency','Budget currency'),{...note('reason','Plan change / close-out reason'),hint:'Required to close, cancel or reopen a completed program.'}]},
 task:{title:'Plan a task',action:'task.save',permission:'work.write',button:'Save task',description:'A practical next action, with one responsible person. Use a work package to group steps; leave the program blank for a standalone task.',defaults:{kind:'task',priority:'normal',contributors:[],dependencyIds:[]},fields:[text('title','Task / work package title'),choices('kind','Type',['task','package','milestone','maintenance','handover','issue']),select('program_id','Program','programs'),select('parent_id','Work package','packages'),select('responsible_id','Responsible person','people'),{key:'contributors',label:'Other personnel',type:'multi',resource:'people'},day('start_on','Planned start'),day('due_on','Due date'),choices('priority','Priority',['low','normal','high','urgent']),{key:'dependencyIds',label:'Must finish before this work starts',type:'multi',resource:'predecessors'},select('asset_id','Linked equipment','assets'),note('notes','Instructions / handover'),evidence],prepare:(v,r)=>{const {dependencyIds,...rest}=v;return {...rest,dependencies:(dependencyIds||[]).map((id:string)=>({id,scopeId:r.predecessors.find(t=>t.id===id)?.scope_id}))};}},
 taskState:{title:'Update task progress',action:'task.status',permission:'work.write',button:'Save progress',description:'Record what actually changed. Dependencies and incomplete work packages are checked before completion.',fields:[choices('status','Next state',['open','ready','in_progress','blocked','on_hold','resolved','cancelled']),note('outcome','Progress / blocker / completion evidence',true)]},
 verify:{title:'Verify completed maintenance',action:'task.verify',permission:'plant.review',mfa:true,button:'Verify maintenance',description:'A different supervisor confirms the completed work. This is not a replacement for a physical safety inspection or isolation procedure.',fields:[note('reason','Independent verification and evidence',true)]},
 person:{title:'Add planning personnel',action:'person.save',permission:'work.write',button:'Save person',description:'Names used for planning and responsibility only. This does not invite an account or grant permissions.',defaults:{active:true},fields:[text('name','Person / crew name'),text('role','Role or contractor',false),select('user_id','Link an existing authorised account','members'),{key:'active',label:'Available for new assignments',type:'check'}]},
 asset:{title:'Record equipment',action:'asset.save',permission:'plant.capture',button:'Save equipment',description:'Use one equipment identity for engineering, servicing and energy. Proposed assets never count as installed generation.',defaults:{kind:'equipment',state:'proposed'},fields:[text('code','Equipment code'),text('name','Equipment name'),choices('kind','Equipment type',['equipment','tank','generator','solar','battery','meter','vehicle','rig']),choices('state','Equipment state',['proposed','installed','operating','standby','out_of_service','retired']),select('parent_id','Parent equipment / area','assets'),text('location','Location / circuit',false),text('model','Manufacturer / model',false),text('serial','Serial number',false),decimal('capacity','Rated capacity (design, not an observation)'),choices('capacity_unit','Capacity unit',['L','kW','kWh','t/h'],false),day('service_due','Next planned service'),note('notes','Condition / service notes'),evidence]},
 fuel:{title:'Record diesel movement',action:'fuel.record',permission:'plant.capture',button:'Save fuel record',description:'Start each tank with an opening observation, then record actual deliveries and issues. A dip checks the ledger; it never silently adjusts it.',defaults:{kind:'delivery'},fields:[choices('kind','Record type',['opening','delivery','issue','transfer','dip']),select('tank_id','Tank','tanks',true),{...select('other_tank_id','Destination tank','tanks',true),when:v=>v.kind==='transfer'},{...select('asset_id','Equipment refuelled','assets'),when:v=>v.kind==='issue'},decimal('litres','Measured quantity, L',true),{key:'occurred_at',label:'Actual observation time',type:'datetime',required:true},text('reference','Docket / observation reference'),note('notes','Source / destination / measurement notes'),evidence]},
 energy:{title:'Record energy observation',action:'energy.record',permission:'plant.capture',button:'Save observation',description:'Enter the measured interval amount, not a cumulative lifetime meter. Preserve the start/end readings in the method or evidence. Use separate records for generation and load.',defaults:{kind:'diesel_generation'},fields:[select('asset_id','Metered equipment','assets',true),choices('kind','Observation type',['diesel_generation','solar_generation','grid_import','load','generator_hours','battery_soc']),{key:'started_at',label:'Interval starts',type:'datetime',required:true},{key:'ended_at',label:'Interval ends / observed at',type:'datetime',required:true},decimal('amount','Measured interval kWh / running h / battery %',true),text('method','Meter IDs, start/end readings or observation method'),note('notes','Coverage / outage notes'),evidence]},
 fuelVoid:{title:'Void mistaken fuel record',action:'fuel.void',permission:'plant.review',button:'Void record',description:'Retain the original. The resulting full tank ledger must still be valid; then enter the corrected observation.',fields:[note('reason','Correction reason',true)]},
 energyVoid:{title:'Void mistaken energy observation',action:'energy.void',permission:'plant.review',button:'Void observation',description:'Retain the original observation before recording a corrected interval.',fields:[note('reason','Correction reason',true)]},
 engineering:{title:'Record engineering revision',action:'engineering.save',permission:'plant.capture',button:'Save engineering record',description:'A concept is not the operating configuration. Independent named review and verified source evidence are required for approval and commissioning.',defaults:{state:'concept'},fields:[text('title','Revision title'),text('reference','Drawing / revision reference'),choices('state','Engineering state',['concept','review','approved','implementing','commissioned','as_built','superseded']),select('program_id','Implementation program','programs'),select('supersedes','Supersedes revision','engineering'),note('notes','Design basis / decision / commissioning evidence'),evidence]},
 cost:{title:'Record program cost',action:'cost.record',permission:'commercial.write',button:'Save cost reference',description:'Keep estimates, commitments and invoiced actuals separate. These are source-linked project records, not a payable or an accounting-system posting.',defaults:{kind:'estimate',currency:'AUD'},fields:[select('program_id','Program','programs',true),choices('kind','Cost basis',['estimate','commitment','actual']),decimal('amount','Amount',true),text('currency','Currency'),text('reference','Quote / contract / invoice reference'),{...day('occurred_on','Document date'),required:true},evidence]},
 costVoid:{title:'Void program cost reference',action:'cost.void',permission:'commercial.write',button:'Void cost reference',description:'Preserve the source record and reason rather than rewriting history.',fields:[note('reason','Reason',true)]},
 spare:{title:'Add critical spare',action:'spare.save',permission:'plant.capture',button:'Save spare',description:'Track only items that matter to uptime. Counts and usage are recorded as movements, not edited totals.',defaults:{unit:'each',reorder_at:'0'},fields:[text('code','Part / stock code'),text('name','Spare name'),select('asset_id','Compatible equipment','assets'),text('location','Storage location',false),text('unit','Stock unit'),decimal('reorder_at','Reorder threshold',true)]},
 spareMove:{title:'Record spare movement',action:'spare.move',permission:'plant.capture',button:'Save stock event',description:'A physical count is a check, not an unexplained stock adjustment. Link parts used to the work that consumed them.',defaults:{kind:'receipt'},fields:[select('spare_id','Spare','spares',true),choices('kind','Movement',['opening','receipt','use','count']),decimal('quantity','Quantity',true),select('task_id','Maintenance / work item','tasks'),{key:'occurred_at',label:'Actual stock event time',type:'datetime',required:true},text('reference','Receipt / job / count reference')]},
};

for(const [key,advanced] of Object.entries({program:['personnelIds','method','plannedMetres','plannedHoles','budget','currency'],task:['contributors','parent_id','asset_id','source_file_id','dependencyIds'],asset:['parent_id','model','serial','capacity','capacity_unit','source_file_id'],person:['user_id']}))for(const f of workflowSpecs[key].fields)if(advanced.includes(f.key))f.advanced=true;

workflowSpecs.spareVoid={title:'Void mistaken spare movement',action:'spare.void',permission:'plant.review',button:'Void stock event',description:'Preserve the original event; the remaining historical stock must stay valid.',fields:[note('reason','Correction reason',true)]};
